### ISSUE TITLE
http.setHeader expected 3 arguments, but got 2

### ISSUE THREAD

**Issue by brownkevg** [silkimen/cordova-plugin-advanced-http#100]
documentation says that I can setHeader with only 2 params but but when i updated to npm @ionic-native/http@4.7.0 gives me the error expected 3 arguments, but got 2. It then references this line as the problem  `this.http.setHeader("Content-Type", "application/json");` I fixed this error by going back to @ionic-native/http@4.6.0, which is the package I had originally when writing this code. Also for more context this code is used in an ionic app for android. Using version 4.7.0 keeps me from building my app as I get an error "Failed to transpile program". Thanks for looking at this!
<img width="740" alt="error" src="https://user-images.githubusercontent.com/14822164/38696580-7419129e-3e44-11e8-9d47-7188584c76a3.png">

**Comment by silkimen** [comment]
You meant ionic-native@4.7.0 not npm, right?

I can't make the first parameter optional in typescript, but in the JS code it's the first param you can omit. That's the reason I didn't make it optional in TS.

You'll need to write following code to achieve the same result:
```TypeScript

this.http.setHeader('*', 'accept', 'application-json');
```

**Comment by brownkevg** [comment]
Yes, specifically to @ionic-native/http@4.7.0. Just wanted to make sure this wasn't an oversight as the documentation specified either would work and that @ionic-native/http@4.6.0 was handling the 3 variables. Didn't realize that TS would cause that type of issue.
Thanks for the explanation!

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
