### ISSUE TITLE
Support "multipart/form-data" requests

### ISSUE THREAD

**Issue by lovesasha** [silkimen/cordova-plugin-advanced-http#101]
Hi,
Thank you for providing such a nice plugin.

Now I met a problem that I can't send multipart/form-data type request. The data serializer doesn't support this content-type. And if I specify the content-type header to 'multipart/form-data', and push string type data in the data field, it can't send the request anymore. And if I push js object( such as {a: 1} ), it can post the data, but the request data cannot be resolve in Charles or the background server. And it's also different from the purpose.

I hope you can reply me and tell me how to resolve it. I need  it very much.

Thank you!!!

**Comment by silkimen** [comment]
Hi Sasha,

this plugin doesn't support this content type, atm. When you are overriding the content type header it's not changing the behavior of the serializer. That's the reason your backend server can't read the data anymore.

You won't be able to achieve this without having a new serializer implemented. So this is a feature request and I can't promise it will be implemented anytime soon.

**Comment by lovesasha** [comment]
Thank you for replying me!

Hope you can implement this function in the future~

Thanks again!

**Comment by iamjoyce** [comment]
In that case, does it mean that we only have two options to send file to the server?

1. Send by base64 string with `post`

2. Send file with `uploadFile` and other variables with `post`

**Comment by abhijithaccion** [comment]
> Hi Sasha,
> 
> this plugin doesn't support this content type, atm. When you are overriding the content type header it's not changing the behavior of the serializer. That's the reason your backend server can't read the data anymore.
> 
> You won't be able to achieve this without having a new serializer implemented. So this is a feature request and I can't promise it will be implemented anytime soon.

Hello silkimen

i am facing the same issue is there a resolution to this.

**Comment by jsasmitha** [comment]
Hello silkimen

Even I'm facing the same,  Is there any solution for this??

**Comment by rezendeneto** [comment]
Hi @silkimen, I'm facing the same issue. Is there already a solution for this?

**Comment by Zertu** [comment]
i use the cordova-plugin-file-transfer to solve the problem

**Comment by HansKrywaa** [comment]
@silkimen I see you moved it to done, when will it be released?

**Comment by silkimen** [comment]
@HansKrywaa  it is already released in v2.3.0
