### ISSUE TITLE
"data" argument supports only following data types: Object

### ISSUE THREAD

**Issue by leemerlas** [silkimen/cordova-plugin-advanced-http#106]
I'm currently getting the following error in my console: 

![screenshot_1](https://user-images.githubusercontent.com/31193012/39401841-3f203554-4b82-11e8-8dd8-47391d021e32.png)

I followed what was stated in the documentation for sendRequest. Here's my code: 
    
    var prisoner = localStorage.getItem('prisoner');
    var tokens = localStorage.getItem('token');
    
    const options = {
        method: 'post',
        contentType: 'application/json; charset=utf-8',
        data: JSON.stringify({ nameP: prisoner, vDate: this.visitDate, numV: this.visitCount, timeV: this.visitTime, relation: this.visitRelation }),
        dataType: "json",
        crossDomain: true,
        headers: {'x-access-token': tokens}
    };

    cordova.plugin.http.sendRequest('http://127.0.0.1:5000/api/user/visitation', options, response => {
        try {
            response.data = JSON.parse(response.data);
            console.log(response.data.message);
            visit_succ.present();
        } catch (e) {
            console.error('JSON parsing error');
        }

    },  response => {
      // prints 403
        console.log(response.status);

      //prints Permission denied
        console.log(response.error);
    });

What am I missing here?

**Comment by chax** [comment]
Don't use JSON.stringify, plugin does serialization automatically.

**Comment by leemerlas** [comment]
@chax so should it be 

    data: { nameP: prisoner, vDate: this.visitDate, numV: this.visitCount, timeV: this.visitTime, relation: this.visitRelation }

instead?

**Comment by chax** [comment]
Try it.

**Comment by leemerlas** [comment]
Well I know its getting sent now, but in my server, one argument is getting logged as a none-type, which is `pid`, and I get it through `var pubid = localStorage.getItem('public_id');`

    data: { nameP: prisoner, vDate: this.visitDate, numV: this.visitCount, timeV: this.visitTime, relation: this.visitRelation, pid: pubid }

In my web app, it works fine and this variable is sent to my server. But during the request, it mysteriously disappears. Any idea why? Could this be a bug?

**Comment by ht-itsoft** [comment]
You can use HttpClient in @angular/common/http to call API. 

`import { Component } from '@angular/core';
import { NavController, Platform } from 'ionic-angular';
import { HttpClient} from '@angular/common/http';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html',
})
export class HomePage {

  constructor(
    public http: HttpClient
  ) {

    platform.ready().then(() => {
      this.http.post(url, data).subscribe(
        response => {
          console.log(JSON.stringify(response));
        }
      );
    })
  }

}`

**Comment by Boby** [comment]
I have a problem where I tried :
this.httpClient.post('http://test.com/api', {
      "name": { "value": "test03" },
      "mail": { "value": "test03@gmail.com" },
      "pass": { "value": "123"}
    },
    {'Content-Type': 'application/json'}).catch(res=>{
      console.log(res);
    });

on my symfony serializer its throwing syntax error but when I am using postman, POST method its working fine

**Comment by shurvir49** [comment]
Any solution? still facing same issue
