### ISSUE TITLE
Browser should support native browser fetch

### ISSUE THREAD

**Issue by BorntraegerMarc** [silkimen/cordova-plugin-advanced-http#108]
In this section it's specified that browsers are supported: https://github.com/silkimen/cordova-plugin-advanced-http#browser-support

However browser support is only enabled when `cordova` is used. Which is not always the case. For example not when I'm locally developing my app without running a production build to include `cordova`.

So by default this library should check if `cordova` is not undefined. And if yes -> it should use the native [browser fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) or [browser XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest)

I would even argue that even when `cordova` is **not** undefined that this library should always use these native ways to do a fetch. So development & production env is the same

**Comment by silkimen** [comment]
Hi Marc, that's an interesting idea, but how do you want to load the web interface? Actually, Cordova is responsible for loading the plugins (native code AND web interface). Without loading Cordova, you won't even have the namespace `cordova.plugin.http` loaded.

**Comment by BorntraegerMarc** [comment]
Good day @silkimen 
thanks for the quick answer. Unfortunately I don't fully understand, what you mean with "how do you want to load the web interface". I thought about having some kind of `index.js` and do a check there:
```
if (!cordova) {
  // We are in a browser, so fetch is available
  cordova.plugin.http.get = async function(data) {
    return await fetch('http://google.ch')
  }
}
```

FYI: I'm more of an web engineer than an cross-platform engineer. So maybe I'm making a conceptional mistake :)

**Comment by BorntraegerMarc** [comment]
For ionic I imagine something like this https://ionicframework.com/docs/native/browser.html could be used

**Comment by silkimen** [comment]
Even if you're using ionic or plain cordova (and you want to build for browser), you still need to load `cordova.js` and build for browser target, e.g. running `cordova build browser`. Otherwise none of your plugins will be loaded and therefore there will be no namespace `cordova.plugin.http` available.

**Comment by BorntraegerMarc** [comment]
ok, I understand @silkimen but wouldn't it be great if we would not have to load cordova by default?
For example one solution could be:
- Add a `index.js` file in the root of this directory
- Add specification that this `index.js` file should be imported in the root of the web project like `require('cordova-plugin-advanced-http')`
- All we do in the `index.js` file is:
```
if (!cordova) {
  // We are in a browser, so fetch is available
  cordova.plugin.http.get = async function(url) {
    return await fetch(url)
  }
}
```
Basically we manually "mock" the cordova object so it can still be used in ONE way across platforms. Web + Native apps. Without needing to build especially the cordova project.

do you think this might work?

**Comment by silkimen** [comment]
Hi Marc, please join my slack channel, so we can discuss this in detail: https://join.slack.com/t/ilkimen/shared_invite/enQtMzYyMDQwMjEwNjU2LTljNTM3ZTc5ZWI0YmYzZGVhOWUzYTkzNmJmMGNkMTlmZjgxZjc5Y2Y3OGFlZGI4ZjhhMjFmMTRjNzU4NGEzZTE

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
