### ISSUE TITLE
How Post Content-Type : application/json

### ISSUE THREAD

**Issue by ayserious** [silkimen/cordova-plugin-advanced-http#110]
How Post Content-Type : application/json 

i try but cannot post.. T___T

have respont 200 but no have something message from server

var data_sent = JSON.stringify(PostParam_data);
  
    window.cordovaHTTP.post("https://175.25.20.188/.....", {data_sent}, {},function(msg) {
                            var data = JSON.parse(msg.data);
                            
                            alert(JSON.stringify(msg));
                            
                            },
                            function(msg) {  
                            alert(JSON.stringify(msg));
                            return false;
                            
                            }
                            );

**Comment by lakadev** [comment]
Hi.

Don't use JSON.stringify

see https://github.com/silkimen/cordova-plugin-advanced-http/issues/106

**Comment by silkimen** [comment]
Hi ayserious, please format your example code snippet properly and try lakadev's advice.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
