### ISSUE TITLE
Set parameter

### ISSUE THREAD

**Issue by TeodorKolev** [silkimen/cordova-plugin-advanced-http#112]
Is it even possible to set parameter in .put request?

**Comment by silkimen** [comment]
Hi TeodorKolev,

the parameters used in a `.get` request are just meant as a convenience function. You can always create the URL yourself containing the query parameters you need e.g. `http://bla.com/blubb?myParam=myValue`.

**Comment by TeodorKolev** [comment]
This isn't working also. I gave up on this.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
