### ISSUE TITLE
Error: {status: -1} on ios

### ISSUE THREAD

**Issue by labeeck** [silkimen/cordova-plugin-advanced-http#114]
I get this error {status: -1} in ios, but works fine in Android.

This is the code I am using

`this.nativeHttp.get(API_URL + url + data, {}, {}).then(res => {
    observer.next(res.data ? JSON.parse(res.data) : '');
    observer.complete();
}, err => {
    let errMsg: any
    try {
        errMsg = JSON.parse(err.error);
        if (errMsg.status == STATUS_ERROR) {
            err.error = errMsg;
        }
    } catch(e) {}
    console.log('error from api service native http');
    console.log(err);
    console.log('error from native api');
    observer.error(err);

})`

The url (API_URL + url + data) is in correct format.

**Comment by iamjoyce** [comment]
1. It will be nice of you to format your codes properly.

2. Did you enable SSL Pinning? If yes, #116 has the same problem.

**Comment by l1nknyto** [comment]
i got similiar problem, my error result is { error: "canceled", status: -1 }

In my case, i am not using SSL pinning.
Request using GET method, working fine. but request using POST method, generating the above error.
And i am right now using self certificate for testing.

Using version 1.11.1.

Thanks for your help ...

**Comment by silkimen** [comment]
@labeeck please format your example code snippet properly and check #116

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!

**Comment by pcsantana** [comment]
For me, the problem was related to encode correctly the url params, like mentioned in [this issue](https://github.com/silkimen/cordova-plugin-advanced-http/issues/149#issuecomment-441344675) .
