### ISSUE TITLE
enableSSLPinning working on Android but not on IOS

### ISSUE THREAD

**Issue by airimiea** [silkimen/cordova-plugin-advanced-http#116]
I am working on an Ionic 2+ project and switching from the Angular http client to this plugin in order to be able to use ssl pinning. I have installed the plugin as instructed [in the Ionic docs](https://ionicframework.com/docs/native/http/). The ssl pinning is working fine on Android but not on IOS. For IOS I have placed my DER certificate in ./platforms/ios/. I have obtained this certificate in DER format by exporting it with firefox. I am using the same file for Android, but placing it in a different folder as instructed in the ionic docs.

Relevant parts from the environment:
```
package.json:
"cordova-ios": "4.5.1",
"@ionic-native/http": "4.7.0",
"cordova-plugin-advanced-http": "1.11.1",
"ionic-angular": "3.7.0",
"@angular/core": "4.4.3",

global npm:
cordova@8.0.0
ionic@3.20.0
ios-deploy@1.9.2
npm@5.6.0

node v8.11.1

IPhone 6
IOS 11.2.5
```

Error:

```json
{"status":-1,"error":"cancelled"}
```

Relevant parts from an Angular service:

```javascript

configureHTTP$ = new ReplaySubject<boolean>(1);

// in the constructor:
platform.ready()
  .then(() => http.enableSSLPinning(true)) // if I comment this line the plugin works on IOS too
  .then(() => {
    http.setDataSerializer('json');
    this.configureHTTP$.next(true);
  });

// where I call post:
this.configureHTTP$
  .flatMap(() => buildRequest$)
  .flatMap((request: any) => this.http.post(this.backendUrl, request, {}))
  .catch(this.handleErr); // Error: {"status":-1,"error":"cancelled"}
```

**Comment by silkimen** [comment]
Did you try putting the cert file in "www/certificates/" folder? This should be working for both Android and iOS.

**Comment by airimiea** [comment]
@silkimen the first suggestion (putting the cert file in www/certificates/) solved my problem. Thank you!

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!

**Comment by jintzz** [comment]
I am getting an issue "plugin not installed", after implementing http.setSSLCertMode('pinning') in my current project. I followed the same steps which are mentioned in https://www.npmjs.com/package/cordova-plugin-advanced-http. Has anyone faced the same issue? Is there any workaround?
