### ISSUE TITLE
Post JSON sends empty data

### ISSUE THREAD

**Issue by AlexOtero32** [silkimen/cordova-plugin-advanced-http#117]
Hi!
I'm tryin to send a POST request to an API, but when it inserts the data into the database, the parameters I send are empty :(
```
let headers = {
          'Content-Type' : 'application/json; charset=UTF-8'
      };
      let body = {
        nombre: this.nombre,
        apellidos: this.apellidos,
        empresa: this.empresa,
        email: this.email
      }
      this.http.post('http://myapiurl/create.php', body, headers)
      .then(function(){
        console.log(JSON.stringify(body));
      }).catch(err => console.log(err.toString()));
```

If I copy the `body` object from the console and paste it in Postman and send it, it seems to work, so I don't think there is an error within the API itself. What am I doing wrong?

The first entry was sent using the module, and the second one copy-pasting the console.log into Postman.
![captura de pantalla de 2018-05-25 19-56-41](https://user-images.githubusercontent.com/11923783/40559087-e0775b66-6055-11e8-8987-b89773497348.png)

**Comment by silkimen** [comment]
Hi Alex,
you need to set the `json` serializer before sending your data. You also don't need to override the content type header. It will default to the value in your snippet when JSON serializer is used. Please read [the docu](https://github.com/silkimen/cordova-plugin-advanced-http#setdataserializer).

**Comment by AlexOtero32** [comment]
Ok, it worked. Thank you!
