### ISSUE TITLE
Issues with Android & iOS on Phonegap

### ISSUE THREAD

**Issue by bozdoz** [silkimen/cordova-plugin-advanced-http#12]
Not sure what could be going wrong here, but I cannot get this plugin to work on Android.  The error I'm receiving is that `cordova.plugin` is undefined.  I've tested this within a handler on the `deviceready` event, I also set an interval to continually check if it becomes defined, but it does not.

Here is part of my config.xml:

```xml
<engine name="android" spec="^6.2.3" />
<engine name="ios" spec="^4.4.0" />
<plugin name="cordova-plugin-advanced-http" spec="^1.5.9" />
```

**Comment by bozdoz** [comment]
Also of note: `cordova.plugin.http` IS defined in browser platform; it just can't seem to execute any functions.

**Comment by bozdoz** [comment]
Also of note: I just tested on ios, and I have the exact same issue: `cordova.plugin` is undefined.

**Comment by silkimen** [comment]
Hi bozdoz,

I am not able to reproduce your problem (on Android and iOS), but you are right concerning browser platform. Can you provide some more information? How did you install the plugin via npm registry or github url?

It's also strange that the object is defined for you on browser, but not on devices 🤔

**Comment by bozdoz** [comment]
The issue seems to be specific to the Phonegap Developer app, which is recommended by Phonegap to test apps.  If I do `phonegap run android` and plug in my phone to test, it works fine (obviously because it's built).  Otherwise, on the Phonegap Developer app, it fails: `cordova.plugin` remains undefined.  I've tested everything I need now, with USB debugging, but every other plugin has worked with the Phonegap Developer app.

**Comment by silkimen** [comment]
Ah ok, thanks for the info. I've never used phonegap (only cordova and sometimes ionic), so I don't even know about this Phonegap Developer App.
Do you know how this works? I mean the iOS and Android source code needs to be compiled to be working. Or do they just use the browser version of the plugin? This might be the reason why it's not working with this app, as we don't support browser target.

**Comment by silkimen** [comment]
Found it: http://docs.phonegap.com/references/developer-app/troubleshoot-faq/

Phonegap developer app only supports some included plugins. But advanced-http plugin is not included in the app and that's the reason why it's not working.
If you want this plugin to be included in the phonegap app, you need to bother the phonegap dev team 😋

**Comment by bozdoz** [comment]
Thanks!  Probably won't, as I'm done my project, but maybe in future projects. 

![bitmoji](https://render.bitstrips.com/v2/cpanel/10211505-173281661_52-s1-v1.png?transparent=1&palette=1&width=246)
