### ISSUE TITLE
SSL Pinning can be bypassed with a proxy (man-in-the-middle attack)

### ISSUE THREAD

**Issue by iamjoyce** [silkimen/cordova-plugin-advanced-http#120]
Certificate pinning can be bypassed with [third-party application](https://github.com/ac-pm/SSLUnpinning_Xposed)

Is there any way to check whether the network is directed to a proxy?

### Steps to replicate

1. Install your application with certificate pinning feature enabled
1. Install [SSLunpinning module with Xposed Framework](https://github.com/ac-pm/SSLUnpinning_Xposed) APK
1. Set-up [Burp Suite Community Edition](https://portswigger.net/burp/communitydownload) to [intercept test device network](https://support.portswigger.net/customer/portal/articles/1841101-configuring-an-android-device-to-work-with-burp)
1. If your server is hosted on HTTPS, install and trust [Burp Suite SSL certificate](https://www.thedroidsonroids.com/blog/how-to-debug-https-traffic-for-android-apps-with-burp-proxy) in your device
1. Submit any API request
1. There is no error message “SSL handshake failed” and request was sent to server. You can see and modify the request on Burp Suite.

**Comment by silkimen** [comment]
Hi iamjoyce,
thanks for the info, but I think there is nothing I can do against. The SSLUnpinning Module seems to register hooks in the system libs of Android. So basically, this is a "problem" of Android, which is not limited to this plugin.
But still for running this kind of scenario you need to have physically access to a rooted device or you need to have a root kit installed, so you can setup this module. I don't think this is a severe problem of this plugin.
