### ISSUE TITLE
SyntaxError: Unexpected EOF

### ISSUE THREAD

**Issue by Ralpharoo** [silkimen/cordova-plugin-advanced-http#121]
I've been having great success with this plugin but have come unstuck on a certain URL.

This throws an unhandled exception 'SyntaxError: Unexpected EOF' error. I've stripped everything back to a basic example which fails every time (regardless of SSL and redirection settings):

```
options = {
  method: 'get',
  data: { },
  headers: { }
};

cordova.plugin.http.sendRequest('https://www.taste.com.au/recipes/loaded-potato-skins/iWP8BULY', options, function(response) {
  // does not get called
  console.log(response.status);
}, function(response) {
  // does not get called
  console.log(response.status);
});
```

Any idea what is happening here? I'm using PGB so do not have the source to debug locally.

Cheers,

**Comment by Ralpharoo** [comment]
Looks like it's a known Cordova bug which they will not fix; https://issues.apache.org/jira/browse/CB-9435

**Comment by silkimen** [comment]
Hi Ralpharoo, thanks for the info. Unfortunately, I can't fix this. I could implement a workaround, which could scan every response for blacklisted chars, but it would slow down everything a lot. So this one won't be fixed, I'm sorry!
If you're controlling the server, you can strip those chars on the server side. If you don't, you can implement a simple reverse proxy which is stripping those chars.

**Comment by Ralpharoo** [comment]
No worries, understand your position. I've seen numerous other plugins implementing such workarounds as this will affect any Cordova user where these characters sneak in. Especially with this plugin where people pull content from external API endpoints/websites they do not have direct control of (which I presume is fairly common).

I'll work around this from our end for now. Thanks for taking a look anyhow (and for your efforts updating this one). Cheers,
