### ISSUE TITLE
body object sequence is scrambled on iOS

### ISSUE THREAD

**Issue by ZieClaw** [silkimen/cordova-plugin-advanced-http#124]
Hello,

I'm running into the following problem, I have a Object with data in it.
It's mean for a PSP api and has to stay the way it is due to the use of a hash of the textual representation.
But the plugin throws the properties around on iOS, something which it does not do on Android.

This is the data I am trying to send:
let content = {Currency:"EUR",AmountDebit: order['grand_total'],Invoice:"Order " + order['order_id'],ContinueOnIncomplete:1,Services:{ServiceList:[{Name:"ideal",Action:"Pay",Parameters:[]}]}}

And this is how I receive it on my test end point to see what is going on:
{"ContinueOnIncomplete":1,"Services":{"ServiceList":[{"Parameters":[],"Name":"ideal","Action":"Pay"}]},"AmountDebit":124.09999999999999,"Currency":"EUR","Invoice":"Order 100024335"}

As you can see the positions of the properties have changed and thus changing the outcome of the hash function. This causes the PSP gateway to reject the request and if I make the data object represent the one send to my endpoint it will change it around again.

**Comment by silkimen** [comment]
Hi ZieClaw, I see your problem. This is happening because the data is serialized and deserialized while it's running through the cordova plugin interface. You can try using the "utf8" serializer instead. But you'll need to serialize your object on your own:

```js
// use utf8 serializer
cordova.plugin.http.setDataSerializer('utf8');

// override content type
cordova.plugin.http.setHeader('*', 'Content-Type', 'application/json');

// serialize your object before sending the data
cordova.plugin.http.post(url, JSON.stringify(content), headers, onSuccess, onFail);
```

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
