### ISSUE TITLE
Not able to send data with complex structure

### ISSUE THREAD

**Issue by IntelliJAbhishek** [silkimen/cordova-plugin-advanced-http#126]
I'm using this plugin in ionic and I can send simple json with json serializer but I'm not able to send this type of json.

```js
{
  "EmployeeId": "string",
  "SelectedOffice": "string",
  "BookingFromDate": "string",
  "BookingToDate": "string",
  "CheckInTime": "string",
  "CheckOutTime": "string",
  "BookingRemarks": "string",
  "EmailId": "string",
  "ContactNumber": "string",
  "SelectedPurpose": "string",
  "OtherPurpose": "string",
  "ReasonPurpose": "string",
  "SelectedLocation": "string",
  "SelectedGuestHouse": "string",
  "EntryMode": "string",
  "Guests": [
    {
      "Name": "string",
      "Gender": "string",
      "OptionalEmployeeId": "string",
      "EmailId": "string",
      "Department": "string",
      "ContactNumber": "string"
    }
  ]
}
```

All other fields are are sent to server but that guest array becomes string and server cannot parse that.. sending same data with angular/common/http is working fine.

**Comment by silkimen** [comment]
Hi IntelliJAbhishek, are you sure, you've setup the "json" serializer? The default one is "urlencoded" and it does not support deep structured data. See [setDataSerializer](https://github.com/silkimen/cordova-plugin-advanced-http#setdataserializer).

**Comment by IntelliJAbhishek** [comment]
@silkimen yes i have set serializer to json. Even i can send simple json requests like this

{ 
    "uname":"string",
    "password":"string",
}

Its working fine but the json in my question i can send.. In one more api i have to send similar type of json it also failed.

**Comment by silkimen** [comment]
Please show us some example code you are running.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
