### ISSUE TITLE
ionic 4: Blank screen

### ISSUE THREAD

**Issue by wilsolutions** [silkimen/cordova-plugin-advanced-http#128]
I've opened an issue on ionic as well, basically I get a blank screen when I add the cordova-plugin-advanced-http.

https://github.com/ionic-team/ionic/issues/14520

**Comment by silkimen** [comment]
Hi wilsolutions, I think there is nothing I can do to solve this problem on my side. Needs to be fixed in ionic-native, right?

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
