### ISSUE TITLE
Feature Request: Additional form data with file upload

### ISSUE THREAD

**Issue by BorntraegerMarc** [silkimen/cordova-plugin-advanced-http#129]
I know from this issue https://github.com/silkimen/cordova-plugin-advanced-http/issues/64 that the plugin does not currently support additional form data with the file upload.

This issue is a feature request to add that functionality

**Comment by iamjoyce** [comment]
#101

**Comment by BorntraegerMarc** [comment]
yeah seems like this is a duplicate. closing this issue...
