### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method getHttpUrlChecked

### ISSUE THREAD

**Issue by ihsanberahim** [silkimen/cordova-plugin-advanced-http#130]
## Current behavior:
Platform Android:
It crash when i do GET request. `HTTP.get`

Platform iOS: 
(everything works fine)

## Error Log:
```
07-18 02:03:40.925 20138-20197/my.app.my E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
    Process: my.app.my, PID: 20138
    java.lang.NoSuchMethodError: No virtual method getHttpUrlChecked(Ljava/lang/String;)Lokhttp3/HttpUrl; in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/app/my.app.my-1/base.apk)
        at okhttp3.internal.huc.OkHttpURLConnection.buildCall(OkHttpURLConnection.java:373)
        at okhttp3.internal.huc.OkHttpURLConnection.getResponse(OkHttpURLConnection.java:435)
        at okhttp3.internal.huc.OkHttpURLConnection.getResponseCode(OkHttpURLConnection.java:491)
        at okhttp3.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at okhttp3.internal.huc.OkHttpsURLConnection.getResponseCode(OkHttpsURLConnection.java:26)
        at com.github.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1717)
        at com.synconset.cordovahttp.CordovaHttp.returnResponseObject(CordovaHttp.java:284)
        at com.synconset.cordovahttp.CordovaHttpGet.run(CordovaHttpGet.java:30)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
```

## My Environment

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v6.14.2
    npm               : 3.10.10 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4.1 Build version 9F2000 

Environment Variables:

    ANDROID_HOME : /Users/me/Library/Android/sdk

Misc:

    backend : pro
```

### Installed plugins
```
com.synconset.imagepicker 2.1.10 "ImagePicker"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-facebook4 2.2.0 "Facebook Connect"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-webview 2.0.0-beta.2 "cordova-plugin-ionic-webview"
cordova-plugin-nativegeocoder 3.1.2 "NativeGeocoder"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.1 "Launch Navigator"
```

**Comment by ihsanberahim** [comment]
modify `project.properties` to use this `cordova.system.library.2=com.squareup.okhttp3:okhttp-urlconnection:3.+`, then it works

**Comment by iamjoyce** [comment]
@ihsanberahim Actually, you can modify the `uk.co.workingedge.phonegap.plugin.launchnavigator` plugin variables instead of changing `project.properties`.

Step 1: Modify `config.xml` and `package.json`

In `config.xml`,

![1](https://user-images.githubusercontent.com/13122245/42866650-bc4b25e6-8a9f-11e8-9561-89e8a25661ff.PNG)

In `package.json`

![2](https://user-images.githubusercontent.com/13122245/42866654-bef59290-8a9f-11e8-89e7-9e704d039a64.PNG)

Step 2: Delete and add platform again

`ionic cordova platform remove android` / `cordova platform remove android` then,
`ionic cordova platform add android` / `cordova platform add android`

Alternatively, you can just remove and add affected plugin

**Comment by ihsanberahim** [comment]
![image](https://user-images.githubusercontent.com/1956846/42868022-d41515f2-8aa3-11e8-81a2-fde792d20e78.png)

Not really. It should auto base on my config.xml but it not refelect the `project.properties`. That is why i need to change it manually.

**Comment by iamjoyce** [comment]
@ihsanberahim I think you will need to

`ionic cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator --variable LOCATION_USAGE_DESCRIPTION="Give some description for your app." --variable OKHTTP_VERSION="3.10.0"`

`cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator --variable LOCATION_USAGE_DESCRIPTION="Give some description for your app." --variable OKHTTP_VERSION="3.10.0"`

You are welcome. I have to thank you instead. This bug hasn't been reported in repositories, so I thought it was an extremely obsure bug 😅.

**Comment by UlisesCeca** [comment]
> It actually, due to conflict with `uk.co.workingedge.phonegap.plugin.launchnavigator` which also use `okhttp3`.
> 
> So, modify `project.properties` to use this `cordova.system.library.2=com.squareup.okhttp3:okhttp-urlconnection:3.+`, then it works.

where is that properties file?

**Comment by Xstoudi** [comment]
I have the same problem but I can't find where the conflict is :
```
cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Comment by cgcman** [comment]
in my case, the problem was Firebase dependencies, i fix with this solution for every Firebase implementation.

```
implementation ('com.google.firebase:firebase-messaging:20.3.0'){
     exclude group: 'com.squareup.okhttp3', module: 'okhttp'
}
```
