### ISSUE TITLE
Problem with uploadFile method

### ISSUE THREAD

**Issue by Hanzofm** [silkimen/cordova-plugin-advanced-http#134]
Hi,

I am trying to upload a image file from my Ionic project to my backend. I obtain the image file_uri from the camera/photogallery with the cordova camera plugin. This are the content of the parameters supplied to the request:

```

path: amazon_laravel_symfony_php_path;
data: {
parameter1:'value'
parameter2:'value2'
...
}
headers: {"Authorization":"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSU","Accept-Language":"es"}
urlLocalFile: "file:///storage/emulated/0/Android/data/com.name.app/cache/1533631321019.jpg"
name: name_parameter

```
This is the request

```
this.http.uploadFile(path, data, headers, urlLocalFile, name)
                        .then(response => {
                            console.log("UPLOAD FILE RES"+JSON.stringify(response))
                        })
                        .catch(error => {
                            console.log("UPLOAD FILE ERROR"+JSON.stringify(error))
                        });
```

When I do the request the response jumps to catch and this is log

`"Error: advanced-http: invalid params object, needs to be an object with strings
    at checkKeyValuePairObject (http://192.168.2.1:8100/plugins/cordova-plugin-advanced-http/www/helpers.js:61:11)
    at checkParamsObject (http://192.168.2.1:8100/plugins/cordova-plugin-advanced-http/www/helpers.js:112:10)
    at Object.handleMissingOptions (http://192.168.2.1:8100/plugins/cordova-plugin-advanced-http/www/helpers.js:245:13)
    at Object.sendRequest (http://192.168.2.1:8100/plugins/cordova-plugin-advanced-http/www/advanced-http.js:83:23)
    at Object.uploadFile (http://192.168.2.1:8100/plugins/cordova-plugin-advanced-http/www/advanced-http.js:123:28)
    at callCordovaPlugin (http://192.168.2.1:8100/build/vendor.js:74541:43)
    at http://192.168.2.1:8100/build/vendor.js:74567:28
    at http://192.168.2.1:8100/build/vendor.js:61959:17
    at new t (http://192.168.2.1:8100/build/polyfills.js:3:21506)
    at tryNativePromise (http://192.168.2.1:8100/build/vendor.js:61958:20)"`

Other advanced http methods like POST works fine with no string params.

The backend waits the image on the 'name_parameter' param and If i do a Postman request with post mode and multipart header works fine.

What I am doing wrong?

**Comment by silkimen** [comment]
Hi Hanzofm, the error message means that your parameters object (second parameter "data" in your code snippet) contains values which are not strings. Please check this object.

**Comment by darrelmen** [comment]
Hi,

Im also having issue with uploading file using https on both android and ios Im not getting any error and Im getting a response  back from the server but it is not uploading the file.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!

**Comment by aecvargas** [comment]
I'm also having issues with uploadFile. I am uploading it to `attachments.php` but `$_FILES` seems to be empty and i'm not quite sure why. 

[https://stackoverflow.com/questions/60486898/cordova-advanced-http-plugin-uploadfile-unable-to-access-files-on-server](StackOverflow Question)
