### ISSUE TITLE
Browser: Content-Type header non overwritable

### ISSUE THREAD

**Issue by glen442** [silkimen/cordova-plugin-advanced-http#136]
Background:
I am trying to implement a CORS work around. The angular-http stuff works fine, but not on IOS since the Webview update. I have removed non-relevant (working) headers for the sake of readability.

```
console.log("Default header: "+JSON.stringify(this.cors_http.getHeaders("*")));

this.cors_http.setDataSerializer('utf8');
console.log("After serializer header: "+JSON.stringify(this.cors_http.getHeaders("*")));

this.cors_http.setHeader("*", "Content-Type", "text/xml; charset=UTF-8"); 
console.log("After setHeader header: "+JSON.stringify(this.cors_http.getHeaders("*"))); 

this.cors_http.post(url, xmlString, additionalHeaders)
   .then(...)
   .catch(error => {
console.log("error: "+error.error);
alert("error: "+error.error);
  });
```

Console:
```
Default header: null
network-service.ts:222 After serializer header: null
network-service.ts:228 After setHeader header: {"Content-Type":"text/xml; charset=UTF-8"}
Failed to load resource: the server responded with a status of 415 (Cannot process the message because the content type 'text/plain; charset=UTF-8 text/xml; charset=UTF-8' was not the expected type 'text/xml; charset=utf-8'.)
```

It seems that the header is correct until the POST is run, where it appends the correct value to an undocumented default. Any suggestions?

I am testing this on: 
`ionic cordova run browser`
The fact that its my back end server returning 415 tells me its not a browser/cordova incompatibility issue.

Trying to run on an android device (ionic cordova run android -l -c --debug) results in cordova not being available - which is a separate issue not related to this one. Running normally on an android device (ionic cordova run android) results in a blank error message ("error: ").

I don't currently have an IOS device to test on.

Setting the host explicitly didn't make a difference.

ionic info

Ionic:

   ionic (Ionic CLI)  : 4.0.1 (C:\Users\glen442\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, browser 5.0.3

System:

   NodeJS : v6.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 3.10.10
   OS     : Windows 10

Environment:

   ANDROID_HOME : C:\Users\glen442\AppData\Local\Android\Sdk\tools\Sdk

**Comment by glen442** [comment]
After a deeper dive in the lib code:

[Here](https://github.com/silkimen/cordova-plugin-advanced-http/commit/6877fbdb6546e483802d1f44226acc3013987a38#diff-6364ee7b2c02b5d25c6574467b7a5a6e) is where the "undocumented default" seems to be introduced (on android, at least).
Thats line 156 in file src/android/com/synconset/cordovahttp/CordovaHttp.java

That seems a reasonable default. I am currently investigating why setting the headers manually does not override this.

**Comment by glen442** [comment]
Workaround for use with:
`'ionic cordova run browser'`

in file:
<app folder>\platforms\browser\platform_www\plugins\cordova-plugin-advanced-http\src\browser\cordova-http-plugin.js

on line 114, comment out the setRequestHeader() like so:
```
    case 'utf8':
      //xhr.setRequestHeader('Content-Type', 'text/plain; charset=utf8'); // line 114
      processedData = data.text;
      break;
```
This will stop the default 'text/plain' header from being added.
It seems the appending of headers (rather than overwriting) is happening in the underlying XMLHttpRequest() browser code.

On a side note, as the 'browser' platform uses XMLHttpRequest(), CORS is enforced.

**Comment by silkimen** [comment]
Hi glen442, thank you for your detailed investigation on this issue. The problem is indeed caused by the fact that the browser merges the values. See [MDN XMLHttpRequest.setRequestHeader()](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader):
> If this method is called several times with the same header, the values are merged into one single request header.

But this problem only affects the browser platform. You can override the content type on Android and iOS even though there is a default value set.

I'll implement a check for overridden content type to prevent this issue.

> On a side note, as the 'browser' platform uses XMLHttpRequest(), CORS is enforced.

Yes, that's absolutely right. The plugin supports a very restricted set of features on browser platform and it's just meant for testing purposes.

**Comment by glen442** [comment]
Just to add, in an earlier post I mentioned:

>  Running normally on an android device (ionic cordova run android) results in a blank error message ("error: ").

This was from an error in my code, and not related to this issue.
