### ISSUE TITLE
iOS: Exception / App stops on sending any request

### ISSUE THREAD

**Issue by corypheus** [silkimen/cordova-plugin-advanced-http#140]
Hi,

I'm getting the following error message upon sending any request on iOS 11.4.1. Building and launching to iPad works fine but firing a request leads to error.
I'm using Ionic and I enabled SSL Pinning (+ allowAllCerts) and DER certificate within folder www/certificates.

`[__NSArrayM length]: unrecognized selector sent to instance`

It pops up within AFURLRequestSerialization.m

    [self.HTTPRequestHeaders enumerateKeysAndObjectsUsingBlock:^(id field, id value, BOOL * __unused stop) {

        if (![request valueForHTTPHeaderField:field]) {

            [mutableRequest setValue:value forHTTPHeaderField:field]; //xcode points to this line

        }
    }];`

dependencies:

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

    cordova-plugin-advanced-http: 1.5.10

Any help is appreciated.
Thanks
Cory

**Comment by silkimen** [comment]
Hi corypheus, please try updating to new version (2.0.2) of this plugin. "allowAllCerts" was removed in version 2.0.0, because it lead to many problems.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
