### ISSUE TITLE
plugin_not_installed

### ISSUE THREAD

**Issue by JoelAH** [silkimen/cordova-plugin-advanced-http#141]
Hi, I installed the plugin as stated in the ionic docs, and also included it in the ap module, but I get this error on catch "plugin_not_installed". I dont know what to do now.

**Comment by litianyangz** [comment]
Mine is the same

**Comment by silkimen** [comment]
Hey guys, actually this sounds like an ionic-native problem not related to the plugin itself. Please open an issue [over there](https://github.com/ionic-team/ionic-native). Please feel free to open a new issue, if it comes out that it's indeed a plugin error!
