### ISSUE TITLE
http post not being executed on android/ios simulator

### ISSUE THREAD

**Issue by darrelmen** [silkimen/cordova-plugin-advanced-http#143]
there is no issue using http get however when using http post, the code does not  execute it. I try to follow through android studio debugger and it is ignoring the action for "post".
Ionic 3.9.2
cordova-plugin-advanced-http (2.0.0, 2.0.1)
tried reinstalling all plugins and rebuilding the platform from scratch still no luck.

**Comment by osrl** [comment]
I think http get is not working either.

**Comment by silkimen** [comment]
Hi guys, please update to latest version and check if the problem still occurs. Closing this, feel free to open a new issue, if this won't solve your problem!
