### ISSUE TITLE
Is it possible to exchange cookies between this plugin and browser $http ?

### ISSUE THREAD

**Issue by pliablepixels** [silkimen/cordova-plugin-advanced-http#147]
Hi, a while ago I [asked](https://github.com/silkimen/cordova-plugin-advanced-http/issues/81) a harder question but now I have a hopefully easier one:

**Question**:
Is it possible to somehow "share" a cookie between this plugin and `$http` calls that the browser makes?

**Context**:
1. I use this plugin to "log in" to a website (say `http://server/login.json". This in turn sets a `ZM_SESSID` cookie which is `httpOnly`. All subsequent plugin based HTTP requests use this cookie, so all good.

2. However, I also need to display static jpeg images from that server using `<img src="http://server/view_image?id=12" />`  but the server will only return the image if it detects `ZM_SESSID`. Given these are two different HTTP contexts (I think), the server rejects it.

(I am aware that I can do a manual `cordova http get` and convert the data to base64 and display it in image src, but base64 takes too much memory)

Thank you!

**Comment by swathi2378** [comment]
Hi @pliablepixels How did you solve your issue?
