### ISSUE TITLE
XML API calling not working with latest version

### ISSUE THREAD

**Issue by dhaneshgosai** [silkimen/cordova-plugin-advanced-http#152]
I am using cordova-plugin-advanced-http plugin for API calling and all JSON enabled api working fine but I have one XML embedded API which is working fire in Postman but while I call it from ionic its param not getting at server end.

Below is my code for XML api:

**Type 1:**
```

let headers = {
          "Content-type": 'text/xml; charset=utf-8',
          "Authorization": token,
        };

    let xmlBody =
      '<ServiceRequest>' +
      '<CseNumber>' + caseNumber +
      '</CaseNumber>' +
      '</ServiceRequest>'

    this.httpPlugin.setDataSerializer('utf8');

    this.httpPlugin.post('https://test.com/Service', xmlBody, headers).then((response) => {
      console.log("XML Response : ", JSON.stringify(response.data));
      xml2js.parseString(response.data, function (err, result) {
        console.log("XML parser success:", result);
        console.log("XML parser error:", err);
        if (result) {
          resolve(result);
        } else {
          reject(err);
        }

      });
    }).catch(error => {
      if (error.status == 403) {
        console.log("Token expired : " + JSON.stringify(error));
      } else {
        console.log("Error : " + error.error);
        console.log("Error " + JSON.stringify(error));
        reject(error);
      }
    });
```

**Type 2:**

```
let xmlBody = '<ServiceRequest>' +
      '<CaseNumber>' + caseNumber +
      '</CaseNumber>' +
      '</ServiceRequest>';

    console.log("XML Body", xmlBody)

    // this.httpPlugin.setRequestTimeout(60);
    this.httpPlugin.setDataSerializer('utf8');

    this.httpPlugin.setHeader('*', 'authorization', token);
    this.httpPlugin.setHeader('*', 'Content-Type', "application/x-www-form-urlencoded");

    this.httpPlugin.post('https://test.com/Service', xmlBody, {}).then((response) => {
      console.log("XML Response : ", JSON.stringify(response.data));
      xml2js.parseString(response.data, function (err, result) {
        console.log("XML parser success:", result);
        console.log("XML parser error:", err);
        if (result) {
          resolve(result);
        } else {
          reject(err);
        }

      });

    }).catch(error => {
      if (error.status == 403) {
        console.log("Token expired : " + JSON.stringify(error));
      } else {
        console.log("Error : " + error.error);
        console.log("Error " + JSON.stringify(error));
        reject(error);
      }

    });
```

All time its throwing error from server and with same request I can able to get data in postman as well as Native iOS code.

I referred this issue on github but still no success.

Some thing I am missing though its not able to get data on server.

Help me to solve this issue.

**Comment by silkimen** [comment]
Type2 won't work for sending your XML data as a string. The serializer will try to interpret your string as an JS object. So stick to Type1. What exactly is your problem? What's the error message?

**Comment by dhaneshgosai** [comment]
Hey,

Thanks for your comment and what I am facing is my XML body not reaching to server end same thing I m able to send it through native iOS code.

Can you please check above code and let me know what’s wrong with above code.

Thanks once again for looking into my issue.

**Comment by silkimen** [comment]
Type1 should be working. So, you don't have an error message? What's the body content you are receiving on server side? Is it empty? What's the response on the client side? Do you have log files from server side?

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
