### ISSUE TITLE
Strange behaviour in Cookie handling on iOS

### ISSUE THREAD

**Issue by RikdeBoer** [silkimen/cordova-plugin-advanced-http#153]
Thanks so much for this plugin, it works great for me on both Android and iOS, in particular in background, which is superb as using straight `fetch()` calls in Javascript will grind to a halt after 5 minutes thanks to Google's stupid policy in Chrome.

My question is what **headers**/parameters do I need to pass to `cordova.plugin.http.sendRequest`, so that I obtain equivalent functionality of the `credentials: 'include'` option of `fetch()`

My app creates a logged-in session on a server and I wish that the session credentials are passed on subsequenst HTTP POSTs with the `sendRequest` call. 
Currently in my setup this is not happening and therefore the server returns a _403 Permission Denied._

Using fetch() (pseudo-code)

```
      const fetchOptions = {
        method: 'post',
        credentials: 'include', // so that session cookie is conveyed
        body: formData
      }
      fetch(url, fetchOptions)
```

Using this plugin:

```
        cordova.plugin.http.sendRequest(url,
          { method: 'post',
            data: data,
            headers: ???
          },
          response => { },
          response => { console.log(response.error) }
        )
```

**Comment by RikdeBoer** [comment]
Dug a little deeper.

First of all, I believe that the cookies aren't being set correctly. The attribute name 'Cookie' is being used. I believe it should be 'Set-Cookie'. 
So I fixed `getCookieHeader` as follows:

```
function getCookieHeader(url) {
  // RdB: The following original line is incorrect
  // return { Cookie: cookieHandler.getCookieString(url) };
  // Instead, this works:
  var header = { }
  header['Set-Cookie'] = cookieHandler.getCookieString(url);
  return header;
}
```

With this change my app started working on iOS, that is no more 403 errors, as the login credentials are now properly passed to the server.

However, I still experience 403's with the same cordova-powered app on Android.

There must be some additional header to set, which we don't have to set when using `fetch()` ...

**Comment by silkimen** [comment]
Hi RikdeBoer,

it needs to be **Cookie** not **Set-Cookie** in _cordova-plugin-advanced-http/www/helpers.js_, because this function is returning the data which is sent to the server, not the data received from the server. See [RFC6265](https://tools.ietf.org/html/rfc6265) specs, especially [section 4.1](https://tools.ietf.org/html/rfc6265#section-4.1) and [section 4.2](https://tools.ietf.org/html/rfc6265#section-4.2).

So the problem must be somewhere else. But I don't have an idea, atm. I think you should check your server logs to see which headers you are receiving.

**Comment by RikdeBoer** [comment]
@silkimen 

Thanks for the references. Yes I believe you are right and I had it mixed up.

But here's the weird part.
It is not, as I first suspected, the _presence_ of 'Set-Cookie' in the header, it is about the _absence_ of 'Cookie', at least with iOS.

When I change function `getMergedHeaders()` to NOT merge in the 'Cookie' header, i.e. comment-out this line:

`  //mergedHeaders = mergeHeaders(mergedHeaders, getCookieHeader(url));`

... then everything works perfectly on the iPhone (simulator) for both GET and POST !

However on Android I get a 403 for both GET and POST,  due to the user not being acknowledged as being logged in.
This happens with or without the 'Cookie' header merged-in as above.

But when I look at the Request Headers as they arrive on the server, I see, for iOS:

AUTHORIZATION: 
HOST: mysite.com
**COOKIE**: SSESSffe6c88c73c1ef6b6daab638079513a8=labQT4PO0TQZnJvwycAXd5OKktMaVFc5dQ_84wTxVXQ
CONNECTION: keep-alive
ACCEPT: */*
USER-AGENT: myapp (iPhone; iOS 11.4; Scale/3.00)
ACCEPT-LANGUAGE: en;q=1
ACCEPT-ENCODING: br, gzip, deflate
REFERER:

So in iOS the Cooke is there after all, even though I suppressed the auto-merging of it in function `getMergedHeaders()`. Something somewhere must have re-inserted it!

If I don’t suppress it (ie use this plugin’s original code), then on iOS, the cookie shows up in the request header, twice:
COOKIE: SSESSffe6c88c73c1ef6b6daab638079513a8=6eWjlESIIivPMUZlMRuLuerpPjPLo_LdPnjjT4Bbt3A; SSESSffe6c88c73c1ef6b6daab638079513a8=6eWjlESIIivPMUZlMRuLuerpPjPLo_LdPnjjT4Bbt3A
And the POST request fails.

Whereas on Android, the Cookie is there as a single copy, which looks fine, but still doesn’t work, i.e. produces a 403 Permission Denied.

AUTHORIZATION: 
ACCEPT-CHARSET: UTF-8, ISO-8859-1
COOKIE: SSESSffe6c88c73c1ef6b6daab638079513a8=B6lk_uqee4HaUbe7uOTh_8Fo1mJWWI3WYA84_aqzkt0
USER-AGENT: Dalvik/2.1.0 (Linux; U; Android 8.0.0; Android SDK built for x86 Build/OSR1.180418.003)
HOST:  mysite.com
CONNECTION: Keep-Alive
ACCEPT-ENCODING: gzip
REFERER:

No such issues on iOS or Android when replacing `sendRequest()` by `XMLHttpRequest` or `fetch() `(and no messing with cookies required).

But, as mentioned, I cannot use XMLHttpRequest or fetch() in plain javascript code on Android because when running in the background these  processes are stopped after 5 minutes and I need my app to send updates continuously, for hours.

**Comment by RikdeBoer** [comment]
XCode forced me to upgrade to iOS 12.0 and update dependencies.
After re-compiling everything, iOS still behaves very much the same, except that the call to `getCookieHeader()` no longer returns a double copy of the cookie. Just a single one, as it does on Android.
However, the fact remains that for iOS at least you have to suppress the merging-in of the result of `getCookieHeader()` in  `getMergedHeaders()`. Then on iOS the result is that "some code, somewhere" puts the cookie in anyway and it works. 
The request headers on arrival at the server are identical, but one produces 403 and the other does not.
Go figure.

**Comment by silkimen** [comment]
Hi RikdeBoer, I'm sorry for my late response, been very busy the last two months. Your issue is very interesting. But something, somewhere needs to be different in the received data. Maybe something in the body? Otherwise, I have no clue why this is happening.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
