### ISSUE TITLE
android version 7.1.1 force close

### ISSUE THREAD

**Issue by warbadev** [silkimen/cordova-plugin-advanced-http#154]
hi i upgraded my android build to cordova android 7.1.1 (latest version) and when ever i use the plugin my app gets force close and cant get any error message to know whats the issue but after debugging and disabling calling this plugin my app works fine so please can u update it to support the latest version

**Comment by abdellaui** [comment]
got the same problem... do u got a solution?

**Comment by aiguy110** [comment]
Could you elaborate a little on exactly how you updated gradle? The global gradle installed on my system is 4.10.2, but I'm still having this issue. Do you have to update your android platform configuration somehow? Have played around a little with build.gradle with no luck.

**Comment by silkimen** [comment]
Closing this, because it's not a problem related to this plugin. Please check-out gradle and cordova documentation on how to update gradle version.
