### ISSUE TITLE
Response data being converted into a string, instead of an object.

### ISSUE THREAD

**Issue by Bengejd** [silkimen/cordova-plugin-advanced-http#156]
When receiving a post response, the response data is being generated as a string, instead of being displayed as a data object. It's in Object format, but it's just a string, instead of an object? I think it has something to do with the serializer response.

**Comment by silkimen** [comment]
Yes, that's right. Please read [docu:success](https://github.com/silkimen/cordova-plugin-advanced-http#success). Data returned from server is always a string. You need to parse it yourself e.g. parsing a string by running `JSON.parse(response.data)`.

The serializer setting is only for configuring how to interpret the data you will be sending (and to configure default headers). It's not meant for parsing the response.

Closing this, feel free to open a new issue, if this won't solve your problem!
