### ISSUE TITLE
Remove header method

### ISSUE THREAD

**Issue by vosecek** [silkimen/cordova-plugin-advanced-http#158]
How to remove header set by setHeader() method? Setting empty value does not work.

**Comment by CS-Tao** [comment]
+1，I want to remove user-agent. Does anyone konw the method?

**Comment by fer1994** [comment]
I want too, i cant back the json response in UTF8 :/

**Comment by CS-Tao** [comment]
> I want too, i cant back the json response in UTF8 :/

Have you tried this api: [setdataserializer](https://github.com/silkimen/cordova-plugin-advanced-http#setdataserializer) ?

**Comment by silkimen** [comment]
Hey guys, it's not supported to remove headers, but actually you can overwrite an header by setting an empty value.

e.g.
```js
cordova.plugin.http.setHeader('*', 'User-Agent', '');
```

will result in an empty User-Agent value:
<img width="899" alt="bildschirmfoto 2018-12-13 um 11 42 00" src="https://user-images.githubusercontent.com/4717881/49933662-8b616700-fecc-11e8-8636-83fa38254925.png">

**Comment by homeportcz** [comment]
> Hey guys, it's not supported to remove headers, but actually you can overwrite an header by setting an empty value.

This does set empty value, but the header does exist. This is problem especially for Authorization header, some servers expect value if Authorization header is defined and fail to authorize request, because it expects Bearer.

**Comment by kish726** [comment]
I have the same problem. I am doing a post request to get my access token and post that i am doing a GET request to get the user information. for the GET request i am passing authorization token as header .Once this header is set then if i call any post after that authorization token is going in the headers and all my calls are failing. i am not able to remove the authorization token from the header. IS there any method to remove the authorization token from the header ( not like setting it to empty).

**Comment by silkimen** [comment]
Headers which were previously set via `setHeader()` can be removed by passing null value in v3.0.0+. But it's not supported to remove default headers like "User-Agent".
