### ISSUE TITLE
Body as Xml String

### ISSUE THREAD

**Issue by pablocabra** [silkimen/cordova-plugin-advanced-http#159]
Hi guys, I'm trying to make a post request where the body is not an Object is an String but it sends the following error:

advanced-http: "data" argument supports only following data types: Object

My request look like:

let body = "<s:Envelope xmlns:s=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\" xmlns:saml=\"urn:oasis:names:tc:SAML:1.0:assertion\" xmlns:wsp=\"http://schemas.xmlsoap.org/ws/2004/09/policy\" xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\" xmlns:wsa=\"http://www.w3.org/2005/08/addressing\" xmlns:wssc=\"http://schemas.xmlsoap.org/ws/2005/02/sc\" xmlns:wst=\"http://schemas.xmlsoap.org/ws/2005/02/trust\">... etc ...<s:Header></wst:RequestSecurityToken></s:Body></s:Envelope>";

var postLoginObs = Observable.fromPromise(this.http2.post(this.apiUrl, body, headers));

Do you have any hint?

Thanks in advance.

**Comment by silkimen** [comment]
See [docu: setDataSerializer](https://github.com/silkimen/cordova-plugin-advanced-http#setdataserializer). You need to configure "utf8" before sending your request.
