### ISSUE TITLE
An error occurred while running cordova plugin add cordova-plugin-advanced-http

### ISSUE THREAD

**Issue by kevinhuron** [silkimen/cordova-plugin-advanced-http#16]
Hi,

I Got this error when I try to install the plugin in my ionic app 
> cordova plugin add cordova-plugin-advanced-http --save
✖ Running command - failed!
[ERROR] An error occurred while running cordova plugin add cordova-plugin-advanced-http --save (exit code 1):

        
        Error: Failed to fetch plugin cordova-plugin-advanced-http via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: npm: Command failed with exit code 1 Error output:
        cp: node_modules/umd-tough-cookie/lib/umd-tough-cookie.js: No such file or directory
        
        npm ERR! Darwin 16.7.0
        npm ERR! argv "/usr/local/bin/node" 
        "/Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/node_modules/.bin/npm" "run" "build"
        npm ERR! node v7.1.0
        npm ERR! npm  v2.15.12
        npm ERR! code ELIFECYCLE
        npm ERR! cordova-plugin-advanced-http@1.5.10 build: `cp node_modules/umd-tough-cookie/lib/umd-tough-cookie.js 
        www/umd-tough-cookie.js`
        npm ERR! Exit status 1
        npm ERR! 
        npm ERR! Failed at the cordova-plugin-advanced-http@1.5.10 build script 'cp 
        node_modules/umd-tough-cookie/lib/umd-tough-cookie.js www/umd-tough-cookie.js'.
        npm ERR! This is most likely a problem with the cordova-plugin-advanced-http package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     cp node_modules/umd-tough-cookie/lib/umd-tough-cookie.js www/umd-tough-cookie.js
        npm ERR! You can get information on how to open an issue for this project with:
        npm ERR!     npm bugs cordova-plugin-advanced-http
        npm ERR! Or if that isn't available, you can get their info via:
        npm ERR! 
        npm ERR!     npm owner ls cordova-plugin-advanced-http
        npm ERR! There is likely additional logging output above.
        
        npm ERR! Please include the following file with any support request:
        npm ERR!     
        /Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/node_modules/cordova-plugin-advanced-http/npm-debug.log
        
        npm ERR! addLocalDirectory Could not pack 
        /Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/node_modules/cordova-plugin-advanced-http to 
        /Users/kevinhuron/.npm/cordova-plugin-advanced-http/1.5.10/package.tgz
        npm ERR! addLocal Could not install 
        /Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/node_modules/cordova-plugin-advanced-http
        npm ERR! Darwin 16.7.0
        npm ERR! argv "/usr/local/bin/node" 
        "/Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/node_modules/.bin/npm" "install" 
        "cordova-plugin-advanced-http" "--save"
        npm ERR! node v7.1.0
        npm ERR! npm  v2.15.12
        npm ERR! code ELIFECYCLE
        npm ERR! cordova-plugin-advanced-http@1.5.10 prepublish: `npm run build`
        npm ERR! Exit status 1
        npm ERR! 
        npm ERR! Failed at the cordova-plugin-advanced-http@1.5.10 prepublish script 'npm run build'.
        npm ERR! This is most likely a problem with the cordova-plugin-advanced-http package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     npm run build
        npm ERR! You can get information on how to open an issue for this project with:
        npm ERR!     npm bugs cordova-plugin-advanced-http
        npm ERR! Or if that isn't available, you can get their info via:
        npm ERR! 
        npm ERR!     npm owner ls cordova-plugin-advanced-http
        npm ERR! There is likely additional logging output above.
        
        npm ERR! Please include the following file with any support request:
        npm ERR!     /Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/node_modules/npm-debug.log

Ionic Info : 
    cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

    global packages:

    cordova (Cordova CLI) : 7.0.1 

    local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.1.2 ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.1

    System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    Node              : v7.1.0
    npm               : 2.15.12 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

    Misc:

    backend : legacy

I tried **ionic cordova plugin add cordova-plugin-advanced-http** command : not working
and **cordova plugin add cordova-plugin-advanced-http** : not working

Thank you very much

**Comment by silkimen** [comment]
OK, the problem seems to be that cordova is trying to run the build script defined in `package.json`. But I don't know why it's doing that. You are using latest version ionic and cordova, right? Maybe there was a change in cordova? I'll need to check this.

**Comment by kesozjura** [comment]
I have the same problem.
@kevinhuron I workarounded it by temporary fork of this plugin. In my fork I added umd-tough-cookie.js to www folder and in cordova project replace repository to my temporary one.
@silkimen I am using latest ionic and cordova.

**Comment by silkimen** [comment]
@kevinhuron, @kesozjura: can you please check, if it's working for you with v1.6.0?

**Comment by kesozjura** [comment]
v1.6.0 works for me

**Comment by kevinhuron** [comment]
Hi !

I solved my problem ! my problem was occured by a deprecated components
I deleted it and I was been able to to download the plugin

**BUT**

I had an another error
When I launch my app my, in the console it say "**plugin not installed**" but when I try to reinstall it, it say it already install...

**Comment by silkimen** [comment]
OK, thanks. I'm closing this.

@kevinhuron, I think your problem is related to a known issue in ionic native. Check #8 and feel free to open a new issue, if it's another problem.
