### ISSUE TITLE
How could I debug in the network tab

### ISSUE THREAD

**Issue by Genarito** [silkimen/cordova-plugin-advanced-http#167]
I've started using this plugin as Angular HTTP doesn't work on iOS. But I notice that nothing appears on network tab in the [Developer Tools in Google Chrome](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) (chrome://inspect/#devices). Is there a way to debug the HTTP request made by the plugin from the Developer Tools?

![image](https://user-images.githubusercontent.com/18036578/49474878-91808500-f7f4-11e8-96b0-bda39bfac239.png)

**Comment by smallg** [comment]
if plugin working, can not catch xhr by develop tools.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!

**Comment by Genarito** [comment]
Hi! Thanks for the answer. I'm trying to debug with `debbuger;` but nothing useful as I can see :S.
Is there a way I could see the request info with breakpoints or It's the same that logging everything in console?

Thanks in advance and sorry about the inconvenients!
