### ISSUE TITLE
Support for ResponseType: Blob

### ISSUE THREAD

**Issue by abhijithaccion** [silkimen/cordova-plugin-advanced-http#171]
Hello silkimen 

i am using the plugin to request for a file which will be sent to me in blob data but the data get encoded to some other format which is not readable is there way i can get the data without the encoding and get the blob object

**Comment by ivarvh** [comment]
I have the same problem, in the native code, you can see that the body is being encoded as a string before it's passed through... So the binary data is lost. This plugin only seems to support text responses...

**Comment by click44** [comment]
I think I'm having the same issue. `Error: Response is not a Blob.` Where do you see "that the body is being encoded as a string before it's passed through" in the native code?

**Comment by ivarvh** [comment]
If you check the CordovaHttp.java, there is a method decodeBody which uses a CharsetDecoder to decode the body. This CharsetDecoder decodes the response bytes to unicode characters, so basically a string.

**Comment by silkimen** [comment]
Hi guys, @ivarvh is absolutely right. This plugin currently doesn't support Blobs. You can use `downloadFile()`, but it's not possible to receive Blobs via other methods. I'll mark this as a feature request.

**Comment by silkimen** [comment]
Implemented in v2.1.1. Closing this, feel free to open a new issue, if this won't solve your problem! 👍
