### ISSUE TITLE
iOS, crash with SSL pinned active

### ISSUE THREAD

**Issue by audio747** [silkimen/cordova-plugin-advanced-http#173]
Hi,

On iOS 12 ((iPhone X) when set SSL pinned:

`cordova.plugin.http.setSSLCertMode('pinned', function() {
  console.log('success!');
}, function() {
  console.log('error :(');
});`

App crash:

`2018-12-19 00:06:32.662435+0100 BP Test[5126:1552521] success!
2018-12-19 00:06:35.398857+0100 BP Test[5126:1552910] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(0x214917ea0 0x213ae9a40 0x21488f470 0x2147fe9d0 0x10273e5a4 0x10275d238 0x2153a682c 0x2152aea28 0x2152adefc 0x2153a8700 0x102d93824 0x102d94dc8 0x102d981c4 0x102d97604 0x102da61dc 0x102da6bc8 0x21453417c 0x214536cec)
libc++abi.dylib: terminating with uncaught exception of type NSException`

No problem in Android.

**Comment by firetrap** [comment]
Same here

**Comment by silkimen** [comment]
Hi guys, which version of this plugin is affected? Did you already try latest version?

**Comment by silkimen** [comment]
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍

**Comment by FranciscoVega2** [comment]
Hi im having this error when executing a post request the plugin is 
cordova-plugin-advanced-http : 3.3.1
cordova-plugin-file: 7.0.0
cordova: 11.1
cordova-ios 6.3.0

in android is working fine but in ios crashes
