### ISSUE TITLE
Can plugin be used for google http referrer restrictions?

### ISSUE THREAD

**Issue by rolinger** [silkimen/cordova-plugin-advanced-http#176]
I load google maps into my app via the `<script src='https://maps.googleapis.com/maps....>` api key method.  However the only way to restrict a google maps web services api key is using HTTP referrer (and in some cases server IP).  Can I use this plugin to create a valid HTTP referrer to match the google api restriction referrer?  And if so, how could I do it considering the its being loaded via the <script> tag in the head of the base index.html file?

**Comment by silkimen** [comment]
Hi rolinger, this is not possible with this plugin. Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.
