### ISSUE TITLE
How to send FormData in post request?

### ISSUE THREAD

**Issue by jsasmitha** [silkimen/cordova-plugin-advanced-http#178]
I want to send the form data in post request, but i'm not able to do. 
Below are my code:
let params = new FormData();
        params.append("country_code",country_code);
        params.append("mobile_no",mobile_no);
        params.append("country",country);
this.http.post(url, params,{}).then(data => {})

How to achieve the this?

**Comment by silkimen** [comment]
Please use following example code:

```js
const params = {
  country_code: country_code,
  mobile_no: mobile_no,
  country: country
};

this.http.setDataSerializer('urlencoded');

this.http.post(url, params, {}).then(data => {
 // do some stuff
});
```

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
