### ISSUE TITLE
No PATCH request support

### ISSUE THREAD

**Issue by paolostefan** [silkimen/cordova-plugin-advanced-http#18]
First of all, thanks for developing this handy plugin.

Would it be possible to add the support for the HTTP PATCH request method? It would be great and it would allow interacting with RESTful APIs more easily.

Thanks again.

**Comment by akhatri** [comment]
I have created a PR for this enhancement ticket (android version). Hope it's okay to integrate once reviewed.

**Comment by akhatri** [comment]
I've added patch methods in the http-request java file and it works on my local project now. PR #22

**Comment by silkimen** [comment]
will be integrated in v1.6.0

**Comment by DonalRafferty** [comment]
This is broken in Android using version 1.6.0, here's the error message:

com/synconset/cordovahttp/CordovaHttpPlugin.java:68: error: constructor CordovaHttpPatch in class CordovaHttpPatch cannot be applied to given types;

            CordovaHttpPatch patch = new CordovaHttpPatch(urlString, params, serializerName, headers, callbackContext);
                                     ^
  required: String,JSONObject,String,JSONObject,CallbackContext,int
  found: String,JSONObject,String,JSONObject,CallbackContext
  reason: actual and formal argument lists differ in length

**Comment by silkimen** [comment]
@DonalRafferty: yes sorry, my fault. I'll fix it, opened a new issue #23 for better tracking.
