### ISSUE TITLE
unusable response body for blob type requests

### ISSUE THREAD

**Issue by Edmu** [silkimen/cordova-plugin-advanced-http#182]
Request body for blob type response seems unusable:

Example code:

cordova.plugin.http.sendRequest(
    'https://via.placeholder.com/5x5/660000/?text=+',
    { method: 'get' },
    (resp) => {
        console.log('resp: ', resp);
    },
    (error) => {
        console.log('err: ', error);
    }
);

Example response:

data: "PNG
↵↵
IHDR·¡´¦PLTEf¼#'	pHYsÄÄ+IDATc`↵gíéIEND®B`"
headers: {date: "Fri, 01 Feb 2019 16:12:06 GMT", content-length: "107", server: "nginx/1.6.2", expires: "Fri, 08 Feb 2019 16:12:06 GMT", okhttp-selected-protocol: "http/1.1", …}
status: 200
url: "https://via.placeholder.com/5x5/660000/?text=+"

data cannot be used to convert it to TypedArray or Blob. I know there is method downloadFile but sometimes there is a need to fetch blob without saving it.

related #171

**Comment by silkimen** [comment]
Closing this, as it's related to #171.
