### ISSUE TITLE
POST the call send adding  \ in data

### ISSUE THREAD

**Issue by sridharan31** [silkimen/cordova-plugin-advanced-http#184]
While sending the encryption data. the our data is contain /. While receiving in server the every froward / the add the extra back slash(\) due to this we are getting the problem in decryption.
ex

`{"Metadata":"gIVZ3zqYCjTUMGgkUfr/pJc5N+X6X5VRJr/cXrgSeEBGjEgPmTU+3iNe+dqp/xRi2NyiYG4lxr7UXazKjmxElJypwnZGxYVB8bX0PzDccS4=","MetaInfo":"YPwpLWjttEqv3eA4itiBFZfqKsVVoQP7bFRfTxdH2QtQaqdHLPjpEa/I7SuLSGPsGm3nVL6zsy3PmOk1PfnNUvsyJUMUDrMm0gPX2sPIhnm4TMbfEm/Vk/Opm86bM304f8lsdQa8evG+DFNJTAy64f4ZJGRP4YZuC7rxArA3Y53c9kfiw9vn65kyFgXT4MrkIqZrrrRDp1OVsHOy75+N28cGOWja1Guvch0uKQzGrreCOpzyWSgojYpIpywIPM4z1iuuGC+/G/LJtZjsSVmHVFgNJoEcfDJ5FyYA28FtobLZKRzGBoTbVfVd9mi2YYmlYgb6E2ko57jBKmwiRZMUTw=="}`
 
`{"Metadata":"gIVZ3zqYCjTUMGgkUfr\/pJc5N+X6X5VRJr\/cXrgSeEBGjEgPmTU+3iNe+dqp\/xRi2NyiYG4lxr7UXazKjmxElJypwnZGxYVB8bX0PzDccS4=","MetaInfo":"YPwpLWjttEqv3eA4itiBFZfqKsVVoQP7bFRfTxdH2QtQaqdHLPjpEa\/I7SuLSGPsGm3nVL6zsy3PmOk1PfnNUvsyJUMUDrMm0gPX2sPIhnm4TMbfEm\/Vk\/Opm86bM304f8lsdQa8evG+DFNJTAy64f4ZJGRP4YZuC7rxArA3Y53c9kfiw9vn65kyFgXT4MrkIqZrrrRDp1OVsHOy75+N28cGOWja1Guvch0uKQzGrreCOpzyWSgojYpIpywIPM4z1iuuGC+\/G\/LJtZjsSVmHVFgNJoEcfDJ5FyYA28FtobLZKRzGBoTbVfVd9mi2YYmlYgb6E2ko57jBKmwiRZMUTw=="}`

**Comment by silkimen** [comment]
I've written a test case to check this ([see app-test-definitions.js#L502-L509](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/test/app-test-definitions.js#L502-L509)), but I can't reproduce your problem.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if you can provide more info!
