### ISSUE TITLE
calling setSSLCertMode with 'default' throws error (bug / Android) 

### ISSUE THREAD

**Issue by Edmu** [silkimen/cordova-plugin-advanced-http#187]
Plugin version: 2.0.5
Tested on 2 devices: Android 8.0.0 / Android 8.1.0 

calling:

cordova.plugin.http.setSSLCertMode('default', function() {
  console.log('success!');
}, function(err) {
  console.log('error', err);
});

executes error callback with error: _There was an error loading system's CA certificates_

logcat stacktrace:

02-28 16:14:24.602 24042 24170 W System.err: com.github.kevinsawicki.http.HttpRequest$HttpRequestException: java.io.IOException: You must add at least 1 certificate in order topin to certificates
02-28 16:14:24.602 24042 24170 W System.err:    at com.github.kevinsawicki.http.HttpRequest.setSSLCertMode(HttpRequest.java:316)
02-28 16:14:24.602 24042 24170 W System.err:    at com.synconset.cordovahttp.CordovaHttpPlugin.execute(CordovaHttpPlugin.java:113)
02-28 16:14:24.602 24042 24170 W System.err:    at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
02-28 16:14:24.602 24042 24170 W System.err:    at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
02-28 16:14:24.602 24042 24170 W System.err:    at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
02-28 16:14:24.603 24042 24170 W System.err:    at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
02-28 16:14:24.603 24042 24170 W System.err:    at android.os.MessageQueue.nativePollOnce(Native Method)
02-28 16:14:24.603 24042 24170 W System.err:    at android.os.MessageQueue.next(MessageQueue.java:325)
02-28 16:14:24.603 24042 24170 W System.err:    at android.os.Looper.loop(Looper.java:147)
02-28 16:14:24.603 24042 24170 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:65)
02-28 16:14:24.603 24042 24170 W System.err: Caused by: java.io.IOException: You must add at least 1 certificate in order to pin to certificates
02-28 16:14:24.603 24042 24170 W System.err:    at com.github.kevinsawicki.http.HttpRequest.getPinnedTrustManagers(HttpRequest.java:322)
02-28 16:14:24.603 24042 24170 W System.err:    at com.github.kevinsawicki.http.HttpRequest.setSSLCertMode(HttpRequest.java:307)
02-28 16:14:24.603 24042 24170 W System.err:    ... 9 more
02-28 16:14:24.604 24042 24170 W PluginManager: THREAD WARNING: exec() call to CordovaHttpPlugin.setSSLCertMode blocked the main thread for 217ms. Plugin should use CordovaInterface.getThreadPool().

**Comment by silkimen** [comment]
Yep, true story. I can confirm this and will fix it.
