### ISSUE TITLE
setSSLCertMode always returns OK

### ISSUE THREAD

**Issue by Aruna1122** [silkimen/cordova-plugin-advanced-http#188]

**Comment by silkimen** [comment]
Hi Aruna, so what's your problem if it's returning OK?

**Comment by Aruna1122** [comment]
Hi @silkimen,

The actual issue is it always returns true, whatever the .cer file that i use. i tried placing the certificate of some other website and it returned true. I then removed the certificate file, even then it returned true.

Im placing the .cer file in www/certificates folder. please guide me if in wrong.

**Comment by silkimen** [comment]
HI Aruna, actually this is not an issue. When you activate SSL pinning it's just doing some configuration  for future requests. The pinned certificate is used later on while validating the certificate chain when you send your request. So, the plugin can not know which domain you'll be using for your future requests.
But yeah, it would be nice to inform the user when no certificate can be found. I think this is a feature we've already implemented for Android but not iOS. Are you using iOS?

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
