### ISSUE TITLE
[iOS] getStatusCode does not map all SSL error codes

### ISSUE THREAD

**Issue by flexaddicted** [silkimen/cordova-plugin-advanced-http#189]
Hi,

I would like to know what is the rationale behind `getStatusCode` mapping.

```
- (NSNumber*)getStatusCode:(NSError*) error {
    switch ([error code]) {
        case -1001:
            // timeout
            return [NSNumber numberWithInt:1];
        case -1002:
            // unsupported URL
            return [NSNumber numberWithInt:2];
        case -1003:
            // server not found
            return [NSNumber numberWithInt:0];
        case -1009:
            // no connection
            return [NSNumber numberWithInt:3];
        case -1202:
            // untrusted SSL certificate
            return [NSNumber numberWithInt:-2];
        default:
            return [NSNumber numberWithInt:-1];
    }
}
```

`CFNetworkErrors` provides the following mapping:

```
// SSL errors
kCFURLErrorSecureConnectionFailed = -1200,
kCFURLErrorServerCertificateHasBadDate = -1201,
kCFURLErrorServerCertificateUntrusted = -1202,
kCFURLErrorServerCertificateHasUnknownRoot = -1203,
kCFURLErrorServerCertificateNotYetValid = -1204,
kCFURLErrorClientCertificateRejected = -1205,
kCFURLErrorClientCertificateRequired = -1206,
kCFURLErrorCannotLoadFromNetwork = -2000,
```

`getStatusCode` maps only `-1202`. Is there any reason for this?

I ask this question since I'm trying to implement Certificate Pinning in a Cordova application. I'm trying to simulate a man-in-the-middle-attack with Charles proxy but the error code that is returned back is `-1200`. Since this value has not been mapped, the status code received by the application always `-1`.

Waiting for a reply, I thank you in advance.

Lorenzo

P.S. Are you able to share your methodology in order to verify Certificate Pinning? Are you using Blurp Suite, Charles proxy, etc?

**Comment by silkimen** [comment]
Hi Lorenzo,

`getStatusCode` was meant to harmonize return codes of iOS and Android. Btw, they've changed in one of the last versions. Positive values are HTTP codes whereas negative values are exceptions (see [CordovaHttpPlugin.m#L95-L115](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/src/ios/CordovaHttpPlugin.m#L95-L115) and [CordovaHttpBase.java#L76-L92](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/src/android/com/silkimen/cordovahttp/CordovaHttpBase.java#L76-L92)). But you're right -1200 to -1204 need to be mapped to code -2 "SSL handshake failed". Thanks for reporting this!

On your second question, yes I'm using Charles proxy very regularly to inspect network data. And I've used mitmproxy several times, but I've never used Blurp suite. If you're doing some kind of Pen-Testing I'd be very interested in your results. 🙂👍

Cheers,
Sefa
