### ISSUE TITLE
Unexpected protocol error when reading to local xml

### ISSUE THREAD

**Issue by metinsevindik** [silkimen/cordova-plugin-advanced-http#190]
I am taking "Unexpected protocol" error when getting to local xml file
`    this.http.get("/assets/resources/settings.xml", {}, {}).then(data => {
      debugger;
    });`

but running http when get online http file. "https://raw.githubusercontent.com/......../settings.xml"

I am tried this url cases;
- "assets/resources/settings.xml"
- "file://assets/resources/settings.xml"
- "file:///assets/resources/settings.xml"
- "./../assets/resources/settings.xml"

Thanks

**Comment by silkimen** [comment]
Hi Metin, this plugin is not meant to be used for local resources. Please use XMLHttpRequest or cordova file plugin instead.

Almanya'dan Ankara'ya selamlar 😉

**Comment by metinsevindik** [comment]
Hi @silkimen thank you for your answer. I understand my problem. 
My problem resolved when add  `import { Http } from "@angular/http"` to my ionic project.

- Aleykümselam 😉 Başkent'ten Almanya'ya sevgiler.
