### ISSUE TITLE
Accessing local content on ios from remotely loaded https page using this plugin

### ISSUE THREAD

**Issue by guylando** [silkimen/cordova-plugin-advanced-http#191]
1. Does this plugin work with UIWebView and WKWebView?
2. UIWebView does not apply CORS, does it mean that ajax with this plugin doesn't have CORS restrictions?
3. Can this plugin be then used to load local files (cdvfile://localhost/bundle/www/file.js, file:///...)?

**Comment by silkimen** [comment]
1. Yes.
2. Yes, this plugin doesn't respect CORS restrictions.
3. No, this plugin is not meant to load local files.

**Comment by guylando** [comment]
@silkimen If this plugin does not apply CORS restrictions then why it can't be used to load local files? Isn't there some system handler which knows to return a local file for local urls? Or basically this functionality is just not implemented here?

**Comment by silkimen** [comment]
This plugin is meant for handling requests with "http" scheme. Local files are not using "http" scheme, but "file" or "cdvfile", etc. So this is out of scope of this plugin.

Closing this, feel free to open a new issue, if this won't solve your problem!
