### ISSUE TITLE
downloadFile fails with error: stream is reset HTTP_1_1_REQUIRED

### ISSUE THREAD

**Issue by graystormtrooper** [silkimen/cordova-plugin-advanced-http#192]
When trying to download a file using downloadFile with SSL cert mode set to 'nocheck'. I'm getting this error in the title.

My guess is it's trying to use HTTP/2 to download and the server didn't support it, but the library isn't retrying using HTTP 1.1.

**Comment by silkimen** [comment]
Do you have access on the backend? Please try to get some log files. Otherwise it'll be hard to find out the reason of your problem.

**Comment by silkimen** [comment]
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍
