### ISSUE TITLE
Double enconding on Android

### ISSUE THREAD

**Issue by Hanzofm** [silkimen/cordova-plugin-advanced-http#195]
Hi,

I am trying to download a file with a path like:

https://mydomain.com/file has spaces.pdf

I am obtaining this error:

`{"status":-1,"error":"There was an error with the given filePath"}`

If I do a previous 'encodeURI' the problem is that on Android the plugin do a double enconding for example:

`https://mydomain.com/file%20has%20spaces.pdf `

is transformed into 

`https://mydomain.com/file%2520has%2520spaces.pdf`

On iOS it works correctly if I previously encode the urls

My version of the plugin is 2.0.4 and the ionic wrapper version is 4.18.0 

What would be the problem?

Related issue:
https://github.com/silkimen/cordova-plugin-advanced-http/issues/96

**Comment by testanddeploy** [comment]
+1

**Comment by silkimen** [comment]
Please try v2.0.7, it should be fixed now. You'll need to encode the base URL yourself whereas query parameters (second argument) will be encoded automatically.

```js
cordova.plugin.http.downloadFile(urlNotEncodedAutomatically, paramsObjectEncodedAutomatically, headers, filePath, successHandler, errorHandler);
```

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!

**Comment by Hanzofm** [comment]
Solved on Android, now it fails on iOS :(
