### ISSUE TITLE
[v2.0.6] iOS: crashes on https downloadFile() call

### ISSUE THREAD

**Issue by olivermuc** [silkimen/cordova-plugin-advanced-http#197]
I realise that I may not be providing sufficient context and data, however I can positively state that up to v2.0.5 my app works flawless using several https:// `downloadFile()` calls.

After updating, the app immediately crashes on the first `downloadFile()` call.

Going back to v2.0.5 fixes this and it works as expected.

Here is as far as I can document the issue, an xcode debug screenshot after crashing:
![image](https://user-images.githubusercontent.com/10549895/55275840-77f7d180-52ec-11e9-97a4-a7596378cd29.png)

**Comment by silkimen** [comment]
Hi Oliver,
I've tried to reproduce your problem by writing a test case (see [app-test-definitions.js#L571-L594](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/test/app-test-definitions.js#L571-L594), but everything is working just fine. Did you test on a device or simulator? Which version of iOS do you use?

**Comment by olivermuc** [comment]
@silkimen phone is running on iOS 12.2; tested with both though, device & simulator.

Will try your example above and will report back.
There is also a chance that it may be related to my code assembling the http header info.

However, the phenomenon that all previous versions leading up to 2.0.6 work and just 2.0.6 causes the above errors.

Going back and forth between the versions reproduces the same results.

**Comment by olivermuc** [comment]
**A few more observations/feedback:**

- **v2.0.7** has the same issues (for me) as v2.0.6 does, the app crashes
- My code makes several `downloadFile()` requests rapidly one after the other
   - Before each, I apply several `setHeader()` commands
- I experimented with setting various breakpoints and delays and interestingly enough, setting a breakpoint before the first `downloadFile()` call it completes **that one** - but then "**skips**" the rest, like those additional calls were never made, but it doesn't crash 
  - Again if I don't set any breakpoints, the app crashes

**My code:**

Setting Headers (get set before each request:
```
setSSLCertMode('nocheck');
setRequestTimeout(30000);
setHeader('*', 'Content-Type', contentType);
setHeader(baseURL, 'Authorization', authorization);
```

Download Call (note: the call is wrapped in an _Observable_ structure, hence `_obs*`):
```
downloadFile(url, {}, {}, `${local_file_path}`)
  .then(fileEntry => {
    if (_.size(fileEntry) > 0) {
      _obs.next(fileEntry);
    } else {
      _obs.next(null);
    }
    _obs.complete();
  })
  .catch((error: any) => {
    _obs.next(null);
    _obs.complete();
  });
```

I'm at a loss what else to test, but all of the issues are not happening with v2.0.5 and lower.

**Comment by olivermuc** [comment]
Follow up; I cloned your repo and reverted this commit:
https://github.com/silkimen/cordova-plugin-advanced-http/commit/a8e3637f2728809377286aa00d85321f291d2f19

With the above everything works as before!

Can you please revert that PR?

Based on the owners own comment:
> Persist the AFHTTPSessionManager instance for the life of the plugin to allow reusing the underlying sockets, for example, with "Connection: keep-alive" headers. Hopefully, this addresses the issue #115 .

...it looks like this introduced more issues than it "fixed".

**Comment by silkimen** [comment]
Ok, I see. Seems to be a race condition issue. I'll try to write a test case for this special case to find a working fix. But you're right, for the first instance, I'll need to revert this commit.

**Comment by chrisjdev** [comment]
I finally reproduced this issue by changing my code to use downloadFile(). I'm not sure what it's for, but there's a `manager.responseSerializer = [SM_AFHTTPResponseSerializer serializer];` line in downloadFile(). I have no other calls to set the response serializer, and for whatever reason, that serializer returns an NSData* instead of a NSString*. When an uploadFile() call runs after a call to downloadFile(), it throws an exception because it can't serialize NSData to JSON. It also appears to be opening a new socket for downloadFile(). I'm still looking into why that might be happening, but one workaround might be to remove the line that sets the responseSerializer, or add a new member variable for a SM_AFHTTPSessionManager that's used only for downloadFile().
