### ISSUE TITLE
Cookie handler does not support 'expires'  on split cookie function

### ISSUE THREAD

**Issue by mburger81** [silkimen/cordova-plugin-advanced-http#2]
I found an error on the cookie handler!
in cookie-handler.js on the splitCookieString function you should check also wor 'Expires=' with upper "E", some service use this.

so something like that
if (cookieParts[i].substr(-11, 8) === 'expires=' || 'Expires=') {

Sorry for that, but I'm not good in making a pull request and it takes a lot of time for me, do you think you can do this?

**Comment by mburger81** [comment]
Hi @silkimen we test the plugin only on android emulator for now using a Nexus 5 KitKat device. We didn't test it on ios or devices. 
But I'm pretty sure it has the the same error. 

The cookie handler on splitfunction supports only lowercase. But the 3rd part server returns Expires part for the cookie with upper E. So I don't think the device type is changing the behavior 
I think you should check wor case insensitive or?

**Comment by silkimen** [comment]
Yes, basically you are right. But I think we should normalize all header keys e.g. having them all in lower-case. So even if the server responds with "Expires", "EXPIRES" or "expires", we should access it with key "expires". I thought we are already doing that, but seems to be broken somehow. That's the reason I'm asking for the device on which this problem occurs.

But I'll implement a workaround for now to fix your problem.

**Comment by mburger81** [comment]
Hi thx, for the fast release this is working great!!!

You are right it is better testing for lower case, the reason I didn't do this in my PR is:
On testing for Expires= || expires= || EXPIRES= you have less probabilty to have some problems with for example a token which could be 'eXpireS='
But I think this should be not often a problem ;)
