### ISSUE TITLE
Exception calling native with command :: CordovaHttpPlugin :: post ::exception=TypeError: helpers.getTypeOf is not a function

### ISSUE THREAD

**Issue by abgrano** [silkimen/cordova-plugin-advanced-http#201]
When i use previous `<plugin name="cordova-plugin-advanced-http" spec="2.0.2" />` it work perfectly.

Now install new `<plugin name="cordova-plugin-advanced-http" spec="2.0.7" />` the console appear "Exception calling native with command :: CordovaHttpPlugin :: post ::exception=TypeError: helpers.getTypeOf is not a function"

**Comment by abgrano** [comment]
version 2.0.6 ok for me. version 2.0.7 still this issue "Exception calling native with command :: CordovaHttpPlugin :: post ::exception=TypeError: helpers.getTypeOf is not a function"

**Comment by silkimen** [comment]
Hi Rano, can you please add some example code? Which OS and which OS version is affected?

**Comment by abgrano** [comment]
Hi @silkimen . i'm using win10, Browser Chrome, Ionic project.

` async login(email: any, pass: any) {
    const loading = await this.loadingController.create({
      message: 'Loading ...'
    });
    await loading.present();
    try {
      const sendData = {
        'email': email,
        'password': pass,
        'remember_me': 0
      };
      this.http.setHeader('*', 'Content-Type', 'application/json');
      this.http.setHeader('*', 'X-Requested-With', 'XMLHttpRequest');
      const dataReturn = await this.http.post('http://localhost/project1/auth/login', sendData, {});
        this.myData = JSON.parse(dataReturn.data);
        console.log(this.myData);
        loading.dismiss();
    } catch (error) {
      loading.dismiss();
      console.log(error);
    }
  }`

Version affected **2.0.7**. Version **2.0.6** work **perfectly** for me using this code.

**Comment by abgrano** [comment]
![Issue](http://dbkuapps.ml/cordova.png)

**Comment by silkimen** [comment]
Ok thanks Rano, I can confirm it's a bug.

**Comment by abgrano** [comment]
> Ok thanks Rano, I can confirm it's a bug.

Alright. Thanks.
