### ISSUE TITLE
Observables response support

### ISSUE THREAD

**Issue by beckmx** [silkimen/cordova-plugin-advanced-http#202]
Hello, I was wondering if the plugin support observables or all responses are based on promises?

**Comment by silkimen** [comment]
Hi beckmx, this plugins doesn't support Promises and Observables. It's a plain old callback API. But you can use ionic-native wrapper if you want to have Promises. And it's up to you if you want to wrap them into observables.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
