### ISSUE TITLE
Encoded url fails on new version [iOS version]

### ISSUE THREAD

**Issue by Hanzofm** [silkimen/cordova-plugin-advanced-http#203]
Come from https://github.com/silkimen/cordova-plugin-advanced-http/issues/195

On Android OS works fine now but on iOS returns and error when I try to download this url:

 `https://padelfederacion.es/Paginas/Docs/Bases Licitacion 2019 05.pdf `

The returned error to this call:

`this.http.downloadFile(encodedURI(url), {}, {}, cordova.file.dataDirectory + name)`

Is this:

`{"status":406,"headers":{"server":"Microsoft-IIS/8.5","content-type":"text/html;  charset=utf-8","x-powered-by":"ASP.NET","x-powered-by-plesk":"PleskWin","date":"Tue, 09 Apr 2019 09:31:39  GMT","content-length":"5173","cache-control":"private"},"url":"https://padelfederacion.es/Paginas/Docs/Bases%20Licitacion%202019%2005.pdf","error":"There was an error downloading the file"} `

This error is returned on whatever uri is passed (contains utf characters, spaces or nothing)

What would be wrong?

**Comment by Hanzofm** [comment]
It seems to be a problem with the 'Accept' `Header`. If I pass as a parameter this:

`this.http.downloadFile(encodedURI(url), {}, {Accept: '*/*'}, cordova.file.dataDirectory + name)`

or

`this.http.downloadFile(encodedURI(url), {}, {Accept: ''}, cordova.file.dataDirectory + name)`

It works fine on iOS and Android OS

**Comment by silkimen** [comment]
Hi Hanzofm, I don't think this a problem related to the this plugin. I have tested it on my device with v2.0.7 and your URL for the pdf file. It's working without problems. I don't need to set the 'Accept' header manually. Maybe there was a problem with the server?

**Comment by Hanzofm** [comment]
Hi @silkimen ,

With this call:

`this.http.downloadFile(encodedURI('https://padelfederacion.es/Paginas/Docs/Bases Licitacion 2019 05.pdf'), {}, {}, cordova.file.dataDirectory + name)`

The returned url of encodeURI call 

`encodeURI('https://padelfederacion.es/Paginas/Docs/Bases Licitacion 2019 05.pdf')`

is:

`https://padelfederacion.es/Paginas/Docs/Bases%20Licitacion%202019%2005.pdf` 


-This code on the devices iPhone 6S(ios 12.2) and iPhone 6S(ios 12.1.4) with Ionic wrapper 4.18.0 and 2.0.4 of the library **works correctly**

-This code on the devices iPhone 6S(ios 12.2) and iPhone 6S(ios 12.1.4) with Ionic wrapper 4.18.0 and 2.0.7 of the library **works bad as explained**

-This code on the devices iPhone 6S(ios 12.2) and iPhone 6S(ios 12.1.4) with Ionic wrapper 4.18.0 and 2.0.7 of the library **with pdf of other servers works correctly**

All explained cases are tested on environments with --livereload param and without it.

In my opinion is not a server problem because 2.0.4 works correctly.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
