### ISSUE TITLE
Getting Error Symbol not found while trying to create a build.

### ISSUE THREAD

**Issue by welcomedk** [silkimen/cordova-plugin-advanced-http#204]
The following errors have occurred:
• In Android on 2019-04-09 at 18:48:39 - Error compiling Cordova plugin: com/silkimen/cordovahttp/CordovaHttpPlugin.java:153: error: cannot find symbol.

**Comment by ath0mas** [comment]
this issue is not really well named, but
=> build fails with version 2.0.8:
```:compileArmv7DebugJavaWithJavac FAILED

BUILD FAILED

Total time: 14.729 secs

    code: 1

Stack:
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\build\advhttp\platforms\android\src\com\silkimen\cordovahttp\CordovaHttpPlugin.java:153: error: cannot find symbol
        this.cordova.getContext(), this.tlsConfiguration, callbackContext);
                    ^
  symbol:   method getContext()
  location: variable cordova of type CordovaInterface
```

**Comment by Mawster** [comment]
Hi guyz,

we have the same problem. Looked into the code and found the problem - instead of 
`  private boolean setClientAuthMode(final JSONArray args, final CallbackContext callbackContext) throws JSONException {
    CordovaClientAuth runnable = new CordovaClientAuth(args.getString(0), args.getString(1), this.cordova.getActivity(),
        this.cordova.getContext(), this.tlsConfiguration, callbackContext);

    cordova.getThreadPool().execute(runnable);

    return true;
  }`

the line 
`new CordovaClientAuth(args.getString(0), args.getString(1), this.cordova.getActivity(),
        this.cordova.getContext(), this.tlsConfiguration, callbackContext);`

should be
`new CordovaClientAuth(args.getString(0), args.getString(1), this.cordova.getActivity(),
        this.webView.getContext(), this.tlsConfiguration, callbackContext);`

**Comment by ath0mas** [comment]
@Mawster I would prefer `this.cordova.getActivity().getApplicationContext()` instead of `this.webView.getContext()`
given the TODO in [CordovaWebView.java#L138](https://github.com/apache/cordova-android/blob/b177f848254f5d479d6a9b744b15211632ab1dcf/framework/src/org/apache/cordova/CordovaWebView.java#L138)
```
    // TODO: Work on deleting these by removing refs from plugins.
    Context getContext();
```

**Comment by tverilytt** [comment]
I got the same error to for 2.0.8, 2.0.6 works well, sticking to that for the moment :-)

**Comment by Mawster** [comment]
> @Mawster I would prefer `this.cordova.getActivity().getApplicationContext()` instead of `this.webView.getContext()`
> given the TODO in [CordovaWebView.java#L138](https://github.com/apache/cordova-android/blob/b177f848254f5d479d6a9b744b15211632ab1dcf/framework/src/org/apache/cordova/CordovaWebView.java#L138)
> 
> ```
>     // TODO: Work on deleting these by removing refs from plugins.
>     Context getContext();
> ```

@ath0mas you are right - is the better !

**Comment by silkimen** [comment]
Hi guys, thanks for analysing this problem. I'm using cordova-android 7+. That's the reason I didn't realize this problem on my machine (see [CordovaInterface.java#L66](https://github.com/apache/cordova-android/blob/rel/7.0.0/framework/src/org/apache/cordova/CordovaInterface.java#L66)). I'll change it to `this.cordova.getActivity().getApplicationContext()`.

**Comment by ath0mas** [comment]
Thanks @silkimen for the fix
indeed getContext() in CordovaInterface.java exists starting from cordova-android@6.4

**Comment by tverilytt** [comment]
thanks @ath0mas - I am using cordova-android@6.3, so that explains it. Probably time to upgrade ;-)

**Comment by Lyfei** [comment]
> Hi guys, thanks for analysing this problem. I'm using cordova-android 7+. That's the reason I didn't realize this problem on my machine (see [CordovaInterface.java#L66](https://github.com/apache/cordova-android/blob/rel/7.0.0/framework/src/org/apache/cordova/CordovaInterface.java#L66)). I'll change it to `this.cordova.getActivity().getApplicationContext()`.

Line 268 also needs to be replaced in the latest version.
