### ISSUE TITLE
async/await/promise alternative

### ISSUE THREAD

**Issue by willmero** [silkimen/cordova-plugin-advanced-http#206]
Hello! 

I seem to be running into a bit of an architectural issue here, where I am attempting to build an API adapter layer into my cordova based application. One of the requirements of this is to be able to perform something like the following:

`let newItem = await hitServer('POST', '/api/newItem', itemData)`

Where `hitServer` will return back the response object from the server on a successful response. 

What would be the method of going this sort of structure with this plugin in Cordova? Currently trying `await cordova.plugin.http.sendRequest...` does not work. 

Cheers

**Comment by silkimen** [comment]
Hi Will, you can't await a function which isn't returning a Promise. Check #202 on how to get a Promise.
