### ISSUE TITLE
Problem with Digest authentication: missing WWW-Authenticate response header

### ISSUE THREAD

**Issue by falquinho** [silkimen/cordova-plugin-advanced-http#209]
Hello all.
As the title says i'm trying to implement digest authentication in an app, but upon error 401 theres's no WWW-Authenticate header in the response. Actually there's no headers at all.
I do not have control over the server (it's an IP camera), but it does expose the header,
since accessing the link in both browser and postman shows it.
I have to use the Native Http since Angular's HttpClient is blocked by CORS.
Can someone help? Is this a bug? Or i am missing something? I've looked in the code but i was not able to understand how response headers are received, so I'm unable to propose a solution or PR.
Thank you for the help and work on this plugin.

**Comment by silkimen** [comment]
Hi Lucas, which OS is affected? Is it Android? If yes, it's probably related to #221. Please try fixed version 2.0.11.

**Comment by falquinho** [comment]
Hey, thanks for answering. 
It was android indeed, sorry i failed to provide this info. 
It does looks like it will fix my problem. Thanks a lot for this, it will give a huge boost to the project
i'm working on. But unfortunatelly i can't test soon, i'll have to come back later do write a follow up.
Thanks for it. Later.

**Comment by falquinho** [comment]
It IS working now. Thank you so much (and sorry for the late response.)

**Comment by rluckez** [comment]
> Hello all.
> As the title says i'm trying to implement digest authentication in an app, but upon error 401 theres's no WWW-Authenticate header in the response. Actually there's no headers at all.
> I do not have control over the server (it's an IP camera), but it does expose the header,
> since accessing the link in both browser and postman shows it.
> I have to use the Native Http since Angular's HttpClient is blocked by CORS.
> Can someone help? Is this a bug? Or i am missing something? I've looked in the code but i was not able to understand how response headers are received, so I'm unable to propose a solution or PR.
> Thank you for the help and work on this plugin.

@falquinho Eu vi que você é brasileiro, eu estou fazendo o mesmo que você, tentando fazer um digest com um projeto Angular numa câmera IP, você consegue me dizer como você fez para montar os dados de autorização do digest? O seu projeto era em cima de alguma marca de câmera específica? No meu caso estou tentando fazer numa Intelbras.

Obrigado!
