### ISSUE TITLE
ssl pinning with ionic v 4.1.0 returns "there was an error setting up ssl pinning"

### ISSUE THREAD

**Issue by KamayaniT** [silkimen/cordova-plugin-advanced-http#210]
Hi,
I am using Ionic Framework v4.1.0
Advanced Native Http Plugin Version : 2.0.9 
I am trying to enable ssl pinning for my project. 

I tried to follow all the steps that were mentioned through the documentation. 
I have tried placing my certificate (.der encoded) in  platforms/android folder and also in "src/assets/certificates" .  
I still keep getting error "there was an error setting up ssl pinning" . 
I cannot find any other documentation or way of solving this. 
Here is the code of how I have implemented this :

import {HTTP} from '@ionic-native/http/ngx';

export class AuthService {
public username: any;
  constructor(public httpnative :HTTP){
       
this.httpnative.setSSLCertMode('pinned').then(res => console.log("success"+res)).catch(err =>alert("SSL : "+err));
  }

}

**Comment by joseconstela** [comment]
@KamayaniT did you manage to solve this? I'm having the same issue.

**Comment by KamayaniT** [comment]
@joseconstela  Yes. It got solved after i removed and installed android platform again.
Also, I have kept my .cer file in src/assets folder directly.

**Comment by ashenwgt** [comment]
Hi @KamayaniT, did you use Capacitor too? 

I have been using Capacitor and still could not integrate SSL Pinning in my Ionic project (https://github.com/ashenwgt/ionic-capacitor-ssl-pinning). What are the steps you followed? Is your code publicly-available?
