### ISSUE TITLE
URI is not absolute

### ISSUE THREAD

**Issue by januarsy** [silkimen/cordova-plugin-advanced-http#211]
cordova.plugin.http.downloadFile("https://smedia2.intoday.in/btmt/images/stories/whatsapp_660_031419103558.jpg", { id: '12', message: 'test'}, { Authorization: 'OAuth2: token' }, '/data/data/myApps/whatsapp_660_031419103558.jpg', function(entry) { alert("SCS : "+entry.name);
}, function(response) { alert("ERR : "+response.error); });

Error Message : URI is not absolute

**Comment by darrensapalo** [comment]
I am also encountering this problem. What did you do to diagnose or fix it?

**Comment by sta55en** [comment]
Seeing this too, with a valid URI.

**Comment by ewwwgiddings** [comment]
Also seeing this. Does anyone have a solution? @sta55en @darrensapalo @januarsy

**Comment by ewwwgiddings** [comment]
For anyone reading this, my issue was I thought the error was occurring as a result of the location of the file to download (https://...) but it was an error with the path of the location I was downloading to (file:///...) Hope this helps someone.
