### ISSUE TITLE
POST json receiving NotEncodableValueException

### ISSUE THREAD

**Issue by Boby** [silkimen/cordova-plugin-advanced-http#212]
Hi, 

I am using : 

this.httpClient.post('http://test.com/api', {
"name": { "value": "test03" },
"mail": { "value": "test03@gmail.com" },
"pass": { "value": "123"}
},
{'Content-Type': 'application/json'}).catch(res=>{
console.log(res);
});

on my symfony serializer its throwing syntax error but when I am using postman, POST method its working fine

it throws out error : 

Symfony\\Component\\Serializer\\Exception\\NotEncodableValueException: Syntax error in
\/vendor\/symfony\/serializer\/Encoder\/JsonEncoder.php(45): Symfony\\Component\\Serializer\\Encoder\\JsonDecode-\u003Edecode(\u0027name=%5Bobject%...\u0027, \u0027json\u0027, Array)

any issue?

**Comment by silkimen** [comment]
Hi Boby, you need to configure the serializer to use `json` instead of default value`urlencoded`. This info was missing in the readme, I've added it now.

your code should be:
```js
this.httpClient.setDataSerializer('json');
this.httpClient.post(
  'http://test.com/api',
  {
    "name": { "value": "test03" },
    "mail": { "value": "test03@gmail.com" },
    "pass": { "value": "123"}
  },
  {
    'Content-Type': 'application/json'
  }
).catch(res => console.log(res));
```

**Comment by Boby** [comment]
thank you for the reply! let me give it a try this week and let you know @silkimen :)

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
