### ISSUE TITLE
Installation Failed 

### ISSUE THREAD

**Issue by pangshangggg** [silkimen/cordova-plugin-advanced-http#213]
npm: Command failed with exit code 1 Error output:
npm ERR! code ECONNRESET
npm ERR! network tunneling socket could not be established, statusCode=400
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2019-05-14T10_15_56_808Z-debug.log

**Comment by vosecek** [comment]
Post command you run.

**Comment by silkimen** [comment]
This problem is not related to this plugin. It's caused by a network issue or npm misconfiguration.
