### ISSUE TITLE
help: how to set responseType?

### ISSUE THREAD

**Issue by sahyun1** [silkimen/cordova-plugin-advanced-http#216]
In angular http, I can specify responsetype like
```
    this._httpClient.get(url, {headers: headers, responseType: 'arraybuffer'})
```

how can I do something similar to this? I tried to convert the response data to arraybuffer but the result is not the same
```
new Response(response.data).arrayBuffer()
```

many thanks!

**Comment by silkimen** [comment]
This relates to #171, it's not supported, atm.
