### ISSUE TITLE
ios status -1

### ISSUE THREAD

**Issue by passwhl** [silkimen/cordova-plugin-advanced-http#217]
>
![QQ截图20190522180805](https://user-images.githubusercontent.com/12857123/58166584-b8f0de80-7cbc-11e9-9c9a-98f775a0478a.png)
version: 2.0.9

**Comment by passwhl** [comment]
@silkimen not working on iOS (but perfectly working on Android)

**Comment by silkimen** [comment]
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍
