### ISSUE TITLE
Headers are used as Params on browser platform

### ISSUE THREAD

**Issue by adamcmoore** [silkimen/cordova-plugin-advanced-http#218]
Making a `get` request with headers results in the headers being added as query string parameters. I'm using version 2.0.9, through `@ionic-native/http@5.6`. `post` and `put` work as expected. My code which is resulting in this behaviour:

```javascript
var options = {
  method: 'get',
  headers: {
    'X-test': 'test value',
  }
};
this.http.sendRequest(url, options);
```

From what I can see, the method `sendRequest` in `www/public-interface.js` calls the `get` method in the `cordova-http-plugin.js` with the following:

```javascript
exec(onSuccess, onFail, 'CordovaHttpPlugin', options.method, [url, headers, options.timeout, options.followRedirect])
```

The `sendRequest` method in `src/browser/cordova-http-plugin.js` is passed the ` [url, headers, options.timeout, options.followRedirect]` array as its `opts` parameter, which I think is then handled incorrectly. When `withData` is `false`, the `headers` are pulled from the array with `opts[2]`. but this index returns the timeout. Should this not be `opts[1]`?

Am I doing something dumb here? Or is there a compatibility issue? Whatever it is, I'm tearing my hair out, and would appreciate any feedback!

**Comment by vosecek** [comment]
Same for me (now testing in browser with ionic cordova run browser --live-reload)

**Comment by vosecek** [comment]
Last version without serious issue is 2.0.6, 2.0.7 has this issue: https://github.com/silkimen/cordova-plugin-advanced-http/issues/201.

Version 2.0.8 has same header issue as 2.0.9.
