### ISSUE TITLE
Unable to send Images using FormData

### ISSUE THREAD

**Issue by swanand6300** [silkimen/cordova-plugin-advanced-http#219]
Hi Guys,

I am trying to send images using form data but every time it gives me below error.

`Error: advanced-http: "data" argument supports only following data types: Array, Object
    at Object.getProcessedData (helpers.js:281)
    at Object.sendRequest (public-interface.js:154)
    at Object.post (public-interface.js:167)
    at callCordovaPlugin (vendor.js:89658)
    at vendor.js:89473
    at vendor.js:89431
    at new ZoneAwarePromise (polyfills.js:3268)
    at tryNativePromise (vendor.js:89430)
    at getPromise (vendor.js:89451)
    at wrapPromise `(vendor.js:89456)`

Here is my code:
`this.file.resolveLocalFilesystemUrl(localImageURL).then((entry: any) => {
      entry.file((file) => {
        const fileReader = new FileReader();
        fileReader.readAsArrayBuffer(file);
        fileReader.onloadend = ev => {
          this.TestformData = new FormData();
          let imgBlob = new Blob([fileReader.result], { type: file.type });
          this.TestformData.append('files', imgBlob, file.name);
        }
      })
    }).then((res) => {
      this.http.service('apiURL?broadcastText=Multiple uploads', this.TestformData).subscribe((res) => { console.log(res) }, (err) => { console.log(err) })
    }, (err => {
      console.log(err)
    }))`

Any help is appreciated.

**Comment by silkimen** [comment]
Relates to #101 and therefore it's not supported.
