### ISSUE TITLE
SyntaxError: Unexpected token d in JSON at position 1

### ISSUE THREAD

**Issue by pedelon** [silkimen/cordova-plugin-advanced-http#220]
I'm using the plugin from Ionic 4, but for some reason all the calls by Post method without problems but then the calls by method GET gives this error. I have tried everything, at some point creating a new project I answered correctly and after compiling the error returned. I do not know what is due. you can help me
On Android
`
let headers =  {'rest-auth': 'asdasdadasndajs' };
let url = 'https://myserver/rest/resumen';

this.http.get( url, {}, headers )then( resp => {
  console.log('resp')
        }).catch( error =>{
          console.log('error');
        });
`

**Comment by jpike88** [comment]
set a breakpoint in the code, that should be easy to diagnose further. your issue doesn't provide enough information to be useful

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
