### ISSUE TITLE
Android: headers not set on HTTP errors

### ISSUE THREAD

**Issue by Enrico204** [silkimen/cordova-plugin-advanced-http#221]
When the remote endpoint returns an HTTP error, `headers` field is not set (at least on Android). The relevant code is at: https://github.com/Enrico204/cordova-plugin-advanced-http/blob/298c0314339d8c32fd80f92815d4923e0779c015/src/android/com/silkimen/cordovahttp/CordovaHttpResponse.java#L59

I think that headers should be returned in case of an error, as they might contain some useful information (such as rate limit infos, etc). Also, if you look at the documentation in home page, under "failing" it seems that it was implemented (or at least there was an intent to implement).

**Comment by silkimen** [comment]
Hi Enrico, you're right, this is a bug. It was implemented before, but seems I've messed up during refactoring. I'll fix this, thanks!

**Comment by Enrico204** [comment]
Thanks! I just tried the version `2.0.11` and it works as expected :-)
