### ISSUE TITLE
Exception when using POST

### ISSUE THREAD

**Issue by russcarver** [silkimen/cordova-plugin-advanced-http#226]
I'm using Ionic (4) and because of this, I have to use their native HTTP wrapper to access your plugin (since they overwrite the `cordova` global variable). So I'm not sure if it's an issue with the plugin or their wrapper. I have opened an issue with them that you can see here (https://github.com/ionic-team/ionic-native/issues/3060). Basically, I'm getting the following exception when sending a POST:

```
06-19 10:22:25.994  2804  3218 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getHttpUrlChecked(Ljava/lang/String;)Lokhttp3/HttpUrl; in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/app/com.ati.playermax-7J2_lAuR7wF-GmEJjCeAYw==/base.apk!classes4.dex)
06-19 10:22:25.994  2804  3218 E AndroidRuntime: 	at com.silkimen.cordovahttp.CordovaHttpBase.sendBody(CordovaHttpBase.java:153)
06-19 10:22:25.994  2804  3218 E AndroidRuntime: 	at com.silkimen.cordovahttp.CordovaHttpBase.run(CordovaHttpBase.java:77)
06-19 10:22:25.997  1369  2009 W ActivityManager: crash
```

I'm using version 2.1.1 of the plugin and version 5.8.0 of the wrapper.

**Comment by russcarver** [comment]
It turns out this issue was a conflict with another plugin (geofence) using `com.squareup.okhttp3:okhttp-urlconnection:3.11.0`.  I added the following variable to my `config.xml` to solve the issue.

```
<plugin name="cordova-plugin-advanced-http" spec="2.1.1">
        <variable name="OKHTTP_VERSION" value="3.11.0" />
    </plugin>
```

**Comment by Xstoudi** [comment]
How did you find the plugin that was a conflict with cordova-plugin-avanced-http ? My bigger problem now is that I have the same error as you had, but I only have those plugin installed :
```
cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Comment by russcarver** [comment]
Through searches I found that OkHttp conflicts may be the source of that error. I searched through the other plugins I used to find references to OkHttp. You can also look at on of the gradle build files in the android platform to see what version is used. There is also another command to list your dependencies: `gradlew :YourApp:dependencies` as can be seen at https://support.zendesk.com/hc/en-us/community/posts/360029407374-App-crashing-after-receiving-message-OkHTTP-setWriteTimeout-method-not-found
