### ISSUE TITLE
Http POST with x-www-form-urlencoded content type FAILS every time

### ISSUE THREAD

**Issue by sambowenhughes** [silkimen/cordova-plugin-advanced-http#227]
Hey Guys,

Im currently using the **cordova-plugin-advanced-http** to make a **x-www-form-urlencoded** POST to Microsoft B2C Auth.

Here is my code:
```
var headers = {
        "content-type": "application/x-www-form-urlencoded",
        'Access-Control-Allow-Origin':'*'
      }

var body = new FormData();
        body.append("Example Param", "Example Value");
        body.append("Example Param", "Example Value");

var url = "example.url";

this.nativeHttp.post(url, body, headers)
        .then(data => {
          console.log("DATA:"+JSON.stringify(data))

        })
        .catch(error => {
          console.log("ERROR:"+JSON.stringify(error))
        });
```
Whenever I make a request passing the **FormData()** object through I get the following ERROR:

**[INFO:CONSOLE(222)] "ERROR:{}", source: http://localhost/pages-home-home-module.js (222)**

Please could you help with this. Or even explain the best way to go about making **www-form-urlencoded** requests using the plugin.

Sam.

**Comment by silkimen** [comment]
Hi sambowenhughes, this plugin doesn't support `FormData` objects. But you can use a plain JS object for sending form data after having configured the data serializer correctly (see also [cordova-plugin-advanced-http#post](https://github.com/silkimen/cordova-plugin-advanced-http#post)).

e.g.
```js
const body = {
  'Example Param': 'Example Value',
  'Example Param2': 'Example Value2',
};

this.nativeHttp.post(url, body, headers)
  .then(data => {
    console.log('DATA:', JSON.stringify(data))
  })
  .catch(error => {
    console.log('ERROR:', JSON.stringify(error))
  });
```

Please use StackOverflow for this kind of questions next time: https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
