### ISSUE TITLE
Any response cache control?

### ISSUE THREAD

**Issue by cabelotaina** [silkimen/cordova-plugin-advanced-http#228]
Hi all,

I need use response cache in our project. The plugin cache the response or have some settings to configure this?

Looking on source code I can't see anything similar with:

https://github.com/kevinsawicki/http-request/blob/master/README.md#using-entity-tags-for-caching
https://developer.android.com/reference/android/net/http/HttpResponseCache

tks

**Comment by silkimen** [comment]
Hi Maurilio, you're right this plugin doesn't support any kind of caching control mechanism. It's up to you to build your own custom wrapper for handling ETags and resolving from custom cache.

**Comment by cabelotaina** [comment]
Oh okay, we are using our own cache system. And now it is working very well on iOS. The next is try with android.

Thank you for your response.
