### ISSUE TITLE
"plugin not installed" error in SSL pinning using ionic-native http

### ISSUE THREAD

**Issue by jintzz** [silkimen/cordova-plugin-advanced-http#229]
Hi,

I am using the plugin [ionic-native http](https://ionicframework.com/docs/native/http) in my current project for enabling SSL pinning. I followed the steps mentioned in the [link](https://www.npmjs.com/package/cordova-plugin-advanced-http) but after taking the build, getting an error 'Plugin not installed'. But the plugin is installed and is listed in config.xml file. and package.json.

The certificate is placed inside www/certificates folder and its in DER format (.cer)

Has anyone faced the same issue? Is there any workaround for the same?
Thanks in advance :)

**Comment by SaileshMS** [comment]
@jintzz ,
facing the same issue with the latest Ionic 4. Which version did you use ?

**Comment by jintzz** [comment]
@SaileshMS 
The same version, Ionic4. I tried to implement the solutions mentioned [here](https://github.com/silkimen/cordova-plugin-advanced-http/issues/8), for me it didn't work. But it may be helpful for you

**Comment by silkimen** [comment]
Hey guys, this is a problem with ionic-native and not with this plugin. Please file an issue [there](https://github.com/ionic-team/ionic-native/issues) next time.

I think your problem is related on how you did import the wrapper:
```js
// ionic 4 import
import { HTTP } from '@ionic-native/http/ngx';

// ionic 3 import
import { HTTP } from '@ionic-native/http';
```

**Comment by jintzz** [comment]
@silkimen 
I had gone through these documentations : [ionic-native/http](https://ionicframework.com/docs/native/http) and [Cordova Advanced HTTP](https://www.npmjs.com/package/cordova-plugin-advanced-http) and followed the same instructions mentioned there. My import statement was also the same like you mentioned. But still that issue exists.

I tried removing the plugin and adding it again as mentioned in some of the blogs, still didn't work for me.
Can you please suggest a solution for the same.

**Comment by silkimen** [comment]
If it's not related to the imports (was just an idea), you'll need to open an issue in the ionic-native repository at https://github.com/ionic-team/ionic-native/issues. You can reference this issue here, so it's easier to find a solution for others having the same problem. But unfortunately, I can't help you.
