### ISSUE TITLE
Readme.md links out to a 404 for ssl pinning blog article

### ISSUE THREAD

**Issue by rtpHarry** [silkimen/cordova-plugin-advanced-http#231]
The readme.md links out to a 404 url for the SSL Pinning explanation:

http://blog.lumberlabs.com/2012/04/why-app-developers-should-care-about.html

**Comment by silkimen** [comment]
Thanks for reporting! 👍

**Comment by rtpHarry** [comment]
No worries. You lured me back in with this notification and I spotted that its also on the NPM page. Not sure if that's a separate file or will update itself in a bit automatically... just thought I'd mention it.
