### ISSUE TITLE
wymsee/cordova-http and cordova-advanced-http

### ISSUE THREAD

**Issue by ankithanrsc** [silkimen/cordova-plugin-advanced-http#233]
I need to send form data through my ionic 3 application and have no control of the server end. Native http is wrapped on cordova-advanced-http that does not support formdata. I have tried alternatives such as angular HttpClient, xmlHttpRequest, axios, fetch etc but all of them returned cors related issues. 
I then found wymsee/cordova-http and it worked well for me. But the problem is that, I still use ionic native http for webservices that accept json object. But I am running into "JSON error" in call made using either cordova-plugin-http or cordova-plugin-advanced-http, whichever is added last.
I already had advanced-http and then i added cordovaHTTP using "cordova plugin add". cordovaHTTP returned JSON error. I removed and reinstalled cordovaHTTP and it worked. But now native http returned "JSON error". And so I removed and added cordova-advanced-http and ionic native http again. Now again, native calls worked but cordovaHTTP failed.
Seems like both the plugins cannot co-exist. Is there something I am missing?

**Comment by silkimen** [comment]
Hi ankithanrsc, this plugin is not meant to be used combined with wymsee/cordova-http. Therefore I've never tested it and I can't tell you if it's possible. Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.
