### ISSUE TITLE
i got error illegal character

### ISSUE THREAD

**Issue by sabardotnet** [silkimen/cordova-plugin-advanced-http#235]
i got error when my file name any space. i use uploadfile methode.

"Illegal character in path at index 44: file:///storage/emulated/0/Download/testfile satu dua.pdf"

i use ionic version 3

thanks for answering..

**Comment by silkimen** [comment]
Whitespaces are not valid in URLs, you need to encode them. Please use StackOverflow for this kind of questions. e.g. https://stackoverflow.com/questions/5442658/spaces-in-urls
