### ISSUE TITLE
[Feature] add enumeration style object for error codes

### ISSUE THREAD

**Issue by flobiwankenobi** [silkimen/cordova-plugin-advanced-http#239]
It would be nice if you can provide an enum or something else for the error codes, because they're not documented.

Like this e.g.
```typescript
enum HttpPluginErrorCode {
  generic = -1,
  secureConnectionOrCertificate = -2,
  serverNotFound = -3,
  timeout = -4,
  unsupportedURL = -5,
  noConnection = -6
}
```

**Comment by chuchuva** [comment]
Relevant code is in CordovaHttpBase.java, for reference:

https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/src/android/com/silkimen/cordovahttp/CordovaHttpBase.java#L81

**Comment by flobiwankenobi** [comment]
Yay 🙌🏼
