### ISSUE TITLE
Google Play Blocker: Unsafe SSL TrustManager Defined

### ISSUE THREAD

**Issue by shagulameed298** [silkimen/cordova-plugin-advanced-http#240]
The affected classes define an empty checkServerTrusted() method, thereby disabling SSL validation and hence accepting any SSL certificate as valid, if the class is used when connecting to a server over SSL/TLS.

Regardless of whether the affected classes are actually used at runtime or not, Google Play is blocking any App that defines such an insecure X509TrustManager, as detailed on Google's support page:

"Beginning May 17, 2016, Google Play will block publishing of any new apps or updates containing the unsafe implementation of the interface X509TrustManager."

**Comment by silkimen** [comment]
Hi guys, removing unsafe SSL TrustManager and HostnameVerifier would break server trust mode "nocheck"  (see [README](https://github.com/silkimen/cordova-plugin-advanced-http#setservertrustmode)). This feature is used by many people for testing purposes, it's not meant for production usage. But I've never seen Apps being blocked for this reason, when this feature is not used in your code.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
