### ISSUE TITLE
Google Play Blocker: Unsafe HostnameVerifier Defined

### ISSUE THREAD

**Issue by shagulameed298** [silkimen/cordova-plugin-advanced-http#241]
The vulnerable classes define a custom HostnameVerifier that does not perform any validation of the server's hostname:

// Sample code to initialize an insecure HostnameVerifier

new HostnameVerifier() {

    public boolean verify(String hostname, SSLSession session) {

        return true;

        }

    });

**Comment by silkimen** [comment]
see #240 .
