### ISSUE TITLE
Auto refresh data json url every 60 second

### ISSUE THREAD

**Issue by aligassan** [silkimen/cordova-plugin-advanced-http#244]
l try to get weather data json api . and my code working fine . but l want to update data json url every 60 second . l used setInterval but he doesn't stay longer time , after several  minuet then my app is crash . My question is . does cordova-plugin-advanced-http provde any method for auto  updating data ? . If not , any one know best way to updating data without crash please ?

My code 
 
```
  private getdata() {
    this.http.get(xxxxxxxxxxxxxxxxx', {}, {})
      .then(data => {
        this.Temp = JSON.parse(data.data).vt1observation.temperature;
  
      });

      
  }
  startInterval(){
     setInterval(() => {
         this.platform.ready().then(() => {
            this.getdata()
        });
     }, 5000);
}

```

Thank you

**Comment by silkimen** [comment]
You should wait for the platform to be ready before bootstrapping your application. Don't wait for the platform ready event in every interval step. Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions next time.
