### ISSUE TITLE
Certificate path - Trust anchor certification path not found

### ISSUE THREAD

**Issue by Galiza** [silkimen/cordova-plugin-advanced-http#245]
I'm trying to implement our own certificate into the project, but I can't seem to get the path right.

Here's all my info:
**Ionic 4.12.0
Cordova 8.1.2
Android 8.0.0**

My package.json:
```
"cordova-plugin-advanced-http": {
        "OKHTTP_VERSION": "3.10.0"
},
```
And
```
"cordova-plugin-advanced-http": "^2.1.1",
```

My config.xml:
```
<resource-file src="certificates/cert1.cer" target="app/src/main/assets/cert1.cer" />
<resource-file src="certificates/cert2.cer" target="app/src/main/assets/cert2.cer" />
<resource-file src="certificates/cert3.cer" target="app/src/main/assets/cert3.cer" />
```

My TypeScript:
```this.http.setSSLCertMode('pinned').then(() => logger.debug("Disabled all CERTS valid"));```

Error:

> {"status":-2,"error":"TLS connection could not be established: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found."}

Can someone please help me with this?

**Comment by shaikMohammedGhouse** [comment]
Hi, I'm also getting the same error, have you found the solution??

**Comment by Galiza** [comment]
I have not, still the same error, it doesn't matter where I place the certificates.

**Comment by Galiza** [comment]
@shaikMohammedGhouse If you find the solution, please, do let me know.

**Comment by Asterodeia** [comment]
Hi. I had the exact same error when certificates were not the good ones, or were not in the right place.

Your certificates should be in www/certificates and not in app/src/main/assets/, and you don't need these entries in config.xml

**Comment by Galiza** [comment]
@Asterodeia But isn't www/ dir generated? How am I supposed to leave the certificate inside it?

**Comment by Galiza** [comment]
@shaikMohammedGhouse I think I might have found the fix, at least, it works now.

I changed:
```
<resource-file src="certificates/cert1.cer" target="app/src/main/assets/cert1.cer" />
<resource-file src="certificates/cert2.cer" target="app/src/main/assets/cert2.cer" />
<resource-file src="certificates/cert3.cer" target="app/src/main/assets/cert3.cer" />
```
to
```
<resource-file src="certificates/cert1.cer" target="app/src/main/assets/www/certificates/cert1.cer" />
<resource-file src="certificates/cert2.cer" target="app/src/main/assets/www/certificates/cert2.cer" />
<resource-file src="certificates/cert3.cer" target="app/src/main/assets/www/certificates/cert3.cer" />
```

**Comment by shaikMohammedGhouse** [comment]
@Galiza, Great! But, I'm not still able to resolve it even after changing as above. Does the certificate in the root certificates folder have to be same as the server one? Or Self signed also works fine? In my case, my server certificate is also a self-signed one. Please let me know where I'm missing things!

**Comment by nationdata-it** [comment]
any update on this?

**Comment by bestoak** [comment]
same issue here. and update on this?

**Comment by matteobaldinidev** [comment]
We have the same issue here. Please help

**Comment by lhfongaa** [comment]
I have the same issue. any update?

**Comment by Galiza** [comment]
Honestly, with my changes, I was able to make it work. Ever since this never happened again. 

Try deleting all folders like /platforms, /www and running everything from scratch.

**Comment by lhfongaa** [comment]
@Galiza I want to ask if "pinned" mode supports untrusted certificate (due to its author) as well, as I still can't make it work by following your work.
