### ISSUE TITLE
Reusing Sockets (Android)

### ISSUE THREAD

**Issue by PsyAl** [silkimen/cordova-plugin-advanced-http#247]
Hi,

we are using this plugin to talk to an embedded device with limited ressources in terms of http-connections (~20 connections). We have the feeling that each request (at least for POST, not sure about other http verbs) is send over a new socket (we see timeouts from sockets with differing port numbers). This is in our case a bit problematic since these sockets are "blocked" for 30 seconds (timeout) -> We can send 20 requests and won't get more answers for 30 seconds...

Is there a way to change this behaviour so that sockets are reused - e.g. configuration options?

Thank you very much in advance!

Kind Regards

Samir

**Comment by silkimen** [comment]
Hi Samir, please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) next time for this kind of questions.
You can check #115 for how to keep a socket alive. It's not working for iOS, but it should work for Android. But the server must also support this feature and must not close the socket on the server side.
