### ISSUE TITLE
My app crash with ionic wrapper 

### ISSUE THREAD

**Issue by samisamsam** [silkimen/cordova-plugin-advanced-http#249]
Hi can you help me please. I'm using this plugin throug Ionic-native wrapper but my app is crashing because of it

**Comment by HansKrywaa** [comment]
See this: #https://github.com/dpa99c/phonegap-launch-navigator/issues/207

**Comment by andrej-vasilj** [comment]
The launch-navigator thing is not the only issue. I'm getting this crash on an up-to-date, clean, newly created ionic app. The steps to reproduce couldn't be simpler:

1. create a new ionic app (blank app)
2. add the http plugin according to ionic documentation
3. import http, add it as a provider and inject it into a constructor and make a get request. You can just copy paste the default code from the docs
4. serve the app: ionic serve --devapp -b
5. open it on your phone with the devapp and watch it crash immediately

It's basically a hello world with the http plugin and it's crashing :(

**Comment by silkimen** [comment]
Should be fixed in #297. Closing this, feel free to open a new issue, if this won't solve your problem! 👍
