### ISSUE TITLE
Transactions slow compared to direct requests from webview

### ISSUE THREAD

**Issue by enayetn** [silkimen/cordova-plugin-advanced-http#25]
I am observing slower total transaction times (request start to resolve) now that I have switched from using iOS WebView to WKWebview + Cordova-HTTP transactions provided by this plugin. 

Is it expected that transaction times will increase when switching to this plugin?

Thanks!

**Comment by silkimen** [comment]
Hi enayetn,

I've never checked total transaction times. But yes, I'd expect it to be slower. Every cordova plugin utilizes an abstraction layer making it slower than highly optimized browser API  code. So here is the difference between using native web API vs. using this plugin:
```
native web API:
  1. XHR Request
  2. native implementation (implemented by browser vendor, e.g. V8)

cordova plugin:
  1. www interface of plugin
  2. cordova plugin interface (de-/serializing data)
  3. native implementation of plugin
```

**Comment by enayetn** [comment]
Makes total sense, just was not anticipating it. Thanks for the confirmation!

**Comment by silkimen** [comment]
You are welcome :)
