### ISSUE TITLE
[Bug] [Android] Enable SSL pinning not working

### ISSUE THREAD

**Issue by maybankidh** [silkimen/cordova-plugin-advanced-http#250]
Set ServertrustMode  as "pinned" is not working. But "nocheck"working fine"
 
App able to establish connection with the server and I can see the"__advancedHttpCookieStore__" object create in localStorage as well .but after any service call getting response data always empty.

Plz help me to resolve this issue. Let me if  any setup required. 
The .der file placed in Certificate folder.

 Refer the response received.

****{status: 200, url: "https://XXXXXXXX", headers: {…}, data: ""}
data: ""
headers:
content-language: "en-US"
content-length: "0"
date: "Thu, 29 Aug 2019 09:35:58 GMT"
okhttp-response-source: "NETWORK 200"
okhttp-selected-protocol: "h2"
p3p: "policyref="/w3c/p3p.xml", CP="CAO DSP COR CURa ADMa DEVa OUR IND PHY ONL UNI COM NAV INT DEM PRE""
__proto__: Object
status: 200
url: "https://XXXXXXXXX"
__proto__: Object****

**Comment by silkimen** [comment]
Hi maybankidh, yes your backend service sends you an empty response (content-length is 0 and data field is an empty string). It doesn't look like a problem with the plugin. Try to get some log files from the backend and analyze what's going on. Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.
