### ISSUE TITLE
How to update to OkHttp 4.2.0 (from currently used 3.10.0, which uses HttpUrlFactory)

### ISSUE THREAD

**Issue by VovanSuper** [silkimen/cordova-plugin-advanced-http#256]
Hello!

After build (web part) Ionic4 project I build android project in Android Studio, which in project structure offeres to upgrade to OkHttp 4.2.0 (latest) library from 3.10.0. Problem with HttpUrlFActory class which is (as far as I understand removed from v.4) - and the class being used in code. So should the project (cordova-plugin-advanced-http) be updated to latest dependencies (as `code cleanup` from Android Studio menu doesn't help automatically resolve the upgrade, as from here: https://square.github.io/okhttp/upgrading_to_okhttp_4/)

**Comment by silkimen** [comment]
See #268. Closing this, feel free to open a new issue, if this won't solve your problem! 👍
