### ISSUE TITLE
Invalid certificate only on ionic 4 ios

### ISSUE THREAD

**Issue by tomedalya** [silkimen/cordova-plugin-advanced-http#259]
We use this plugin with ionic 3 everything worked fine.
since we migrated to ionic 4, it works on android but pinned do not work on ios we keep getting 
status: -2 
error: the certificate for this server is invalid ...

it works fine on android, this error occur only on ios (all devices all versions)

**Comment by silkimen** [comment]
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍

**Comment by jkd2bleu** [comment]
For those who has still this problem, I faced the same issue which is related to ionic webpack configuration. Here is how to fix it: https://stackoverflow.com/questions/56857657/ssl-pinning-issue-with-ionic-capacitor/65980732#65980732
