### ISSUE TITLE
JSON request with array data is not working on Android (JSON error)

### ISSUE THREAD

**Issue by matodrobec** [silkimen/cordova-plugin-advanced-http#26]
Hello, I am getting JSON error when I would like to send array data in post request
```javascript
        this.http.setDataSerializer("json");
        this.http
            .post(
            "https://localhost/api/create",
            [{ test: 1 }, { test: 2 }],
            {
                "Accept": "application/json",
                "Content-Type": "application/json"
            }
            )
            .then((response) => {
                console.log('response', response);
            })
            .catch((error) => {
                console.log('error', error);
            })
        ;
```
I try somethink like below but still same error `JSON error`
```
this.http.setDataSerializer("urlencoded");

        this.http
            .post(
            "https://localhost/api/create",
            JSON.stringify([{ test: 1 }, { test: 2 }]),
            {
                "Accept": "application/json",
                "Content-Type": "application/json"
            }
            )
            .then((response) => {
                console.log('response', response);
            })
            .catch((error) => {
                console.log('error', error);
            })
            ;
```

Plagin
```cordova-plugin-advanced-http 1.5.10 "Advanced HTTP plugin"```

How can I send json request  with array data? 

Thanks!

**Comment by S1lentControl** [comment]
https://github.com/silkimen/cordova-plugin-advanced-http#setdataserializer

**Comment by matodrobec** [comment]
@S1lentControl  what I am doing wrong? Can you send me an example?
Thx

**Comment by S1lentControl** [comment]
OOps, I didn't see the method call.
Need more info. What is the error in the first example. Everything looks correct.

**Comment by matodrobec** [comment]
@S1lentControl  I am getting `JSON error` when I am using `[{ test: 1 }, { test: 2 }],`  as array data.

**Comment by bdoooh** [comment]
@matodrobec setting `this.http.setDataSerializer( "json" );` prior to posting just fixed this for me.

**Comment by inabhi9** [comment]
Any update? Setting `this.http.setDataSerializer( "json" );` doesn't work

**Comment by matodrobec** [comment]
@bdoooh I did it as you can see in this issue above https://github.com/silkimen/cordova-plugin-advanced-http/issues/26#issue-263419270 . The problem is that secound param of http.post can be object. I would like do json request with data like Array or Json string. I do not know how to do

```
 this.http
      .post(
            "https://localhost/api/create",
            JSON.stringify([{ test: 1 }, { test: 2 }]),
             ....
      )
```
OR
```
 this.http
     .post(
            "https://localhost/api/create",
            [{ test: 1 }, { test: 2 }],
            ...
     )
```

**Comment by inabhi9** [comment]
This only affects Android version and by looking at the code, it seems most all Cordova http method needs overridden function for `JSONArray params`. I'll try to submit PR if it works

**Comment by silkimen** [comment]
Hi guys,

sending JSON arrays is not supported, atm. @inabhi9 are you sure it's only affecting Android?
 
I see the problem for Android in e.g. [CordovaHttpPlugin.java L56](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/src/android/com/synconset/cordovahttp/CordovaHttpPlugin.java#L56), because it's a JSONObject and not JSONArray.

But I think it could also be a problem with iOS in e.g. [CordovaHttpPlugin.m L148](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/src/ios/CordovaHttpPlugin.m#L148), because it needs to be a NSArray not a dictionary, right?

But actually I haven't tested, yet.

**Comment by inabhi9** [comment]
@silkimen Yes I just tested in iOS 10.3

with this code

```
cordova.plugin.http.setDataSerializer( "json" );
        cordova.plugin.http.post(
            'https://requestb.in/13mhw1r1',
            [{ test: 1 }, { test: 2 }],
            {
                "Accept": "application/json",
                "Content-Type": "application/json"
            },
            (resp: any) => {
                console.log('resp', resp);
            },
            (errorResp: any) => {
                console.log('error', errorResp);
            }
        )
```

and resulted in successful request

![image](https://user-images.githubusercontent.com/1921170/31944628-57e417de-b8ea-11e7-8c80-777e956aaff0.png)

**Comment by bdoooh** [comment]
@matodrobec it should look something like this..

```javascript
this.http.setDataSerializer("json");
this.http.post( url, [{ test: 1 }, { test: 2 }], { 'Content-Type': 'application/json' } );
```

**Comment by matodrobec** [comment]
@silkimen  @bdoooh @inabhi9  I am using Android platform

**Comment by enayetn** [comment]
Hi, I am seeing exactly the same Issue. 

Using POST with an array as the input data, Android fails to complete the request and returns an error of "JSON Error"

The same call on iOS works perfectly fine.

**Comment by enayetn** [comment]
I have solved this for now by sending by data as an object instead of an array

`['item1','item2']` becomes 

```
{
   data : ['item1','item2']
}
```

Luckily I control the server in this case.

**Comment by silkimen** [comment]
@inabhi9 are you currently working on that problem?

**Comment by inabhi9** [comment]
@silkimen Yes I'm trying and hopping to complete it by sunday. If you could do before that feel free to proceed

**Comment by silkimen** [comment]
@inabhi9 I'll fix it. I think it'll be ready today.

**Comment by inabhi9** [comment]
@silkimen Awesome! Waiting for your patch...

**Comment by enayetn** [comment]
@silkimen doing `cordova plugin add` still returns me 1.7.0 not 1.7.1, any ideas?

**Comment by silkimen** [comment]
@enayetn I've released it just now. Can you try again?

**Comment by enayetn** [comment]
@silkimen WORKS! 🎊  thanks so much for this update!

**Comment by BorntraegerMarc** [comment]
I'm experiencing this issue again in version `1.11.1`
