### ISSUE TITLE
[Bug] [ios/android] JSON data sent to API have different format depending on OS

### ISSUE THREAD

**Issue by wijourdil** [silkimen/cordova-plugin-advanced-http#262]
**Describe the bug**
I use the `ionic-native/http` plugin for both android and ios platforms.
I use it to get/post data from an API (written in PHP), and it works for all endpoints except one.

The data I want to post :
```json
{
    "data": [
        {
            "ppty-one": "value-1",
            "ppty-two": "value-2",
            "...": "..."
        },
        { "..." }
    ]
}
```
Data received on API from android / ionic serve :
```php
[
    "data" => [
        [
            "ppty-one" => "value-1",
            "ppty-two" => "value-2",
        ],
        [ /* ... */ ]
    ]
]
```

Data received on API from ios :
```php
[
    "data" => [
        [
            "ppty-one" => "value-1"
        ],
        [
            "ppty-two" => "value-2"
        ],
        [ /* ... */ ]
    ]
]
```

It's really annoying because depending on the mobile device's OS, the API doesn't receive datas in the exact same format.

I tried to use things like `cordova.plugin.http.setDataSerializer('json');` but it didn't changed anything 😞.

**NB:** I "solved" my issue by using `@ionic-native/http` for android and `@angular/common/http` for ios.

**System info**
 - affected HTTP plugin version: 5.13.0
 - affected platform(s) and version(s): iOS
 - affected device(s): every iOS devices
 - cordova version: 8.1.2
 - cordova platform version(s): android 8.1.0, ios 5.0.1

**Are you using ionic-native-wrapper?**
No

<!--**Minimum viable code to reproduce**
If applicable, add formatted sample coding to help explain your problem.

e.g.:
```js
cordova.plugin.http.setDataSerializer('urlencoded');
```-->

<!--**Screenshots**
If applicable, add screenshots to help explain your problem.-->

**Comment by silkimen** [comment]
Hi Wilfried, please add your JS code which is used to create the request. Looks like you're using the plugin wrong at some point.

**Comment by silkimen** [comment]
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍
