### ISSUE TITLE
[Bug] [android] Content Type not being passed with json after recent andoid update

### ISSUE THREAD

**Issue by lucascrandle** [silkimen/cordova-plugin-advanced-http#263]
**Describe the bug**
As of Monday October 28 we started seeing web calls error with HTTP Code 415. I am using ionic 5 and setting the setDataSerializer('json') call.
I noticed that the android system webview released a new version on Monday and wondering if they're related.

I tried upgrading from 1.0.9 to 2.2.0 and that didn't fix it, when manually including content type header it will pass it along.

Wondering if anyone else has seen this issue?

**System info**
 - affected HTTP plugin version: 2.2.0
 - affected platform(s) and version(s): Android 9
 - affected device(s): We tested on Samsung S10e and other various ones
 - cordova version: 7.1.4
 - @angular/platform-browser": "^7.2.15",
 - @angular/platform-browser-dynamic": "^7.2.15

**Are you using ionic-native-wrapper?**
 - ionic-native-wrapper version: 5.5.1
 - did you check [ionic-native issue tracker](https://github.com/ionic-team/ionic-native/issues) for your problem? Yes

**Minimum viable code to reproduce**
If applicable, add formatted sample coding to help explain your problem.

e.g.:
```js
this.http.setDataSerializer('json');
this.http.post().then()...
```

**Screenshots**

**Comment by lucascrandle** [comment]
Update: Using sendrequest appears to fix the issue:
    var post = this.http.sendRequest(url, {data: body, method: "post", serializer: "json"})

**Comment by silkimen** [comment]
Hi Lucas, seems odd to me especially, because `post()` is just a shorthand function for `sendRequest()` (see [public-interface.js#L172](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/www/public-interface.js#L172)). Are you sure that it's making a difference?

**Comment by lucascrandle** [comment]
@silkimen thanks for responding. 
I am sure it made a difference, but I think it was more related to the setDataSerializer call not working correctly. I am leaning this way because the api error code was 415, Unsupported media type, and I could re-create the 415 code in postman by removing the content-type header from the http call.

I was calling post with a custom header object that only contained an Authorization header. Maybe that had something to do with it?

It has been a month with no other community comments, so I will close this. I am happy with just documenting it. Thanks!
