### ISSUE TITLE
Unable to fetch status text reason code

### ISSUE THREAD

**Issue by jeremyspatrick** [silkimen/cordova-plugin-advanced-http#267]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. e.g. I'm always frustrated when [...]

This is a fine line between a bug and a feature request. It appears the current implementation uses NSURLRequest which does not capture the HTTP status text/reason code from the HTTP response object. 

Our api has several different types of 401s and each are differentiated by the status text/reason code.

Core Framework via CFHTTP appears to capture this information but to utilize this would require an entire rewrite of the core functionality of this plugin. 

Is there any current way to get this information that i'm missing?  Is there a workaround or an easy way to convert an NSURLRequest to a CFHTTP Request?

**Describe the solution you'd like**
Ideally this plugin would not only return the status code as an integer but would also have the status text as a string.

**Describe alternatives you've considered**
Replace NSURLRequest with Core Framework.

**Comment by silkimen** [comment]
Hi Jeremy, I understand your problem, because I had to deal with this problem several times. But you shouldn't depend on the status text. You should consider changing the backend API. Here is a good explanation why it's a bad idea: https://stackoverflow.com/a/6373323/3585524

**Comment by jeremyspatrick** [comment]
That's what I ended up doing. Used a header to pass the info. Thanks for
taking the time to respond.

**Comment by silkimen** [comment]
Ok, cool! Glad to hear you could solve your problem 👍
