### ISSUE TITLE
Crash in offline app

### ISSUE THREAD

**Issue by ansarikhurshid786** [silkimen/cordova-plugin-advanced-http#269]
It is really great and working perfectly with ios and android. 

I tried once when i was offline it is directly crashing the application. ......

**Comment by silkimen** [comment]
Please add some detailed info. We don't realize any kind of problems when being offline with the device except that requests will fail, which is obvious.

**Comment by silkimen** [comment]
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍
