### ISSUE TITLE
Android - remove cordova file as a dependency

### ISSUE THREAD

**Issue by REPTILEHAUS** [silkimen/cordova-plugin-advanced-http#271]
I have removed all cordova plugins from my app bar this one (migrated to capacitor) as its pretty good however today the dependency on cordova file plugin has meant I cannot build my app.

I just use this plugin for simple HTTP requests, I have no need for filesystem access. Can this be an optional parameter so that I can have less cordova plugins

https://github.com/apache/cordova-plugin-file/issues/359

**Comment by silkimen** [comment]
Duplicates #238
