### ISSUE TITLE
Add support for aborting requests

### ISSUE THREAD

**Issue by TheCelavi** [silkimen/cordova-plugin-advanced-http#272]
Seams that it is not possible to abort request. Is that planned to implement in the future? (like https://developer.mozilla.org/en-US/docs/Web/API/AbortController)

**Comment by slothstronaut** [comment]
The `sendRequest` method seems to return null, so probably not. Would be great if this were supported!

**Comment by silkimen** [comment]
This will be available in v3.1.0. Thank you @russaa for your great PR!

**Comment by TheCelavi** [comment]
Thanks @russaa ! You rock!
