### ISSUE TITLE
[Bug] [github] ci action in fork fails at 'e2e tests'

### ISSUE THREAD

**Issue by ath0mas** [silkimen/cordova-plugin-advanced-http#281]
**Describe the bug**
After release of v2.3.1 I synced [my fork](https://github.com/ath0mas/cordova-plugin-advanced-http) and pushed it back to GitHub.
But now the ci action **fails**: see [runs/348593431](https://github.com/ath0mas/cordova-plugin-advanced-http/runs/348593431)

**System info**
 - [my fork](https://github.com/ath0mas/cordova-plugin-advanced-http) up to date with Latest commit a4f1217

**debug**
- action is ok up to *Upload artifact to BrowserStack*
  - with expected `Skipping uploading artifact, because BrowserStack credentials are not set.`
- **but** *Run e2e tests* does not skip as it should for a fork?
  - in *test-app.sh* it should exit with `Skipping CI tests, because Saucelabs credentials are not set.` ?
  log shows it continues and error in *caps.js* while `localAndroidDevice` key does not exist in `configs`

**Comment by silkimen** [comment]
Yep, that‘s right! I will need to fix that.

**Comment by silkimen** [comment]
@ath0mas Can you please check if this one  fixed your problem?

**Comment by ath0mas** [comment]
Perfect!
see [runs/349300294](https://github.com/ath0mas/cordova-plugin-advanced-http/runs/349300294) on: push (32187a1) 3x ✔️

**Comment by ath0mas** [comment]
but checks on the main repo seem to be skipped too: [runs/349132412](https://github.com/silkimen/cordova-plugin-advanced-http/runs/349132412) on: push (32187a1)
