### ISSUE TITLE
No setDataSerializer ("multipart") in ionic3

### ISSUE THREAD

**Issue by chenheng0910** [silkimen/cordova-plugin-advanced-http#282]
**There is no setDataSerializer ("multipart") property in my ionic3 project**

I created an ionic3 project and then added plugins **cordova-plugin-advanced-http**

* ionic cordova plugin add cordova-plugin-advanced-http
* npm install --save @ionic-native/http@4

There is no **multipart** attribute in my @ ionic-native / http file :
`/**`
`* Set the data serializer which will be used for all future POST and PUT requests. Takes a string representing the name of the serializer.`
     `* @param serializer {string} The name of the serializer. Can be urlencoded, utf8 or json`
     ` */`
    
`setDataSerializer(serializer: string): void;`

any one can help this?
`"@ionic-native/http": "^4.20.0",`
`"cordova-plugin-advanced-http": "^2.3.1",`
`"cordova-plugin-advanced-http": {
        "OKHTTP_VERSION": "3.10.0"
      }
`
`node: v10.15.0`
`ionic: v5.4.6`

**Comment by silkimen** [comment]
Hi chenheng0910, you are likely using an old version of ionic-native. This problem is not related to this plugin directly. Please check if there is a newer version of ionic-native available and open an issue on their issue tracker.
