### ISSUE TITLE
Send string as payload in POST request

### ISSUE THREAD

**Issue by JamieMcDonnell** [silkimen/cordova-plugin-advanced-http#284]
**Is your feature request related to a problem? Please describe.**
I am trying to POST a Base64 image to a REST API which will save the image to the database. 
Wrapping the base64 string in an array causes the following java error on the back end:
"java.lang.IllegalArgumentException: Illegal base64 character 5b\n\t at java.util.Base64$Decoder.decode0(Base64.java:714" 

**Describe the solution you'd like**
I would like to be able to send a string as the request payload - currently only object and array data types are supported

```js
let url = 'path/to/my/api'
let requestOptions = {
data: 'myBase64EncodedImageAsAString',
method: 'POST'
}
cordova.plugin.http.sendRequest(url, requestOptions, function (response) {
// success
}, function (error) {
// error
})
```

**Describe alternatives you've considered**
I have tried using the upload sendRequest method, but this also does not accept a string, and the back-end API is set up (and I do not have control of it) to accept a simple POST with Content-Type of 'canvas/upload'

**Comment by silkimen** [comment]
Try this and also check out [the documentation](https://github.com/silkimen/cordova-plugin-advanced-http#setdataserializer):

```js
const url = 'path/to/my/api';
const data = 'myBase64EncodedImageAsAString';
const headers = {
  'Content-Type': 'MyOverridden/Content-Type' // only needed if you want to override the default content type "text/plain"
};

cordova.plugin.http.setDataSerializer('utf8'); // this is the important part
cordova.plugin.http.post(url, data, headers, function(response) {
  // success
}, function(response) {
  // error
});
```

**Comment by JamieMcDonnell** [comment]
Hi Sefa,
thanks so much - I missed this simple step in the docs ;( Must be about
time for a holiday! All is working now as expected - thanks for your help.
Regards
Jamie
