### ISSUE TITLE
Remove cordova-plugin-file dependency.

### ISSUE THREAD

**Issue by briny-hitesh** [silkimen/cordova-plugin-advanced-http#285]
In my project we are not given any functionality to upload or download file. So, I dont need Cordova plugin file in My project. But cordova plugin advanced HTTP has dependency on that.

If I'll remove cordova plugin file its throws the error while make build of android or ios.

> Cannot find plugin.xml for plugin "cordova-plugin-file". Please try adding it again.

Can anyone suggest me how resolve this error.

**Comment by silkimen** [comment]
Duplicates #238
