### ISSUE TITLE
An error occured during post proces…esponse: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by leonwong72** [silkimen/cordova-plugin-advanced-http#286]
Hi, sorry to bother you again. I got this error when i add response type json to the options.

> {status: -7, error: "advanced-http: an error occured during post proces…esponse: Unexpected token o in JSON at position 1", url: "http://wecafe.uat.wepost.com.my/api/auth/login/otp", headers: {…}}
status: -7
error: "advanced-http: an error occured during post processing response: Unexpected token o in JSON at position 1"
url: "http://wecafe.uat.wepost.com.my/api/auth/login/otp"
headers: {cache-control: "no-cache, private", content-type: "application/json"}
__proto__: Object

This is my response result without response type json

> {url: "http://wecafe.uat.wepost.com.my/api/auth/login/otp", status: 200, data: "{"login":{"code":537223}}", headers: {…}}
url: "http://wecafe.uat.wepost.com.my/api/auth/login/otp"
status: 200
data: "{"login":{"code":537223}}"
headers: {cache-control: "no-cache, private", content-type: "application/json"}
__proto__: Object

Can you help me with this?

**Comment by silkimen** [comment]
I'm sorry, but I won't debug your application for you. All issues you've created in the last days were about user errors. Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.

**Comment by millerg6711** [comment]
> I'm sorry, but I won't debug your application for you. All issues you've created in the last days were about user errors. Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.

I don't believe this is a user error. I seem to get the same error, whenever I set the response type to "json" it doesn't work. But, when I don't set one.. it works fine. I'm using the latest version with cordova browser, with the sendRequest() method.
