### ISSUE TITLE
[Bug][iOS] CredStore - performQuery - Error copying matching creds.  Error=-25300, But angular/common/http not giving this error

### ISSUE THREAD

**Issue by sankaryg** [silkimen/cordova-plugin-advanced-http#287]
**Describe the bug**
ionic native 4 version always thrown unauthorized error when i am calling my rest api using post request(x-www-form-urlencoded)

**System info**
 - affected HTTP plugin version: 2.3.1
 - affected platform(s) and version(s): ios 13.2
 - affected device(s): iPhone 8
 - cordova version: [e.g. 6.5.0]
 - cordova platform version(s): [e.g. android 7.0.0, browser 5.0.3]

**Are you using ionic-native-wrapper?**
 - ionic-native-wrapper version: [e.g. 5.8.0]
 - did you check [ionic-native issue tracker](https://github.com/ionic-team/ionic-native/issues) for your problem?

**Minimum viable code to reproduce**
If applicable, add formatted sample coding to help explain your problem.

Tried with following code:
getImageAccesToken(): Observable<any>{
  let headers = {'Content-Type':'application/x-www-form-urlencoded'};
  let body = {
        "client_id":"xxxxx",
        "client_secret": "xxxxx",
        "grant_type": "client_credentials",
        "response_type":"token"
      }
  return new Observable((observer)=>{
      this.http.setDataSerializer('urlencoded');
      var observableFromPromise = from(this.http.post(this.API_ACCESS_TOKEN_URL,body,headers));
      observableFromPromise.subscribe(resp=>{
        console.log(resp);
        observer.next(resp);
        observer.complete();
      },err=>{
        observer.error(err);
      })
  });
}

Ionic info:
Ionic:

   Ionic CLI                     : 5.4.9 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 9 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0 

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.14.0 (/usr/local/bin/node)
   npm        : 6.13.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.3 Build version 11C29

Error:

CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = "UAA/client";
    srvr = "****";
    sync = syna;
}

{"status":401,"headers":{"pragma":"no-cache","x-content-type-options":"nosniff","content-type":"application/json;charset=UTF-8","strict-transport-security":"max-age=31536000; includeSubDomains; preload;","date":"Mon, 30 Dec 2019 14:26:33 GMT","x-frame-options":"DENY","x-vcap-request-id":"fe09613d-dca3-4ddf-4651-3f16d577d5e4","www-authenticate":"Basic realm=\"UAA/client\", error=\"unauthorized\", error_description=\"Bad credentials\"","x-xss-protection":"1; mode=block","cache-control":"no-store","content-length":"62"},"url":"***","error":"{\"error\":\"unauthorized\",\"error_description\":\"Bad credentials\"}"}

**Comment by silkimen** [comment]
Please format your source code properly and explain your use-case. Where does this error occur? Looks like something goes wrong on the server side? Do you have some logs from server side?

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
