### ISSUE TITLE
Promise

### ISSUE THREAD

**Issue by gatelli** [silkimen/cordova-plugin-advanced-http#288]
Using http **.get** returns data from website using AngularJS with global variable like {{_variable_}} in the answer, without waiting for the replacement of variables with their values.
How can I do to deal with that, as .get request can return the values ?

Thx !

**Comment by silkimen** [comment]
Hi gatelli, this seems to be a question related to AngularJS and not specifically related to this plugin. Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
