### ISSUE TITLE
add responseType to ionic-native/http/ngx get request

### ISSUE THREAD

**Issue by skyleguy** [silkimen/cordova-plugin-advanced-http#290]
Hello community,

I am having a tremendous amount of trouble getting a response type header to be added to my ionic native http's outgoing request. I am pulling a pdf from my api as application/pdf but i would like the responseType to be blob so that i can use a file reader to display the pdf using another package, ng2-pdf-viewer. Right now without the responseType header being utilized my pdf is corrupted when trying to display it.

Current implementation:

import { HTTP } from '@ionic-native/http/ngx';

constructor(private http: HTTP) {}

const httpOptions: any = {
   'Accept': 'application/pdf'
}
const url: string = 'myPdfUrl.com/thing.pdf'
this.http.get(url, httpOptions)
.subscribe((suc: any) => {
    const myBlob: Blob = new Blob([suc], { type: 'application/pdf'});
    console.log(myBlob);
});

I am successfully printing the blob object of my pdf but when reading it using a fileReader and displaying it using ng2-pdf-viewer it is corrupted.

 I know that using angular's httpClient you can do this as follows:

const options: any = {
    headers: {
      'Accept': 'application/pdf'
   },
   responseType: 'blob'
}

This is working well but i am trying to use ionic's HTTP and doing the same thing does not fix my issue.

Expected Solution (Not working): 

const httpOptions: any = {
   'Accept': 'application/pdf',
   'responseType': 'blob'
}

 I also see that there is a setHeaders on the HTTP instance, but that is also not achieving what i want (although im not sure what value to put for the host).

**So how do I set the responseType to blob using Ionic's HTTP?** I know that support for it was added in release 2.1.1 as stated in this thread:

https://github.com/silkimen/cordova-plugin-advanced-http/issues/171

I am using 2.2.0 so this should be available to me.

**Comment by silkimen** [comment]
Hi Kyle, you'll need to use the `sendRequest` method instead of the shorthand `get` function. This will allow you to pass the `responseType` parameter. Also check out the [README file #sendRequest](https://github.com/silkimen/cordova-plugin-advanced-http#sendrequest).

e.g.
```js
const reqOptions = {
  method: 'get',
  responseType: 'blob',
  headers: {
    accept: 'application/pdf'
  }
};

const url = 'https://myPdfUrl.com/thing.pdf';

this.http.sendRequest(url, reqOptions) ...
```

Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions next time.

**Comment by jojagoma1981** [comment]
Hi Silkimen, I have the same problem in an Ionic App while downloading a PDF.  I am sending the responseType= "blob" but the response value is text. So "response is not blob" error is logged. 
   But if I change the responseType = "text" the response value is a corrupt PDF. Even with a dummy PDF  from https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf. 

Thanks for your help!!!

**Comment by silkimen** [comment]
Please check my e2e specs for an usage example: https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/test/e2e-specs.js#L765-L779

This code is successfully tested on Android (v5.1 & v9) and iOS (v10.3 & v13.2 ). You need to pass the `responseType` parameter as options NOT as header value.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍

**Comment by Homand-Cindy** [comment]
I have the same problem in an Ionic App while downloading a PDF. I am sending the responseType= "blob" but the response value is always text. If i convert the response value to Blob and I read this in PDFViewer, the PDF is corrupted. 

```
import { HTTP, HTTPResponse } from '@ionic-native/http/ngx';
...
public adHTTP: HTTP
...

let res : HTTPResponse = await this.adHTTP.sendRequest("https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf", {method: "get", responseType: "blob"});
console.log(res.data); // res.data is not Blob but is Text 

let blobresp: Blob = new Blob([res.data], {type: "application/pdf"});
console.log(blobresp); // is I use the Blob in PdfViewer, I have an error "PDF is corrupted"
```

Thanks for your help!!!
