### ISSUE TITLE
[Feature] dns over https

### ISSUE THREAD

**Issue by MrBitBucket** [silkimen/cordova-plugin-advanced-http#292]
I would like to use dnsoh dns over https.

I used the code below to extract the IPV4 address and that works fine I can see the correct ip address is being fetched and assigned to app.hostIp.

However, when I try to sendRequest to

'https://' + app.hostIp + '/path/'

I am getting a response that indicates that a dns lookup is being performed as a reverse lookup is performed and fails some how in ssl. I do have my host in my headers along with appropriate Authorization header.

Is there a way to get dnsoh to work with this plugin? 

```js
// do some fancy stuff here
function fetchHostIp(host){
	app.http.sendRequest(
		'https://1.1.1.1/dns-query',
		{
		method: 'get',
		params: {name:host,type:'A'},
		headers: {host:'mozilla.cloudflare-dns.com',accept: "application/dns-json"},
		responseType: 'blob'
		},
		function(response) {
			response.data.text().then(
				function(t){
					try {
						var ob = JSON.parse(t);
					} catch(e){
						alert('JSON parse error in fetchHostIp('+host+')\nt='+t);
					}
					if(ob.Status==0){
						app.hostIp = ob.Answer[0].data;
						alert('host='+host+' addr='+app.hostIp);
						app.baseUrl = setBaseUrl(app.hostIp);
						app.http.setHeader(app.hostIp, 'Authorization', myAuth);
					} else {
						alert('fetchHostIp('+host+') Status='+ob.status);
					}
					});
			},
		function(response) {
			var m='fetchHostIp('+host+') '+ response.status + ' error:' + response.error;
			alert(m);
			}
		);
	}
```

**Comment by silkimen** [comment]
Hi MrBitBucket, honestly I've never used / implemented dnsoh. I think it's better to use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.
