### ISSUE TITLE
How to upload BLOB

### ISSUE THREAD

**Issue by Kepro** [silkimen/cordova-plugin-advanced-http#293]
Hi guys, trying to upload a file, but we have only blob, we don't have that file locally...
I tried with blob, then with URL.createObjectURL but it's not working 

any idea how to use it correctly? or it's not supported?

**Comment by silkimen** [comment]
Hi Kepro, you can use the `multipart` serializer to achieve that. You'll need to create a FormData object, append your blob and then send it via POST or PUT request. See also [#setdataserializer](https://github.com/silkimen/cordova-plugin-advanced-http#setdataserializer) and [Web-APIs-required-for-Multipart-requests](https://github.com/silkimen/cordova-plugin-advanced-http/wiki/Web-APIs-required-for-Multipart-requests).

**Comment by Kepro** [comment]
today I test it on iPad so it's not working with POST in the browser too, not only uploadFile method right?
