### ISSUE TITLE
[Deprecation][Android] drop support for Android < 5

### ISSUE THREAD

**Issue by silkimen** [silkimen/cordova-plugin-advanced-http#297]
This plugin utilizes an OKHTTP Connection factory to support PATCH requests on Android versions 4.4 and older. This was introduced in #79. But this causes a lot of problems (see [related issues](https://github.com/silkimen/cordova-plugin-advanced-http/issues?utf8=%E2%9C%93&q=OKHTTP)).
Android <= 4.4 have a market share < 9% therefore it seems to be good choice to drop support for these versions in upcoming versions of this plugin.

**Comment by silkimen** [comment]
Will be removed in v3.0.0.

**Comment by LyteFM** [comment]
Hi, the commit says this will drop support for Android `< 5.1` while the issue states `< 5.0`. Which one is correct? And I think it would be a good idea to mention the required minimum version in the readme.

**Comment by silkimen** [comment]
Hi @LyteFM, you are right. I've changed the title to state the correct Android SDK level. Will also add it into the readme.
