### ISSUE TITLE
[Feature] Document browser support

### ISSUE THREAD

**Issue by beruic** [silkimen/cordova-plugin-advanced-http#298]
**Is your feature request related to a problem? Please describe.**
I am currently helping out with implementing certificate pinning in our app at work using your plugin.
So far everything seems nice and functional, however changing the apps network communication also breaks testing it locally in the browser.

**Describe the solution you'd like**
I am a bit uncertain, but as I understand it, you do have partial browser support.
If I have understood correctly what browser support is, it would be nice if this was documented how to actually use it.

**Comment by silkimen** [comment]
Hi beruic,

> I am a bit uncertain, but as I understand it, you do have partial browser support.

Yes this plugin does support the cordova `browser` target. But it's only meant for debugging purposes, not for production grade usage. You can find a list of features which are not supported for browser target here: https://github.com/silkimen/cordova-plugin-advanced-http#browser-support

> If I have understood correctly what browser support is, it would be nice if this was documented how to actually use it.

I don't get the question. The API is exactly the same for browser target. But it's not supporting all features.

**Comment by beruic** [comment]
I have realized now that with browser support, the `browser` platform of Cordova was meant.

I am currently maintaining an app where testing is done by running `index.html` in the browser instead. Therefore I had to implement your interface myself, which I did from putting useful pieces together from the contents of the `/www` directory. 

Initially I thought I could use `src/browser/cordova-http-plugin.js`, but even though the names of the functions are the same, the signature of the arguments is not. Can you explain to me why that is?

**Comment by silkimen** [comment]
`src/browser/cordova-http-plugin.js` is the cordova browser target implementation. It's called via `cordova/exec` from within the www interface `src/www/public-interface.js`. Check these lines to see the files registered as the www interface: [plugin.xml#L11-L26](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/plugin.xml#L11-L26). Check these lines to see which files are registered as the browser target code: [plugin.xml#L88-L97](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/plugin.xml#L88-L97).

You can add the `browser` target to cordova, build it and then run this package in the browser. That's what it's meant to be used for. You don't need to re-implement the interface.

**Comment by beruic** [comment]
Well. I needed to run without Cordova, so there were no way around it. Thanks for the clarification though.
