### ISSUE TITLE
Send requests when internet is back (by the OS in background)

### ISSUE THREAD

**Issue by ThomasKientz** [silkimen/cordova-plugin-advanced-http#30]
Is it possible to register background requests ?

So if the app doesn't have internet at the moment, the request is stored and execute later by the OS.

On iOS, I think it can be performed with the property [discretionary](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1411552-discretionary?language=objc)  set on an `Background sessions` of a [URLSession](https://developer.apple.com/documentation/foundation/urlsession).

**Comment by silkimen** [comment]
Hi Thomas,
sorry, we won't support this in the near future. But feel free to fork this repo and implement it according to your needs.
