### ISSUE TITLE
Digest Authentification

### ISSUE THREAD

**Issue by dawiinci** [silkimen/cordova-plugin-advanced-http#302]
Is there any documentation about this? Or is this even possible?

Thanks

**Comment by silkimen** [comment]
Hi dawiinci, this is not a built-in feature, but you can implement it yourself based on this plugin. You'll need to get the nonce value from the server response found in the `www-authenticate` header and then create a `authorization` header.  See https://en.wikipedia.org/wiki/Digest_access_authentication for details.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
