### ISSUE TITLE
Ionic/React support

### ISSUE THREAD

**Issue by pantos27** [silkimen/cordova-plugin-advanced-http#304]
Tried using the plugin on an Ionic+React project and got the following error

```
./node_modules/@ionic-native/http/ngx/index.js
 Module not found: Can't resolve '@angular/core' in '/Users/onionion/Node/ionic_poc/node_modules/@ionic-native/http/ngx'
```

Is there a plan to support also react projects or at least vanilla JS?

**Comment by silkimen** [comment]
This plugin does support vanilla cordova projects, please read the docu. https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md#usage

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
