### ISSUE TITLE
What version of AFNetworking the plugin is using

### ISSUE THREAD

**Issue by akoshkarov** [silkimen/cordova-plugin-advanced-http#307]
Hi, thank you for the great plugin, we are using it in our mobile application for several years.

I'm wondering what version of AFNetworking library we are using in order to understand what features of the library can be used in the plugin?

And the second question: are we constantly upgrading the library version in the plugin to get the latest patches and fixes and how custom modifications of the library applied in the plugin can prevent doing the upgrade to the latest version of the library?

Thanks in advance

**Comment by silkimen** [comment]
Hi Andrey, I can't tell you the base version of AFNetworking used in this plugin anymore. I think it was 3.x. Anyways, it's basically a fork of AFNetworking and some features not needed by this plugin have been removed. Therefore it's not updated to newer versions. I need to apply patches on my own if there are patches affecting functionality of this plugin.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't answer your questions! 👍
