### ISSUE TITLE
Ionic download CORS blocked file

### ISSUE THREAD

**Issue by myin142** [silkimen/cordova-plugin-advanced-http#310]
I am trying to download a file in ionic that is blocked by CORS. This project does say that it by passes the CORS restriction but I do not know if it really works. When I try to download the japanese [edict2 file](https://www.edrdg.org/wiki/index.php/JMdict-EDICT_Dictionary_Project#CURRENT_VERSION_.26_DOWNLOAD) that is CORS blocked, I get a status -1 with the following error object:

```json
{
    "status":-1,
    "url":"http://ftp.monash.edu/pub/nihongo/edicthdr.txt",
    "headers":{
        "okhttp-response-source":"NETWORK 200",
        "etag":"\"bb-59ea00bba3eec\"",
        "content-type":"text/plain; charset=UTF-8",
        "server":"Apache/2.4.6 (Red Hat Enterprise Linux)",
        "keep-alive":"timeout=5, max=100",
        "date":"Sat, 15 Feb 2020 18:17:03 GMT",
        "content-length":"187",
        "accept-ranges":"bytes",
        "last-modified":"Sat, 15 Feb 2020 16:45:12 GMT",
        "okhttp-selected-protocol":"http/1.1",
        "connection":"Keep-Alive"
    },
    "error":"Length: 1"
}
```

When trying to download file that is not blocked, it works fine. It is difficult to find the problem with just that error message. I compared the headers with the one that works, but I do not see any big differences. I use a normal get request with no parameters and headers: `http.get(url, {}, {})`

Any idea what the problem could be? Or is CORS really blocking the request?

**Comment by pcsantana** [comment]
Hi @myin142 , did you solve the problem? I am facing a similar problem.
Thank you.

**Comment by pcsantana** [comment]
Ok, was my mistake. 
My problem was the encoded url.

**Comment by silkimen** [comment]
When you open `http://ftp.monash.edu/pub/nihongo/edicthdr.txt` in your browser, you'll see that the file contains invalid utf8 characters at the beginning. But the header states that plain utf8 encoded text will be loaded. The plugin tries to interpret the data and therefore fails. Try to set the `responseType` option to `arraybuffer` and see if the request still fails. If it's working, you'll need to interpret the data on yourself.

**Comment by myin142** [comment]
The errors seems to be gone, but I have problems reading the data. I do not know if this library returns wrong data or the other library that decodes the data. I have no problems decoding data from a file that is not CORS blocked

**Comment by myin142** [comment]
I found the problem. For some reason it still return a string even though I set the `responseType` to `arraybuffer`. This is probably a bug right?

**Comment by silkimen** [comment]
Please add some MVP code to demonstrate your problem.

**Comment by myin142** [comment]
I am using the ionic native plugin. The url should be replaceable with the simpler one above, have not tested it though.

```
this.http.get('http://ftp.monash.edu/pub/nihongo/edict2.gz', '', {responseType: 'arraybuffer'}).then(data => {
    console.log(typeof data.data);
})
```

**Comment by silkimen** [comment]
You are passing a header `responseType`. This won't work. You need to provide it as an option, which is not possible with the shorthand function `get`. Use `sendRequest` instead, please read the docu carefully: https://github.com/silkimen/cordova-plugin-advanced-http#sendrequest

**Comment by myin142** [comment]
Did not notice that. Thanks, it works now.
