### ISSUE TITLE
uploadFile does not posts image to server file (PHP)

### ISSUE THREAD

**Issue by aecvargas** [silkimen/cordova-plugin-advanced-http#315]
I have a function which opens up the camera and calls another function once the picture has been taken.

```
  open_camera() {
    const options: CameraOptions = {
      quality: 100,
      destinationType: this.camera.DestinationType.FILE_URI,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE
    };
    this.camera.getPicture(options).then(
      imageURI => {
        this.fileUpload(imageURI);
      },
      err => {
        this.f.onError(err, 'ATTACH227', true);
      }
    );
  }
```

This is the code inside fileUpload.

```
this.http
    .uploadFile(
        'https://example.com/pages/attachments.php, {
            action: 'INSERT'
        }, {},
        'file:///storage/emulated/0/Android/data/io.ionic.starter/cache/1583144250046.jpg', // imageURI
        'picture'
    )
    .then(
        fileResult => {
            console.log(fileResult);
        },
        err => {
            this.f.onError(err, 'API244');
        }
    );
	
```

When I check attachments.php here are the results:

`$_GET` contains the param 'action' with the value 'INSERT'
`$_POST` is empty but I expected the params to be in post since I thought I was posting a file to the server.
`$_FILES` is empty. I thought it would populate it with the image from the URI.

I'm getting the error:

> Undefined index: file from $_FILES['file']

I'm not really sure what I'm doing wrong here as I can't seem to get this to work. I'm currently only working it with images from the camera so far but will also be uploading images from the gallery or files. 

I'd appreciate any kind of help and advice to get this working.

Thanks

**Comment by Kepro** [comment]
@aecvargas android? ios? browser?

**Comment by aecvargas** [comment]
@Kepro My bad. It's Android.

**Comment by aecvargas** [comment]
I've got it to kind of work by changing `picture` to `file` but it seems like the data is lacking. I thought it would just send off the entire file details?

Here is the serialize data:

`a:1:{s:4:"file";a:5:{s:4:"name";s:17:"1583510749038.jpg";s:4:"type";s:0:"";s:8:"tmp_name";s:0:"";s:5:"error";i:1;s:4:"size";i:0;}}`

**Comment by gaurav-chandra** [comment]
this is more of server side error. You need to check the logs on the server.

**Comment by silkimen** [comment]
@gaurav-chandra is right, please check your server logs. And please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.
