### ISSUE TITLE
[Feature] Document non-http statuses

### ISSUE THREAD

**Issue by beruic** [silkimen/cordova-plugin-advanced-http#317]
**Is your feature request related to a problem? Please describe.**
I am trying to make my code handle various error scenarios gracefully, but I had to dig into the source code to find out what was going on.

I noticed that whenever there was a timeout, the response would look as follows:
```js
{
  status: -4,
  error: "Request timed out: java.net.SocketTimeoutException: timeout"
}
```
, however I could find no documentation that could tell me that `-4` always means timeout.
I also see other negative statuses that would have been nice to know from the documentation.

**Describe the solution you'd like**
It would make sense to document these negative statuses. Also because it is possible to set a timeout for a request, it should be easy to figure out how to handle when it actually happens.

**Comment by silkimen** [comment]
You are right. This info is missing in the docs. In the meantime you can check this: [www/error-codes.js](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/www/error-codes.js).

**Comment by silkimen** [comment]
Added missing info in README

**Comment by beruic** [comment]
@silkimen did you forget to push? Can't seem to find it anywhere.

**Comment by silkimen** [comment]
it's in the README.md here: https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md#failure

> An enumeration style object is exposed as cordova.plugin.http.ErrorCode. You can use it to check against internal error codes.
