### ISSUE TITLE
[Bug] [android] Requests don't get sent

### ISSUE THREAD

**Issue by pjmazenot** [silkimen/cordova-plugin-advanced-http#318]
**Describe the bug**
On the android platform the request never gets sent. The process stops in the sendBody function and no error is thrown.

**System info**
 - affected device(s): Tested with Pixel 2 API 28 (emulator)
 - cordova version: 9.0.0
 - cordova platform version(s): android 8.1.0

**Are you using ionic-native-wrapper?**
No

**Minimum viable code to reproduce**

```ts
httpRequest(
        getAuthUrl(),
        {
            method: 'post',
            headers: {
                'Accept-Encoding': 'gzip',
                'Connection': 'Keep-Alive',
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            data: {
                username: username,
                password: password
            },
            serializer: 'urlencoded',
        },
        (response: HTTPResponse) => {

            console.log('success');
            console.log(JSON.stringify(response));

           if (successCallback) {
             successCallback();
          }

        },
        (response: HTTPResponse) => {

            console.log('error');
            console.log(JSON.stringify(response));

            if (errorCallback) {
                console.log(response);
                errorCallback(response.error || 'Unknown error');
            }

        }
    );
```

Where

```ts
const httpRequest = (url: string, options: HTTPOptions, success?: (response: HTTPResponse) => void, error?: (response: HTTPResponse) => void) => {

    console.log('-- prepare request --');
    console.log(url);
    console.log(JSON.stringify(options));

    console.log('-- send request --');
    cordova.plugin.http.sendRequest(
        url,
        options,
        function(response: HTTPResponse) {
            // prints 200

            console.log('-- success --');
            console.log(JSON.stringify(response));

            // Execute success callback
            if(success) {
                success(response);
            }
        },
        function(response: HTTPResponse) {
            console.log('-- error --');
            console.log(JSON.stringify(response));

            // Execute error callback
            if(error) {
                error(response);
            }
        }
    );
};
```

**Additional info**

- The Android Studio console display no error
- I was able to track the issue to `openOutput` function in `HttpRequest.java`, this function fails and prevent the rest of the code to be executed
- I have no problem with the same TS code on the iOS platform
- Possibly related to https://github.com/silkimen/cordova-plugin-advanced-http/issues/314

**Comment by silkimen** [comment]
Hi Pierre-Julien, two questions:
1. Is it working when you remove the additional headers sending an empty header object `{}`? 
2. Is your backend URL publicly available for testing purposes?

**Comment by pjmazenot** [comment]
Hi @silkimen, 
Thanks for your reply, sadly I'm working on an internal app so the backend is only accessible via a restricted VPN. 
However I'm experiencing this bug with any public url so it's doesn't seems related to our backend. I also tested without the extra headers as requested, also same results. 
We could talk on Skype or equivalent and I could share my screen if it helps, just let me know.

**Comment by pjmazenot** [comment]
UPDATE and RESOLVED: 

After a few changes in the code the issue link to `openOutput ` disappeared, sadly I don't know which part did the job...

I ended up having trouble with `HttpURLConnection` when trying to do a `getResponseCode` and it ended up originating from a conflict with the internet connection. On the simulation the connection "data" was cutting internet from the connection "wifi" and for whatever reason in that case again no Exception what thrown and the plugin would fail silently.

I fixed it by deactivating my "data" connection. From my research it could also have happened if I was missing the `INTERNET` permission. 

I'm closing this, @silkimen please remove the "need more info" tag if you get the chance.
