### ISSUE TITLE
support for typescript

### ISSUE THREAD

**Issue by cnotoham** [silkimen/cordova-plugin-advanced-http#32]
Hi,

It's not really an issue but rather a request if you plan to support typescript?

Thank you and Regards,
Cornelius

**Comment by ryandegruyter** [comment]
Ionic native offers typescript support for this plugin:

https://ionicframework.com/docs/native/http/

**Comment by cnotoham** [comment]
I am not using ionic just the Angular4 components.  I need the *.d.ts files so that it compiles

**Comment by silkimen** [comment]
Hi cnotoham,

I'm considering migrating our js code to ts, so I could just generate the declaration files you need. But atm I'm struggling with some other feature requests and bugs, so I won't do this for the next version.

**Comment by cnotoham** [comment]
Hi @silkimen,

That will be great. I am pretty sure this will benefit the wider community.

**Comment by cnotoham** [comment]
Hi @silkimen,
 I am now using ionic.  So don't worry about this request.

Thank you.

**Comment by silkimen** [comment]
Closing this, as it's supported by using ionic-native.

**Comment by barrynorman** [comment]
Hi @silkimen,

thank you for the plugin. Actually right now I'm facing the same "issue" AND I'm using Ionic ;) 
I'm using the `sendRequest` but I getting errors, that `sendRequest` does not exist on type HTTP.

This plugin in typescript would be awesome!

**Comment by chax** [comment]
sendRequest() is still not implemented in Ionic wrapper.

**Comment by chax** [comment]
@silkimen, can you add it in this PR:
ionic-team/ionic-native#2370

**Comment by barrynorman** [comment]
@chax Thank you for your reply. 
@silkimen Could you please add also support for `sendRequest` to the PR (https://github.com/ionic-team/ionic-native/pull/2370)?
