### ISSUE TITLE
Slow response for https request

### ISSUE THREAD

**Issue by lucassouza16** [silkimen/cordova-plugin-advanced-http#321]
I have an application that uses the plugin to make calls to api, when using http it works normally, but when using https it takes at least 2 minutes to get the feedback, I already made the same call with xmlhttprequest on the webview and on the postman and it worked normally. Here is an example of my API get request https://myfooddelivery.com.br:8443/api/Inicio/VersaoApp

**Comment by varadig** [comment]
I have a same issue on Android. on iOS is work normally.
`cordova.plugin.http.setRequestTimeout(0.3);`

on iOS is wait 300ms, but Android ....there is no effect.

**Comment by silkimen** [comment]
@varadig slow response has nothing to do with timeout value. So, your problem is not related to this one.

@lucassouza16 I can't see something special with your backend. Try to get log files from the server and inspect them. Unfortunately, I can't help you.

**Comment by varadig** [comment]
Thank you for the answare @silkimen, and there is somethings to do with skip request on long response time? So if the address is no response for example 300ms break the request?

**Comment by varadig** [comment]
I need to use no a two separate branch of my code, becaues on iOS is working your code, but not on Android, and the [Cordova Advanced HTTP 2](https://www.npmjs.com/package/cordova-plugin-advanced-http-2) is wokring on Android, but not on iOS (the same problem, can't setup timeout)

**Comment by Lindsor** [comment]
@varadig no idea if this is related to you but if your building an angular app make sure to wrap the `AdvancedHttp.sendRequest` in `this.ngZone.run()` since this is leaving the browser context angulars ChangeDetection looses context.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍

**Comment by varadig** [comment]
I made a custom timeout system, and stop the request if there was no response
