### ISSUE TITLE
[Bug] [Android] Double Encoding

### ISSUE THREAD

**Issue by pliablepixels** [silkimen/cordova-plugin-advanced-http#322]
**Describe the bug**
 I'm curious what the state of double encoding is. On an android phone, it looks like `cordova.http.sendRequest` (method=`GET`) is URL encoding the base URL, while as per https://github.com/silkimen/cordova-plugin-advanced-http/issues/195 it was mentioned the base URL won't be encoded internally.

Details:
1. I have not changed the serializer (anyway, it is only for `POST/PATCH/etc` not `GET`)

2. Here is my code:

a) The URL I start with is `https://example.com/api/events/consoleEvents/1 hour/AlarmFrames >=:1.json?&token=1234`
b) I then pass it to the plugin like this: `cordova.plugin.http.sendRequest(encodeURI(url),...` (note I use `GET`)

The result of `encodeURI(url)` is  `https://example.com/api/events/consoleEvents/1%20hour/AlarmFrames%20%3E=:1.json?&token=1234`

c) This results in the http plugin erroring with this URL:

```
Inside native HTTP error for url:https://example.com/api/events/consoleEvents/1%2520hour/AlarmFrames%2520%253E=:1.json?&token=1234
````

Which looks like it re-URL encoded my URL.

Am I doing something wrong?

(Caveat: I know some aspects of the URL are not normal, like `?&` but these don't cause any issues in any browser HTTP request I've seen. My question is specifically about how this plugin does URLencoding)

**System info**

cordova platform:
```
Installed platforms:
  android 8.0.0
  ios 5.1.1
```
cordova version:
```
8.1.2 (cordova-lib@8.1.1)
```

http plugin version:
```
cordova-plugin-advanced-http 2.4.1 "Advanced HTTP plugin"
```

Ionic version:
```
 ionic (Ionic CLI) : 4.5.0 (/usr/local/lib/node_modules/ionic)
 @ionic/v1-toolkit : 1.0.22
```

**Comment by silkimen** [comment]
Hi pliablepixels, please check my answer in this issue #337. URL encoding has been an issue in older versions, but it shouldn't be in your version (v2.4.1).

**Comment by pliablepixels** [comment]
Thank you, silkimem. I am going to close this out - this is only happening in certain build from source scenarios of my app that uses your plugin and not always. I've worked around it - thanks for your input.
