### ISSUE TITLE
POST is not working with strange error

### ISSUE THREAD

**Issue by bastifix** [silkimen/cordova-plugin-advanced-http#323]
Hi, I can do a GET request without any problems. The PHP script also works well for POST requests, but when I do a POST request from my ionic app, I always get this error:

`{"__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0},"line":86,"column":22,"sourceURL":"file:///var/containers/Bundle/Application/FAC1A964-4A4A-4081-B9DA-B3D3F1E1BEC1/App.app/www/plugins/cordova-plugin-advanced-http/www/helpers.js"}`

I couldn't find any help so far. Am I doing something wrong?
Here is my ionic code:

```
let postData = new FormData()
  postData.append('s_id',this.s_id)
  postData.append('klasse',this.klasse.id)
  postData.append('stunde',this.stunde.id)
  postData.append('uebungen',JSON.stringify(this.uebungen))
  postData.append('wo_id',woid)

const options = {
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
    }
};

this.http.post(
      'URL.php/', 
      postData,
      options
     )
     .then(response => {
        // prints 200
        console.log("Response-Status: "+response.status);
        try {
          response.data = JSON.parse(response.data);
          // prints test
          console.log("Response-Message: "+response.data.message);
        } catch(e) {
          console.error('JSON parsing error');
        }
     })
     .catch(response => {
       // prints 403
       console.log("Response: "+JSON.stringify(response));
      }
     });
```

**Comment by arnoldgamarram** [comment]
Hi @bastifix you can use **adb logcat** in te terminal to check out more of you error in low level of your app. 

I usually install my app on one device and use chrome://inspect/#devices and logcat to debug my application.

 cheers.

**Comment by bastifix** [comment]
Ok, thanks!
I already tried that, but the above error is the only thing I can get there...

**Comment by arnoldgamarram** [comment]
maybe you can share the code on github and paste the url here.

**Comment by bastifix** [comment]
I shared all of the code above or is there missing something? The same with GET is also working, so I think that all imports etc. are alright.

My PHP file contains this (but I checked this part, it's working): 

```
<?php
$pdo = new PDO('mysql:host=localhost;dbname=*', '*', '*');

$neuer_user = array();
$neuer_user['s_id'] = $_POST['s_id'];
$neuer_user['klasse'] = $_POST['klasse'];
$neuer_user['stunde'] = $_POST['stunde'];
$neuer_user['user'] = $_POST['wow_id'];
$neuer_user['uebungen'] = $_POST['uebungen'];

try {
    $statement = $pdo->prepare("INSERT INTO wot (s_id,klasse,stunde,user,uebungen) VALUES (:s_id, :klasse, :stunde, :user, :uebungen)");

    if (!$statement) {
    echo "\nPDO::errorInfo():\n";
    print_r($pdo->errorInfo());
    }

    $statement->execute($neuer_user);
}
catch(Exception $e) {
    echo 'Exception -> ';
    var_dump($e->getMessage());
}

$statement = $pdo->prepare("SELECT * FROM wot WHERE user = ?");
$statement->execute($neuer_user['user']);   
while($row = $statement->fetch()) {
   echo $row['user']." ".$row['s_id']."<br />";
   echo "Klasse: ".$row['klasse']."<br /><br />";
}

?>
```

**Comment by bastifix** [comment]
Ok, I got an error now:

` advanced-http: "data" option is configured to support only following data types: String`

I tried all forms of only strings in my post-data, but the error stays.

**Comment by silkimen** [comment]
@bastifix please check: 

* https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md#setdataserializer 

* https://github.com/silkimen/cordova-plugin-advanced-http/wiki/Web-APIs-required-for-Multipart-requests

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
