### ISSUE TITLE
POST not working on iOS with ionic 5

### ISSUE THREAD

**Issue by octimus** [silkimen/cordova-plugin-advanced-http#325]
Hello,
when i try to send data by POST using iphone or iphone emulator, the server doesn't get the data.

i'm using ionic 5, and cordova-plugin-advanced-http 2.4.1

**Comment by silkimen** [comment]
Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.
