### ISSUE TITLE
[Feature] [Android] OkUrlFactory is deprecated

### ISSUE THREAD

**Issue by costand** [silkimen/cordova-plugin-advanced-http#327]
**Is your feature request related to a problem? Please describe.**
OkConnectionFactory import which is deprecated and removed in latest versions of OKHTTP

**Describe the solution you'd like**
Android plugin should remove this dependency or include this class as suggested by OkHttps docs: https://gist.github.com/swankjesse/dd91c0a8854e1559b00f5fc9c7bfae70

**Comment by silkimen** [comment]
Duplicates #297 .
