### ISSUE TITLE
How to resend session cookie with next request

### ISSUE THREAD

**Issue by 3adeling** [silkimen/cordova-plugin-advanced-http#328]
I am able to login using this library and I can see the cookie stored in local storage successfully.
but how to send it with the next request(s)? I can't find anything in the documentation related to my question.

your support is highly appreciated

**Comment by silkimen** [comment]
Hi @3adeling, they should be send automatically. There is nothing you need to do. Did you receive valid cookies? Did you check for a valid expiry date?

**Comment by silkimen** [comment]
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍
