### ISSUE TITLE
Get response URL

### ISSUE THREAD

**Issue by longzheng** [silkimen/cordova-plugin-advanced-http#33]
I have a specific scenario where the API I'm calling redirects me to a different success/failure URL (both with status 200 😭).

It doesn't look like the HTTPResponse object contains the URL. 

I'm wondering if it's possible to get this added to the library?

**Comment by longzheng** [comment]
There's also another scenario where I need to get the response URL to extract a token from the URL's parameters.

**Comment by silkimen** [comment]
Hi longzheng,
can you provide me some more info? What exactly is the server responding? Is it a location header like `Location: http://www.example.com/`?

**Comment by longzheng** [comment]
Yep, if the response redirects, then the redirected URL is returned.

The ``response`` object in many request APIs have a ``url`` property that is this URL.

e.g. https://developer.mozilla.org/en-US/docs/Web/API/Response/url

**Comment by silkimen** [comment]
OK, but if we are talking about the `Location` header, you can also get it from the headers property, don't you?  Do you really need to have another property? I understand it would be easier to handle for you, but I think it's a convenience function. Or do I misunderstand your problem?

**Comment by longzheng** [comment]
I think the missing link is the fact that the redirect occurs in a series of HTTP response(s), and the resulting page does not have the ```Location``` header.

For example, in this sequence of HTTP events

Request ```GET https://www.test.com/request```

Response
```
Status: 304

Headers:
Location: https://www.test.com/newaddress

Data: 
N/A
```

Request ```GET https://www.test.com/newaddress```

Response
```
Status: 200

Headers:
...

Data: 
Hello world
```

Your response object will return ```Hello world```, but there is no way to infer the URL of the response. It is transparent (at least to this library) that the response data came from a different URL than the one I requested originally.

**Comment by silkimen** [comment]
Ah ok, now I see the problem! I'll check how to implement this one.

**Comment by longzheng** [comment]
I believe AFNetworking will actually return the URL in the response object, should be able to pass that back as well? https://stackoverflow.com/questions/43556469/how-to-get-full-response-string-in-afnetworking-from-server

I'm sure the Android equivalent has something similar?

**Comment by silkimen** [comment]
will be added in v1.8.0
