### ISSUE TITLE
[Bug] [Android] First Request with HttpUrlConnection, Afterwards always OkHttp

### ISSUE THREAD

**Issue by TheHighriser** [silkimen/cordova-plugin-advanced-http#331]
Description: I am surprised that nobody ever saw this but the second request is ALWAYS with OkHttp. 

Following change is probably necessary: 

```java
protected void prepareRequest(HttpRequest request) throws JSONException, IOException {
    request.followRedirects(this.followRedirects);
    request.readTimeout(this.timeout);
    request.acceptCharset("UTF-8");
    request.uncompress(true);
    HttpRequest.setConnectionFactory(new OkConnectionFactory());
    ...
}
```

to

```java
protected void prepareRequest(HttpRequest request) throws JSONException, IOException {
    HttpRequest.setConnectionFactory(new OkConnectionFactory());
    request.followRedirects(this.followRedirects);
    request.readTimeout(this.timeout);
    request.acceptCharset("UTF-8");
    request.uncompress(true);
    ...
}
```

On the JS side I have a simple request:

```js
await this.http.get('http://testdomain.com/hello.json', {}, { "someheader": headerValue });
```

Proof can be seen when using monitoring solutions like Dynatrace. 

First Request looks like the following:

2020-05-07 12:40:58.576 1543-1638/io.ionic.starter D/caa-aCallbackCore: #13443.PRE_EXEC of getResponseCode of **HttpURLConnectionImpl** to http://testdomain.com/hello.json

Second Request looks like the following:

2020-05-07 12:41:10.010 1543-1639/io.ionic.starter D/caa-aCallbackCore: #13444.POST_EXEC_ERR of getResponseCode of **OkHttpURLConnection** to http://testdomain.com/hello.json

**Comment by silkimen** [comment]
Thanks for reporting this issue, but we are dropping support for Android < 5.1 and therefore don't need to use the OkConnectionFactory class anymore. See #297. Closing this, feel free to open a new issue, if this won't solve your problem! 👍

**Comment by thibaultv** [comment]
Hi @TheHighriser,
Thanks for poinying this bug. As u said, okHttp must be use for old android only but it was not the case. I have maybe a problem due this behavior on 2.4.0 on production application.

For information, the use of okHttp for the second request only is due that the factory is used at the first call of `followRedirects` method that create the connection.
