### ISSUE TITLE
iOS 12 - Post requests turning into get requests

### ISSUE THREAD

**Issue by bryce13950** [silkimen/cordova-plugin-advanced-http#333]
**Describe the bug**
I am having an issue on my iPhone 6 running the most recent version of iOS available (12.4.6) where all post requests appear to be transformed into get requests. I have two devices, one running iOS 13, and another with iOS 12. They are both running the same build, but the problem only persists on my iPhone 6. I first found this bug with an older set of packages, so I updated everything to see if that would make a difference, ran a clean build, and the issue persisted.

**System info**
 - affected HTTP plugin version: 2.4.1
 - affected platform(s) and version(s): iOS 12
 - affected device(s): iPhone 6 (latest device unable to run iOS 13)
 - cordova version: 9.0.0 (cordova-lib@9.0.1)
 - cordova platform version(s): iOS 5.1.1

**Are you using ionic-native-wrapper?**
 - ionic-native-wrapper version: 5.25.0
 - did you check [ionic-native issue tracker](https://github.com/ionic-team/ionic-native/issues) for your problem? Yes

**Minimum viable code to reproduce**

```TypeScript
this.http.post(path, data, this.headers())
```

**Comment by silkimen** [comment]
Hi Bryce, unfortunately I don't have a device running iOS 12, but I've checked on a iPhone 6 Simulator with iOS 12.4. The e2e specs suite is running without any problems and there are a lot of tests which would fail when post requests would turn to get requests. Can you please cross-check your build on a Simulator?

**Comment by bryce13950** [comment]
Is there a debug point that you may be able to advise me to in order to debug this further on a real device on my own?

**Comment by silkimen** [comment]
That's hard to tell, because the problem does not occur on my machine. I think you can start in line [CordovaHttpPlugin.m#L177](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/src/ios/CordovaHttpPlugin.m#L177) and then dig deeper.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
