### ISSUE TITLE
[Bug] Empty JSON response triggers error, even though the request is successful

### ISSUE THREAD

**Issue by antikalk** [silkimen/cordova-plugin-advanced-http#334]
**Describe the bug**
Error status: -7
Error message: advanced-http: an error occurred during post processing response: JSON Parse error, Unexpected EOF

When a REST request returns an empty response body the request fails even though its status indicates it is successful.

This is due to a faulty parsing of the response: With responseType JSON the response is parsed with JSON.parse(response.data) with data being an empty string when the response is empty. This throws an exception.

**Minimum viable code to reproduce**
Call any API that returns an empty response.

**Comment by silkimen** [comment]
Will be fixed in v2.5.1. Thank you Oliver 👍

**Comment by antikalk** [comment]
Thank you! :)

**Comment by antikalk** [comment]
@silkimen: When can I expect 2.5.1 to release? I am using npm as package manager and there is v2.4.1 the latest version. Thank you very much for your work by the way! This plugin really helps me out when trying to switch to WkWebView on iOS. :)

**Comment by silkimen** [comment]
Just released now :)

**Comment by MojioMS** [comment]
same for PUT in v 3.0.1
