### ISSUE TITLE
http.sendRequest Does not work on my Android

### ISSUE THREAD

**Issue by k018c1077** [silkimen/cordova-plugin-advanced-http#336]
I just copy and paste sample code to my Cordova Project.
But,`JSON error` has Occuered.
Could you help me?

`
const options = {
          method: 'post',
          data: { id: 12, message: 'test' },
          headers: { Authorization: 'OAuth2: token' }
        };

        cordova.plugin.http.sendRequest('https://google.com/', options, function (response) {
          console.log(response.status);
        }, function (response) {

          console.log(response); //It says 'JSON error'

          //prints Permission denied
          console.log(response.error);
        });
`

**Comment by silkimen** [comment]
Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.
