### ISSUE TITLE
[Bug] [iOS] request fails with accentuated characters in url

### ISSUE THREAD

**Issue by florian72810** [silkimen/cordova-plugin-advanced-http#337]
When downloading a file from an url with accentuated characters, the request failed with error
```
*** Assertion failure in -[AFHTTPRequestSerializer requestWithMethod:URLString:parameters:error:]
```

**Minimum viable code to reproduce**
```js
const url = 'https://aji-restaurants.com/wp-content/uploads/restaurants/4870/documents/Janvier_Février_Mars_2020-Pdf.pdf';
HTTP.get(url, {}, {});
```

If I escape the string with *encodeURI()*, the requests succeeds. The following works:
```js
const url = 'https://aji-restaurants.com/wp-content/uploads/restaurants/4870/documents/Janvier_Février_Mars_2020-Pdf.pdf';
const encodedUrl = encodeURI(url);
HTTP.get(encodedUrl, {}, {});
```

**System info**
 - affected HTTP plugin version: 2.4.1
 - affected platform(s) and version(s): iOS 13.4.1
 - affected device(s): iPhone SE 2nd Generation
 - cordova version: 9.0.0
 - cordova platform version(s): ios-5.1.1

**Are you using ionic-native-wrapper?**
 - ionic-native-wrapper version: 5.25.0
 - I did check the [ionic-native issue tracker](https://github.com/ionic-team/ionic-native/issues) for the problem

**Comment by silkimen** [comment]
That‘s how it‘s intended to work. You need to escape special characters yourself. This is meant to prevent double encoding of pre-encoded URLs, as many users seem to have this case. It‘s also documented here: https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md#sendrequest

**Comment by florian72810** [comment]
Thanks for your reply.
