### ISSUE TITLE
XMLHttpRequest cannot load on iOS 13.4.1

### ISSUE THREAD

**Issue by khalilbenhassine** [silkimen/cordova-plugin-advanced-http#338]
I am trying to call Restful API on iPhone   with .net backend .
Just for ios 13.4.1 I am getting the below error:
Request header field Authorization is not allowed by Access-Control-Allow-Headers
XMLHttpRequest cannot load http:*****  due to access control checks.

Ionic:

   ionic (Ionic CLI)  : 4.2.1 
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2
   Cordova Platforms     : ios 5.1.1
   Cordova Plugins       :cordova-plugin-advanced-http 2.4.1
cordova-plugin-ionic-webview 4.2.1

**Comment by silkimen** [comment]
If you're using XMLHttpRequest you are not using this plugin. If you have problems with ionic please ask them for support.
