### ISSUE TITLE
Ionic Upload Error: advanced-http: “params” option needs to be an dictionary style object, <params: {[key: string]: string | string[]}>

### ISSUE THREAD

**Issue by louiemiranda** [silkimen/cordova-plugin-advanced-http#339]
I actually posted an issue on stackoverflow; https://stackoverflow.com/questions/62047127/ionic-upload-error-advanced-http-params-option-needs-to-be-an-dictionary-sty.

However, figured that it might be best to ask the author too.

My code, it does not have any syntax error based on the documentation commented below. The issue was related on the params, which I could not figure out why...

> Error: advanced-http: "params" option needs to be an dictionary style object,

`async uploadToAPI(imgEntry) {

    var url = environment.api_host + "/activities/log/images"
    var filePath = imgEntry.localURL;
    var name = 'reports';

    var body = {
        user_hash: 'xxxxxxx',
        activities_id: 1,
        activities_log_id: 1
    }

    var headers = {
        'Authorization': 'Bearer ' + environment.api_security_bearer
    }

    // (method) HTTP.uploadFile(url: string, body: any, headers: any, filePath: string | string[], name: string | string[]): Promise<any>
    // @param url — The url to send the request to
    // @param body — The body of the request
    // @param headers — The headers to set for this request
    // @param filePath — The local path(s) of the file(s) to upload
    // @param name — The name(s) of the parameter to pass the file(s) along as
    // @returns — returns a FileEntry promise that will resolve on success, and reject on failure

    this.http.uploadFile(
        url,
        body,
        headers,
        filePath,
        name,
    ).then((data) => {
        console.log(data)
    })
        .catch(error => {
            console.log(error)
        })
}`

What could I be missing as a mistake on the following code above?
![Screen Shot 2020-05-27 at 11 41 08 PM](https://user-images.githubusercontent.com/10982/83044418-ba46ab00-a076-11ea-926d-8da4b8bff01d.png)

**Comment by Motoralfa** [comment]
Im having the same issue, could find someting?

**Comment by louiemiranda** [comment]
Hi guys, I resolved this by using .sendRequest() and using method "post" since that's what I am using on the API endpoint.

Here's my code and hope this help others as well.

```
this.http.setDataSerializer('multipart')

formData.set('user_hash', 'xxxx')
formData.set('activities_id', this.activities_id)

var url = environment.api_host + "/activities/log/images"

this.http.sendRequest(url, {
    method: "post",
    data: formData,
    headers: this.headers,
    timeout: 60,
})
    .then(response => {
        console.log(response);
    })
    .catch(error => {
        console.log(error);
    });
}
```

**Comment by HardikDG** [comment]
@louiemiranda Where did you added the Blob(image data) in this? Inside FormData? 
Also why use post instead of Upload?
