### ISSUE TITLE
Support sending UTF-8 encoded strings in body (for use with SOAP API)

### ISSUE THREAD

**Issue by juangalalz** [silkimen/cordova-plugin-advanced-http#34]
Hello I need to consume an api that is made in soap, so the body is an xml like this:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://ws/">
   <soapenv:Header xmlns:wsa="http://www.w3.org/2005/08/addressing"><wsa:Action>http://ws/api/accesoRequest</wsa:Action><wsa:MessageID>uuid:1792610b-a8f7-4251-9828-f8bf59e51c35</wsa:MessageID></soapenv:Header>
   <soapenv:Body>
      <ws:acceso>
         <!--Optional:-->
         <usuario>TEST</usuario>
         <!--Optional:-->
         <contrasena>TEST</contrasena>
         <codigo_consulta>12342</codigo_consulta>
      </ws:acceso>
   </soapenv:Body>
</soapenv:Envelope>
```
I send this body as a string:

```
this.http2.post(SERVER_URL, this.envelopeBuilder(method, this.createXmlBody(method, param)), headers)
          .then(data => {
            console.log("data", data);
            console.log(data.data); // data received by server
            this.parseResponse(data.data, cb);

          }).catch(error => {

            console.log("error", error);
            console.log(error.error); // error message as string
            console.log(error.headers);
            this.parseResponse(null, cb);

          });
```

this.envelopeBuilder(method, this.createXmlBody(method, param)) give me a string and works fine with http from @ angular / http

but with the http of @ ionic-native / http does not work for me, apparently the body is treated and does not arrive as it is to the server.

I am not using @ angular / http since I have cors problem and I do not handle the backend so I have to use ionic native

I think you could create an option for the 
`this.http2.setDataSerializer`
 method that insists that the body is raw

**Comment by leongzw** [comment]
+ 1 for this, due to the new introduced ' cordova-plugin-ionic-webview ', it enforces CORS which the previous plugin doesn't, and we couldn't able to configure at api side, we couldn't use http from angular to call soap api anymore

**Comment by MatthieuNarcisi** [comment]
+1 for this too. We need to be able to send raw XML to our server (old API) and do need the requests to NOT be serialized. Sent as raw.

**Comment by iligzar** [comment]
I'm solved for android (maybe is not right)
**_With this.http.setDataSerializer('json');_**
```
let headers = {
       "Content-type": 'text/xml;charset="utf-8"',
       "Accept": "text/xml",
       "Pragma": "no-cache",
       "SOAPAction": _SOAPAction http://*.com/ws/card/getCard _,
       };

let xml = '<?xml version="1.0" encoding="UTF-8"?>' +
      '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" '+
      'xmlns:ns1="'+_namespace_+'"'+
      ' xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="'+_namespace_+'">'+
      '<SOAP-ENV:Header><ns2:UserCredentials>'+
      '<xsd:string>'+_username_+'</xsd:string>'+
      '<xsd:string>'+_password_+'</xsd:string>'+
      '</ns2:UserCredentials></SOAP-ENV:Header>' +
      '<SOAP-ENV:Body><ns1:'+_service_+'>'+_paramsxml_+
      '</ns1:'+_service_+'>' +
      '</SOAP-ENV:Body></SOAP-ENV:Envelope>

this.http.setDataSerializer('json');

this.http.post(soapurl, xml , headers).then( .... ).catch(...)
```
**_With this.http.setDataSerializer('text');_**

**Files:**

 /node_modules/cordova-plugin-advanced-http/src/android/com/github/kevinsawicki/http/HttpRequest.java

/plugins/cordova-plugin-advanced-http/src/android/com/github/kevinsawicki/http/HttpRequest.java

**Add :**

_~119 row_
```
/
   * 'text/text' content type header value
   */
  public static final String CONTENT_TYPE_TEXT = "text/xml";
```
_~2757 row_ 
```
/
   * Set the 'Accept' header to 'text/text'
   *
   * @return this request
   */
  public HttpRequest acceptText() {
    return accept(CONTENT_TYPE_TEXT);
  }

```
**Files:**

 /node_modules/cordova-plugin-advanced-http/src/android/com/synconset/cordovahttp/CordovaHttp.java
/plugins/cordova-plugin-advanced-http/src/android/com/synconset/cordovahttp/CordovaHttp.java

**Edit :**

~141 row (  _protected HttpRequest setupDataSerializer_ )
```
protected HttpRequest setupDataSerializer(HttpRequest request) throws JSONException, Exception {
      if (new String("json").equals(this.getSerializerName())) {
          request.contentType(request.CONTENT_TYPE_JSON, request.CHARSET_UTF8);
          request.send(this.getParamsObject().toString());
      } else if (new String("text").equals(this.getSerializerName())) {
          request.contentType(request.CONTENT_TYPE_TEXT, request.CHARSET_UTF8);
          request.send(this.getParamsObject().toString());
      } else {
          request.form(this.getParamsMap());
      }
```
**Files:**

 /node_modules/cordova-plugin-advanced-http/www/advanced-http.js
**Edit**

_~36 row_
`var validSerializers = ['urlencoded', 'json','text'];`

**Comment by corran2go** [comment]
Don't know why, but `this.http.setDataSerializer('json');` allows sending XML but uses `'content-type': 'application/json; charset=UTF-8',` and it can't be overridden by a custom header `'Content-Type': 'application/xml; charset=utf-8'`

**Comment by iligzar** [comment]
_this.http.setDataSerializer('json');_ with XML work for Android but don't for iOS.

**Comment by iligzar** [comment]
**This method is wrong, but work**
I use  **this.http.setDataSerializer('json');** 
```
let headers = {
       "Content-type": 'text/xml;charset="utf-8"',
       "Accept": "text/xml",
       };
let xml = 'Xml content as string';
this.http.post(soapUrl, xml, headers).then( .... ).catch(...)
```
**For iOS**
I am overwrite **AFURLRequestSerialization.m** file 
_/plugins/cordova-plugin-advanced-http/src/ios/AFNetworking_
_/node_modules/cordova-plugin-advanced-http/src/ios/AFNetworking_

```
if (parameters) {
        if (![mutableRequest valueForHTTPHeaderField:@"Content-Type"]) {
            [mutableRequest setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
        }
        //Comment this row
        //[mutableRequest setHTTPBody:[NSJSONSerialization dataWithJSONObject:parameters options:self.writingOptions error:error]];
       //Add this row
        [mutableRequest setHTTPBody: [parameters dataUsingEncoding:NSUTF8StringEncoding]];
    }
```

**Comment by jondediego** [comment]
Same issue here. Which version of the plugin are you using @iligzar? Your solution doesn't work for me on Andoird, I get an error message: "JSON Error" trying to make a call like you do.
`   http.setDataSerializer('json');
            //bodyRequest is a string that contains xml

            http.post(url ,bodyRequest, {"SOAPAction": soapaction, "Pragma": "no-cache","Content-Type":  "text/xml; charset=utf-8", "Accept": "text/xml"}).then((response) => {
                SOAPClient._onSendSoapRequest(isBrowser, method, async, callback, wsdl, xmlHttp);
            }).catch(e => {
            })`

**Comment by Steve720zhang** [comment]
@jondediego
u shouldnt set 'http.setDataSerializer('json')' and '"Content-Type": "text/xml; charset=utf-8"' at the same time . its doesnt make sense.

**Comment by jondediego** [comment]
Ok @Steve720zhang, so is there currently a way to send raw XML to a server with a NOT serialized body request?

**Comment by silkimen** [comment]
Hi guys,

upcoming version 1.10.0 will support a new serializer `utf8`, which should solve your problem.

e.g. without ionic-native wrapper:
```js
http.setDataSerializer('utf8');
http.setHeader('text/xml; charset=utf-8');

http.post(url, xmlString, additionalHeaders, successHandler, failHandler);
```

e.g. with ionic-native wrapper:
```js
this.http.setDataSerializer('utf8');
this.http.setHeader('text/xml; charset=utf-8');

this.http.post(url, xmlString, additionalHeaders)
  .then(...)
  .catch(...)
```

Basically this "serializer" is just a feature which is passing your string as plain text to the server. So I could have called it `plain`, `text` or `none`, but I've decided to call it `utf8`, because it only supports this encoding.

Please check if this feature fits your needs!

**Comment by mgmanoj** [comment]
`this.http.setHeader('text/xml; charset=utf-8');`
Typescript highlight the above code as error 'Expected 2 arguments, but got one'

**Comment by glen442** [comment]
The documentation says:

`setHeader(host, header, value)`

Set a header for all future requests. Takes a hostname, a header and a value.

Param | Type | Details
-- | -- | --
host | string | The hostname to be used for scoping this header
header | string | The name of the header
value | string | The value of the header
