### ISSUE TITLE
Change certificates 

### ISSUE THREAD

**Issue by nabwill** [silkimen/cordova-plugin-advanced-http#340]
Hi, 

I implemented the plugin in my application. Works fine! My thanks to the community.
I'm afraid if someone decompiles my apk and changes the signed certificates. And in a second moment, recompiled the apk with invalid certificates in order to capture https requests.

Any guidance on that? This is possible?

resource:
https://v0x.nl/articles/bypass-ssl-pinning-android/
https://frida.re/

**Comment by nabwill** [comment]
https://www.preemptive.com/blog/article/1149-tools-don-t-hack-apps-hackers-do-securing-android-apps-against-frida/102-mobile-protection

**Comment by silkimen** [comment]
Hi nabwill, yes, that's absolutely possible. But it's not this plugin's task to prevent this kind of attacks. This plugin supports SSL pinning to create a secure e2e communication channel. It's meant to secure the session data and other sensible data It's not meant to prevent attackers from analyzing your APIs.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
