### ISSUE TITLE
setClientAuthMode not available in npm package

### ISSUE THREAD

**Issue by sansid1983** [silkimen/cordova-plugin-advanced-http#341]
Hi,

I am not able include setClientAuthMode as the selector is missing in TS class. The method is available in the publicInterface and the CordovaHttpPlugin.h, but missing in the ionic-native package.

Thanks

**Comment by jachstet-sea** [comment]
I assume you should report this at https://github.com/ionic-team/ionic-native
This repository (https://github.com/silkimen/cordova-plugin-advanced-http) does not include any TypeScript code

**Comment by silkimen** [comment]
Yep, that's true. Please head to the ionic-native repository: https://github.com/ionic-team/ionic-native
