### ISSUE TITLE
Test suite is failing on HTTP redirect specs

### ISSUE THREAD

**Issue by silkimen** [silkimen/cordova-plugin-advanced-http#344]
**Describe the bug**
The test suite is failing for both Android and iOS on HTTP redirect specs. It's caused by an upstream issue here: https://github.com/postmanlabs/httpbin/issues/617. Hopefully, it's fixed soon. 

**Screenshots**
<img width="595" alt="CleanShot 2020-06-25 at 04 03 44@2x" src="https://user-images.githubusercontent.com/4717881/85645029-e3b81e00-b698-11ea-9d68-49b18d0a01f2.png">

**Comment by ath0mas** [comment]
Many commits linking same issue postmanlabs/httpbin#617 seem to report for _httpbin to be abandoned_ and they migrated their tests to https://httpbingo.org/.

Could this be done here too?

**Comment by silkimen** [comment]
@ath0mas seems to be a good alternative. Do you mind creating a PR?

**Comment by ath0mas** [comment]
@silkimen Sure.

Shall we go for a full replacement of httpbin.org with httpbingo.org, or just for these two specs?
And can I change the default scheme to https, to switch to http only when necessary?
Any advice about "Update test cert for httpbin.org" or so, for ci or other test cases?

**Comment by silkimen** [comment]
Hmm, I think it's better to start with these two specs and see how stable things are working. If it's working stable for the next two months or so, we can replace all specs. I'm also considering another alternative: spinning up a test server every time we're running the specs, but I don't actually know if this is possible with GitHub Actions and Travis CI. 🤔
