### ISSUE TITLE
SSL Pinning by passed using telerick fiddler tool

### ISSUE THREAD

**Issue by anchitd** [silkimen/cordova-plugin-advanced-http#346]
I am developing an  hybrid application, we have used this plugin to have SSL pining in place, Now our security testing complain that SSL pinning is compromised when they use bypass code using telerik fiddler tool , Kindly let me know any ways to restrict the SSL Pinning code not to get bypassed.

Thanks,
Anchit

**Comment by silkimen** [comment]
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍
