### ISSUE TITLE
[Question] [Android] uploadFile() seems does not send form-data to server

### ISSUE THREAD

**Issue by miderose** [silkimen/cordova-plugin-advanced-http#347]
**Describe the bug**
uploadFile() function seems does not send form-data to server (server doesn't receive any of the form-data in the body parameter)

**System info**
 - affected HTTP plugin version: 2.5.1 
 - affected platform(s) and version(s): Android 9
 - affected device(s): Samsung Note 8
 - cordova version: 9.0.0
 - cordova platform version(s): android 8.1.0

**Are you using ionic-native-wrapper?**
 - ionic-native-wrapper version: 5.27.0
 - did you check [ionic-native issue tracker](https://github.com/ionic-team/ionic-native/issues) for your problem?  Yes

**Minimum viable code to reproduce**

```js
    this.http.setDataSerializer('multipart');

    return this.http.uploadFile(
        backendUrl + 'myApiPath',
        {
          data: formData
        },
        {
          Authorization: localStoredToken
        },
        photoFilepath,
        photoFilename
    );
```

**Comment by silkimen** [comment]
Please read the documentation carefully (you're using the API wrong) and use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
