### ISSUE TITLE
[Question] [android] {"status":-1,"error":"There was an error with the request: unexpected end of stream"}",

### ISSUE THREAD

**Issue by hesampour** [silkimen/cordova-plugin-advanced-http#349]
I am using asp.net api for the backend code. I send datta as Json Format. 
calling the api with browser or postman cause no Error.
calling api with cordova-plugin-advanced-http when no html is in the data again cause no Error.
calling api with cordova-plugin-advanced-http when some html code is in the data or data is a little large case There was an error with the request: unexpected end of stream

**Comment by silkimen** [comment]
This might be caused if you have non unicode characters in your data. Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
