### ISSUE TITLE
timed out

### ISSUE THREAD

**Issue by araafat3** [silkimen/cordova-plugin-advanced-http#350]
hi
how to fix this
Request timed out: java.net.SocketTimeoutException: timeout

**Comment by silkimen** [comment]
Please read the documentation carefully and use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
