### ISSUE TITLE
API end expecting ID in formData with "msgId" as key name, but uploadFile doesn't give access for that.

### ISSUE THREAD

**Issue by digholesnehal** [silkimen/cordova-plugin-advanced-http#352]
I am using uploadFile method instead of sending formData in Post method, as Post method doesn't accept any other type than object or array. But my API end expect an id with the file object in formData.. where uploadFile method add id as params or body. How should I access the API if it only accepts a body as formdata as:

```
let formData = new FormData();
 formData.append("msgId",JSON.stringify(data.msgId));
                  files.forEach((f,i)=>{
                    uploadData.append("files",f.file);
                  });
```
The above code snippet is of data which need to send as it is working fine from other platforms such as web, where we are sending this formData using post method. Please guide me to solve this issue.

**Comment by silkimen** [comment]
Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
