### ISSUE TITLE
[Bug] [Browser] responseType "json" not working with valid JSON response

### ISSUE THREAD

**Issue by millerg6711** [silkimen/cordova-plugin-advanced-http#355]
> When using the cordova plugin I experienced the same bug as mentioned in #286. For me the bug occurs when using responseType **json** on the platforms **ios** and **android**.
> 
> While debugging the code I found out, that the error is thrown here:
> 
> ```js
> // json
> if (responseType === validResponseTypes[1]) {
>   response.data = JSON.parse(response.data);
> }
> ```
> 
> [_www/helpers.js_](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/www/helpers.js#L296)
> 
> Then I noticed, that with responseType set to json `response.data` is always a base64 encoded string of the json data. For me that doesn't make sense (as json is a form of text). I edited the native android and ios code to use the text serialization on responseType json.
> 
> **I have not checked platform browser.**

@silkimen I'm using platform browser with the sendRequest(), and responseType "json" - but this doesn't seem to work for me. I get the error - "advanced-http: an error occured during post proces…esponse: Unexpected token o in JSON at position 1". If I take it out, it'll work fine and yes.. the server is returning back valid json

_Originally posted by @millerg6711 in https://github.com/silkimen/cordova-plugin-advanced-http/pull/301#issuecomment-667602251_

**Comment by karahi** [comment]
On 3.1.0 this is happening for me on Android. The server seems to be returning valid JSON according to "curl -L $url | jq".
