### ISSUE TITLE
cordova.plugin.http.setClientAuthMode

### ISSUE THREAD

**Issue by jahanvi-droid** [silkimen/cordova-plugin-advanced-http#357]
I am not able to get the function of setClientAuthMode 

I am using a capacitor in my project and adding a Cordova plugin with the native wrapper with below commands. 

npm install cordova-plugin-advanced-http
npm install @ionic-native/http
ionic cap sync

I have imported HTTP in my app module and using it in service.  But I am not able to add setClientAuthMode function in my service

Can anybody please help me that how to add this plugin correctly in my project to use this function?

**Comment by jahanvi-droid** [comment]
Can anybody please help with the above query? 

I want to user .p12 for SSL certification. But I don't know how to use it?

**Comment by mrakowski0** [comment]
Hey, did you find a solution? I have the same issue currently.

**Comment by jahanvi-droid** [comment]
No I didn't fine anything yet

**Comment by LyteFM** [comment]
https://github.com/silkimen/cordova-plugin-advanced-http/issues/168

This issue is a duplicate and should be closed.

https://github.com/ashenwgt/ionic-capacitor-ssl-pinning -> example repo for how to get it working.

**Comment by Schlupps** [comment]
> #168
> 
> This issue is a duplicate and should be closed.
> 
> https://github.com/ashenwgt/ionic-capacitor-ssl-pinning -> example repo for how to get it working.

No I don't think so. It is not the pinning problem. The function to be used it setClientAuthMode. You can send the certificate for client certificate authentication. I have the same problem. In the current  @ionic-native/http version this function seems not to be implemented.

Any ideas or workarounds?

**Comment by lda573** [comment]
You need to access the cordova plugin from the window obj, and there you can get the function:

export class TestHttpService {
  cordova: any = window["cordova"];

  constructor(private https: HTTP) {}
.......
// In some function, or init:
  this.cordova.plugin.http.setClientAuthMode('systemstore', {}, this.success, this.fail);

.....
//http methods from the HTTP Module -> cordova-plugin-advanced-http
    this.https.get(url, {}, {})
      .then((data) => {
        ...
      })
      .catch((err) => {
        ....
      });

**Comment by silkimen** [comment]
Hi guys,

this problem is related to the ionic wrapper, not the plugin itself. Please open an issue here: https://github.com/ionic-team/ionic-native

Closing this, feel free to open a new issue, if this won't solve your problem! 👍
