### ISSUE TITLE
Cookie handling is handled automatically by this plugin ?

### ISSUE THREAD

**Issue by rajasekarsphcl** [silkimen/cordova-plugin-advanced-http#358]
I tried using this plugin. I hit authentication api and on success, the server sent me a cookie.

I noticed, this plugin seems to be automatically sending the received cookie to the subsequent requests (just like any browser do). 

Is that mean, i don't need to manually store cookie in localstorage and manually set cookie in in subsequent requests?. This plugin will handle that automatically ?

**Comment by silkimen** [comment]
Yes, that's what this plugin does.

**Comment by kristdevmaster** [comment]
@silkimen 
I am using this plugin and get the Response Header from Server.
```
{
   "content-type":"text/html; charset=utf-8",
   "document-policy":"force-load-at-top",
   "pragma":"no-cache",
   "alt-svc":"h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400",
   "x-fb-debug":"uy7wpWBDGT2LiEWSeEXsmv7RE0quSUPNjnPEHgCnmuBmAmmRS+vshllM1O4csxXOKSOy2ehvsKg5cCt+HuZ+Bg==",
   "set-cookie":"datr=lmEqYnbOK6EG6_OuvFTdySd2; expires=Sat, 09-Mar-2024 20:37:42 GMT; Max-Age=63072000; path=/; domain=.facebook.com; secure; httponly, sb=lmEqYi02Rn9PFamIskjGWRUh; expires=Sat, 09-Mar-2024 20:37:42 GMT; Max-Age=63072000; path=/; domain=.facebook.com; secure; httponly",
   "content-encoding":"br",
   "x-xss-protection":"0",
   "expires":"Sat, 01 Jan 2000 00:00:00 GMT",
   "x-fb-rlafr":"0",
   "cache-control":"private, no-cache, no-store, must-revalidate",
   "date":"Thu, 10 Mar 2022 20:37:43 GMT",
   "strict-transport-security":"max-age=15552000; preload; includeSubDomains",
   "x-content-type-options":"nosniff",
   "x-frame-options":"DENY",
   "vary":"Accept-Encoding"
}
```

But at the subsequent request, it shows 401 error. And this plugin's getCookeString(<url to get the above response header>) shows empty string. 
Please let me know where is the issue.
