### ISSUE TITLE
[Bug] [Android] memory leakage leads to app crashes

### ISSUE THREAD

**Issue by silkimen** [silkimen/cordova-plugin-advanced-http#359]
**Describe the bug**
App crashes on Android due to a memory leakage in this plugin. This problem only occurs when the plugin is used heavily and many requests are made in a short period of time.

**Minimum viable code to reproduce**
```js
for (let i = 0; i < 2000; ++i) {
  cordova.plugin.http.get('https://httpbin.org/anything', {}, {}, success, fail);
}
```

**Screenshots**
![CleanShot 2020-07-22 at 00 57 03@2x](https://user-images.githubusercontent.com/4717881/90346802-61aafc80-e02c-11ea-86a6-23727d2febff.png)

**Comment by SamerAtawna** [comment]
I have updated to 3.0.1 and this issue still exists :/ any suggestions?

**Comment by SamerAtawna** [comment]
@silkimen I have updated to 3.0.1 and this issue still exists :/ any suggestions? thanks
