### ISSUE TITLE
Need to check if the cookie is not expired.

### ISSUE THREAD

**Issue by rajasekarsphcl** [silkimen/cordova-plugin-advanced-http#360]
Thanks for this awesome plugin. I just want to know, is there any straightforward way to check if the cookie has expired or not in javascript?.

**Comment by silkimen** [comment]
This plugin does not expose any functionality for this purpose. But you can get the cookie string for a given URL with `getCookieString(url)`. If your cookie has expired it won't be included in this string.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
