### ISSUE TITLE
iOS端 Error Domain=NSURLErrorDomain Code=-1001 "The request timed out."

### ISSUE THREAD

**Issue by wangli1992** [silkimen/cordova-plugin-advanced-http#362]
**You've got questions?**

ionic1项目
ionic info :
ionic (Ionic CLI) : 4.1.2 (/Users/wangli/.nvm/versions/node/v10.13.0/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.3.5
   @ionic/v1-toolkit : 3.1.2

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 5.1.0
   Cordova Plugins       : cordova-plugin-ionic-webview 5.0.0, (and 26 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/wangli/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v10.13.0 (/Users/wangli/.nvm/versions/node/v10.13.0/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 11.5 Build version 11E608c

已知网络状态良好，在iOS端打印输出结果  Task <16A1BA4E-F8D1-4939-B7E1-975203137928>.<1> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x2839ab900 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <16A1BA4E-F8D1-4939-B7E1-975203137928>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <16A1BA4E-F8D1-4939-B7E1-975203137928>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://test17.xgenban.com/sctserver/mob/notice/list?page=1&rows=10&noticeKey=11, NSErrorFailingURLKey=https://test17.xgenban.com/sctserver/mob/notice/list?page=1&rows=10&noticeKey=11, _kCFStreamErrorDomainKey=4}，
提示网络超时，但是网络转态非常好

**Comment by silkimen** [comment]
Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.
