### ISSUE TITLE
Why is the request parameter only a string type, and passing a numeric type gives an error

### ISSUE THREAD

**Issue by wangli1992** [silkimen/cordova-plugin-advanced-http#363]
cordova.plugin.http.setDataSerializer('json');
 var header = { "Content-Type": 'application/json' };
 var options = {"beginTime":1598952780000,"endTime":1598956260000,"meetingContent":"发发发","meetingRoomId":"8669"};
 cordova.plugin.http.post(url,
                options, header, function (response){},function(error){});

Error: advanced-http: "data" option is configured to support only following data types: Array, Object
processData@ionic://localhost/plugins/cordova-plugin-advanced-http/www/helpers.js:410:22
sendRequest@ionic://localhost/plugins/cordova-plugin-advanced-http/www/public-interface.js:151:35
post@ionic://localhost/plugins/cordova-plugin-advanced-http/www/public-interface.js:167:39
postRequest@ionic://localhost/module/common/requester.js:142:37
ionic://localhost/module/common/requester.js:3237:32
ionic://localhost/module/meetingNotice/meetingRoomReservationList.js:103:41
ionic://localhost/module/meetingNotice/meetingRoomReservationList.js:171:44
fn
ionic://localhost/lib/ionic/js/ionic.bundle.min.js:26071:21
$apply@ionic://localhost/lib/ionic/js/ionic.bundle.min.js:13534:193
ionic://localhost/lib/ionic/js/ionic.bundle.min.js:26070:19
Pf@ionic://localhost/lib/ionic/js/ionic.bundle.min.js:13427:481
d@ionic://localhost/lib/ionic/js/ionic.bundle.min.js:13427:425
dispatchEvent@[native code]
triggerMouseEvent@ionic://localhost/lib/ionic/js/ionic.bundle.min.js:2969:20
tapClick@ionic://localhost/lib/ionic/js/ionic.bundle.min.js:2958:20
tapTouchEnd@ionic://localhost/lib/ionic/js/ionic.bundle.min.js:3085:13

**Comment by silkimen** [comment]
Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.
