### ISSUE TITLE
Is neccessary the cordova-plugin-file dependency?

### ISSUE THREAD

**Issue by julianCast** [silkimen/cordova-plugin-advanced-http#367]
Hi, I wonder if the plugin cordova-plugin-file is neccesary.
I say that because the app permission is trying to write and read in a shared storage. and I'm just making http calls.

**The plugin 'cordova-plugin-file' is required by (cordova-plugin-advanced-http)**

Thanks!

**Comment by lempere** [comment]
Yes for the download part:
 
https://github.com/silkimen/cordova-plugin-advanced-http/blob/5f327dc82a0da80b232faaf2e0d87508d9249bc7/src/android/com/silkimen/cordovahttp/CordovaHttpDownload.java#L34

If you don't use that part you could delete it and delete the cordova-plugin-file

**Comment by julianCast** [comment]
Thank you!
