### ISSUE TITLE
Receiving headers for a URL not working correctly

### ISSUE THREAD

**Issue by jkfb** [silkimen/cordova-plugin-advanced-http#37]
The `getMatchingHostHeaders` method determines the headers for a URL based on the domain and port, but the `setHeader` method sets the header based on the domain without the port.

**Comment by silkimen** [comment]
I've checked that, but I don't see a problem here. `setHeader` method sets the header just the way you pass it in:

```js
// will match http://www.example.com/...
cordova.plugin.http.setHeader('www.example.com', 'Header', 'Value');

// will match http://www.example.com:8080/...
cordova.plugin.http.setHeader('www.example.com:8080', 'Header', 'Value');
```

I mean we'll need to document this, but I think it's behaving correctly. Did I miss something?

**Comment by jkfb** [comment]
No you didn't. I assumed that it was your intention to set a header by specifying just the hostname without the port.

**Comment by silkimen** [comment]
OK, I've added a notice in the docu.
