### ISSUE TITLE
Can't load big chunks of data (~50MB) via get()

### ISSUE THREAD

**Issue by SamerAtawna** [silkimen/cordova-plugin-advanced-http#373]
The issues occurs whenever calling an API, the response have heavy data on it and the app crashes;

**System info**
 - affected HTTP plugin version: 3.0.1
 - affected platform(s) and version(s): Android 9
 - cordova version: 9.0.0
 - cordova platform version(s): 9

**Minimum viable code to reproduce**
** this api works so you may use this exact code to reproduce 
```javascript
    for (let index = 1; index < 7; index++) {
      this.http
        .get(
          `https://supermarketabumalk.herokuapp.com/delta?data=ZMOBILE_PM1_MASTER_DATA_SRV_vol${index}`,
          {},
          {}
        )
        .then((res) => {
          console.log(`res ${index}`, res);
        });
    }
```
**Screenshots**
Android studio native error : 
![image](https://user-images.githubusercontent.com/30001759/94968728-19776900-050a-11eb-81bd-7178cdb1d3f4.png)

**Comment by silkimen** [comment]
Hi @SamerAtawna, this is not a memory leak problem. You are trying to load a file which is about ~50MB into your web view. This is done by loading the whole contents into memory, serializing them in the native coding into JSON to pass them into the web view (via cordova bridge functionality). The content is not streamed in chunks into the web view. Therefore it's consuming too much memory.

You should consider using `downloadFile()` to load your data into a temporary location on the disk and then reading the content via `FileReader` API or you can ask the backend developer to create smaller JSON chunks which you can consume one after the other releasing previous chunks.

In either case, it's not an issue in this plugin. It's about how you consume your data.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍

**Comment by SamerAtawna** [comment]
@silkimen Thank you.
