### ISSUE TITLE
[Bug] [iOS] Randomly crashing when [AFSecurityPolicy evaluateServerTrust:forDomain:]

### ISSUE THREAD

**Issue by Adza93** [silkimen/cordova-plugin-advanced-http#376]
**Describe the bug**
While using latest version of cordova-plugin-advanced-http application randomly crashes while performing method [AFSecurityPolicy evaluateServerTrust:forDomain:] in 2 variants. Please help, this issue is really annoying and crashes applications without any notice. All SSL certificates are .cer files DER encoded, and they are valid, so there is no issue with certificates.

**1. Fatal Exception: NSInvalidArgumentException
-[__NSCFString SSLPinningMode]: unrecognized selector sent to instance 0x280416370
-[AFSecurityPolicy evaluateServerTrust:forDomain:]**

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1be2a5654 __exceptionPreprocess
1  libobjc.A.dylib                0x1bdfc7bcc objc_exception_throw
2  CoreFoundation                 0x1be1a9dd8 -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x1be2a97f8 ___forwarding___
4  CoreFoundation                 0x1be2ab71c _CF_forwarding_prep_0
5  AppName                      0x102a4e924 -[AFSecurityPolicy evaluateServerTrust:forDomain:] + 263 (AFSecurityPolicy.m:263)
6  AppName                      0x102a2dd00 __45-[CordovaHttpPlugin setupAuthChallengeBlock:]_block_invoke + 52 (CordovaHttpPlugin.m:52)
7  AppName                      0x102a8d53c -[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] + 970 (AFURLSessionManager.m:970)
8  CFNetwork                      0x1c16a17b0 _CFNetworkHTTPConnectionCacheSetLimit
9  Foundation                     0x1be67a3f0 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
10 Foundation                     0x1be585710 -[NSBlockOperation main]
11 Foundation                     0x1be67c64c __NSOPERATION_IS_INVOKING_MAIN__
12 Foundation                     0x1be585414 -[NSOperation start]
13 Foundation                     0x1be67d044 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
14 Foundation                     0x1be67cb10 __NSOQSchedule_f
15 libdispatch.dylib              0x1bdf4edd0 _dispatch_block_async_invoke2
16 libdispatch.dylib              0x1bdf6b524 _dispatch_client_callout
17 libdispatch.dylib              0x1bdf45274 _dispatch_continuation_pop$VARIANT$armv81
18 libdispatch.dylib              0x1bdf449e8 _dispatch_async_redirect_invoke
19 libdispatch.dylib              0x1bdf51534 _dispatch_root_queue_drain
20 libdispatch.dylib              0x1bdf51cd0 _dispatch_worker_thread2
21 libsystem_pthread.dylib        0x1bdfbcb38 _pthread_wqthread
22 libsystem_pthread.dylib        0x1bdfbf740 start_wqthread

**2. Crashed: NSOperationQueue 0x127f3d140 (QOS: UNSPECIFIED)
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000098f0b2e30**
-[AFSecurityPolicy evaluateServerTrust:forDomain:]
Crashed: NSOperationQueue 0x127f3d140 (QOS: UNSPECIFIED)
0  libobjc.A.dylib                0x1ab8cea70 objc_msgSend + 16
1  AppName                      0x10299ee30 -[AFSecurityPolicy evaluateServerTrust:forDomain:] + 271 (AFSecurityPolicy.m:271)
2  AppName                      0x102995840 __45-[CordovaHttpPlugin setupAuthChallengeBlock:]_block_invoke + 52 (CordovaHttpPlugin.m:52)
3  AppName                      0x1029af8e8 -[AFURLSessionManager URLSession:didReceiveChallenge:completionHandler:] + 970 (AFURLSessionManager.m:970)
4  CFNetwork                      0x1aefef6a4 _CFNetworkHTTPConnectionCacheSetLimit + 199816
5  Foundation                     0x1abf9e004 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
6  Foundation                     0x1abea05a4 -[NSBlockOperation main] + 104
7  Foundation                     0x1abfa0344 __NSOPERATION_IS_INVOKING_MAIN__ + 24
8  Foundation                     0x1abea027c -[NSOperation start] + 752
9  Foundation                     0x1abfa0d70 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
10 Foundation                     0x1abfa0830 __NSOQSchedule_f + 184
11 libdispatch.dylib              0x1ab86bf24 _dispatch_block_async_invoke2 + 144
12 libdispatch.dylib              0x1ab85f5ac _dispatch_client_callout + 20
13 libdispatch.dylib              0x1ab861d60 _dispatch_continuation_pop + 408
14 libdispatch.dylib              0x1ab8614c0 _dispatch_async_redirect_invoke + 588
15 libdispatch.dylib              0x1ab86e724 _dispatch_root_queue_drain + 348
16 libdispatch.dylib              0x1ab86eed0 _dispatch_worker_thread2 + 116
17 libsystem_pthread.dylib        0x1ab8c56dc _pthread_wqthread + 216
18 libsystem_pthread.dylib        0x1ab8cb9c8 start_wqthread + 8

**System info**
 - affected HTTP plugin version: [3.0.1]
 - affected platform(s) and version(s): [iOS 13, and iOS14 reported crash reports so far]
 - affected device(s): [all iOS devices]
 - cordova version: (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1) 
 - cordova platform version(s): [ios 5.1.1]

**Are you using ionic-native-wrapper?**
 - ionic-native-wrapper version: [e.g. 5.8.0]
 - did you check [ionic-native issue tracker](https://github.com/ionic-team/ionic-native/issues) for your problem? Yes, this ios not an issue with ionic platform

**Minimum viable code to reproduce**
If applicable, add formatted sample coding to help explain your problem.

  public setServerTrustMode(mode): Promise<any> {
    return new Promise((resolve, reject) => {
      try {
        cordova.plugin.http.setServerTrustMode(mode, () => {
          console.log('setServerTrustMode: success!');
          resolve("OK");
        }, function () {
          console.log('setServerTrustMode: error!');
          reject("ERROR");
        });
      } catch (error) {
        console.warn("CordovaHttpPlugin called but 'cordova' is not defined. Probably this page is not opened with cordova view",
          error);
        reject("ERROR");
      }
    });
  }

**Comment by silkimen** [comment]
Looks like it's related to #351 therefore I'm closing this one. We can track your issue there.
