### ISSUE TITLE
Improper Validation of Certificate - Android

### ISSUE THREAD

**Issue by subukamath** [silkimen/cordova-plugin-advanced-http#378]
We use this library for our android app. When running Veracode Vulnerability scan for the android app, below vulnerability was reported.

Improper Validation of Certificate with Host Mismatch CWE ID 297
http://cwe.mitre.org/data/definitions/297.html

The failure to validate host-specific certificate data may mean that, while the certificate read was valid, it was not for the site originally requested.

TLSSocketFactory.java Lines 32 37 43 48 54
CordovaServerTrust.java Line 40

**Comment by silkimen** [comment]
**TLSSocketFactory.java**: This code is not validating the certificates. It's an adapter for the socket factory, it's used to enable TLS 1.2 on older android versions and then all other methods are delegated to the original implementation, we just forward the calls. So, it's a false positive.

**CordovaServerTrust.java**: the `noOpTrustManagers` are meant to disable trust validation. It's only used if you [configure the server trust mode "nocheck"](https://github.com/silkimen/cordova-plugin-advanced-http#setservertrustmode). This is meant only for testing purposes and not production usage.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
