### ISSUE TITLE
NSException SSL pinning

### ISSUE THREAD

**Issue by AlekseiFalshtynskii** [silkimen/cordova-plugin-advanced-http#38]
Hello.
I have problems with ios.
I have the latest version of the plugin - 1.7.1.
When checking the certificate for ios error: "libc++abi.dylib: terminating with uncaught exception of type NSException"
But the Android works well.
Could you help me, please?

**Comment by AlekseiFalshtynskii** [comment]
I'm sorry. I figured it out. The certificate was in an incorrect encoding. Close issue.

**Comment by geffroydom** [comment]
Hello, 
I have exactly the same error on IOS only. How did you solved it ? What do you mean by "an incorrect encoding" ? My certificate is a cer file and seems correct, and it works on Android.
Thanks for your help.

**Comment by AlekseiFalshtynskii** [comment]
Hello.
The problem was that my certificate in the .cer format with base64 encoding, but needed with DER encoding.
Sorry for my English.

**Comment by geffroydom** [comment]
Thank you so much, you saved my day !
If someone else have the same problem, here is a page with explanations about certificate encoding formats : https://mssec.wordpress.com/2014/03/06/what-is-the-difference-between-the-formats-der-encoded-and-base64-encoded-when-exporting-a-certificate/

**Comment by silkimen** [comment]
A lot of people are experiencing problems, because they are trying to use a PEM encoded cert. But actually it's written in the docu which kind of cert you need and how to convert it.

Maybe I'll need to implement a cert checking returning a more precise error message.
