### ISSUE TITLE
Missing HostnameVerifier?

### ISSUE THREAD

**Issue by degob** [silkimen/cordova-plugin-advanced-http#380]
Hi Silkimen,
thank you for the cool plugin 'cordova-plugin-advanced-http'.
I am having issues with server trust mode 'pinned'. 
The certificates are being checkd correctly, but as the hostnameVerifier is set to 'null', I get an error that hostname is not verified. 
I wonder if it should be possible to add a hostnameVerifier (maybe even the 'noOpVerifier') to the pinned mode. 
I don't understand what the default hostnameVerifier is being used if set to null (CordovaServerTrust, line 73). 
Can you give me a hint? 
Thank you in advance
Degob

**Comment by silkimen** [comment]
Hi @degob,
I'm sorry for my late response. When the hostname verifier is set to `null` it should use the default verifier provided by `javax.net.ssl.HttpsURLConnection` see [HttpsURLConnection](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/HttpsURLConnection.html). The "magic" is happening [here in CordovaHttpBase.java#L135-L137](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/src/android/com/silkimen/cordovahttp/CordovaHttpBase.java#L135-L137). Where do you get an error that the hostname is not verified? Can you provide us a stack trace?

**Comment by silkimen** [comment]
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍
