### ISSUE TITLE
Add own certificate to cordova app with a Let's Encrypt encrypted backend on Android < 7

### ISSUE THREAD

**Issue by gabn88** [silkimen/cordova-plugin-advanced-http#384]
Starting June 2021Let's Encrypt will start using an new root certificate (https://letsencrypt.org/2020/11/06/own-two-feet.html). This won't work with Android < 7. 
The only feasible workaround is to use okhttp and add a root certificate to the app (https://stackoverflow.com/questions/64844311/certpathvalidatorexception-connecting-to-a-lets-encrypt-host-on-android-m-or-ea and https://github.com/dimagi/commcare-android/pull/2409) 
I think this can be done via this plugin. 
Are you planning to update this plugin to include the new root certificate by default? Or can you help a novice user with setting this up in the cordova app?

**Comment by silkimen** [comment]
Hi @gabn88, this plugin does not support adding new root certificates to the Android system CA store. Though you could pin to the new root certificate, but then you won't be able to communicate with servers using certificates which are issued from another root CA. If this a viable option for you, check [README #setservertrustmode](https://github.com/silkimen/cordova-plugin-advanced-http#setservertrustmode).

**Comment by silkimen** [comment]
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍
