### ISSUE TITLE
Android HostnameVerifier Security Issue 

### ISSUE THREAD

**Issue by SugamAmtrak** [silkimen/cordova-plugin-advanced-http#385]
Hello, when we published the app to Google Play, we received a warning as shown below:

Your app(s) are using an unsafe implementation of the HostnameVerifier interface. You can find more information about how resolve the issue in this Google Help Center article.

We identified that the CordovaServerTrust.java implements the HostnameVerifier and uses the verify method. The problem looks to be around there somewhere. Can anyone please help us resolve the issue? Thank you!

**Comment by silkimen** [comment]
Hi @SugamAmtrak, please check this issue #378. It's okay to ignore this warning as long as you [don't use the "nocheck" trust mode](https://github.com/silkimen/cordova-plugin-advanced-http#setservertrustmode), which is only meant for testing purposes.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
