### ISSUE TITLE
[Bug] [ios] security issue - unsafe Objective-C protocol `NSCoding` has been used in the plugin

### ISSUE THREAD

**Issue by nipuna21018** [silkimen/cordova-plugin-advanced-http#387]
**Description**
The `NSKeyedArchiver` or `NSKeyedUnarchiver` methods used by the Plugin are insecure because they are incompatible with the `NSSecureCoding` protocol. An attacker-controlled payload that is deserialized via these APIs may result in attacker-controlled code being executed.

`NSCoding` is an Objective-C protocol that interoperates with `NSKeyedArchiver` and `NSKeyedUnarchiver`. Together, these APIs allow serialization and deserialization of code objects. However, the `NSKeyedUnarchiver` methods used by the plugin, and the `NSCoding` protocol itself, do not verify the type of object upon deserialization. Thus, an attacker may craft a malicious payload that results in unexpected code being executed.

To mitigate this vulnerability, Apple introduced the `NSSecureCoding` protocol along with the following secure methods of `NSKeyedArchiver` and `NSKeyedUnarchiver`, which are robust against this type of attack:

**Recommandation**
Locate all the classes in the Plugin that conform to `NSCoding` and migrate them to `NSSecureCoding`. Then, replace the insecure usages of `NSKeyedArchiver` and `NSKeyedUnarchiver` with the secure APIs that perform error handling and validate the expected type of the deserialized objects.

**Comment by silkimen** [comment]
Hi Nipuna,

thanks for creating this issue. Where did you find those methods in this plugin? All `NSCoding` conforming classes already do use secure decoding. I can't find any usage of `NSKeyedArchiver ` or `NSKeyedUnarchiver `.

**Comment by nipuna21018** [comment]
Hi Silkimen,

This issue was reported by [DataTheorem](https://www.datatheorem.com/), an agency which scans apps for security. We are using this plugin in our app.

I found `NSCoding` protocol is used in the file `src/ios/AFNetworking/AFHTTPSessionManager.m`, line no 443. 

I thought `NSKeyedArchiver ` and `NSKeyedUnarchiver ` are associated with `NSCoding` protocol. If not please ignore those two methods. 

As per the security finding they have mentioned to migrate from `NSCoding`  to `NSSecureCoding`. I'll close this issue, if you can confirm that `NSCoding` conforming classes already do use secure decoding.

**Comment by silkimen** [comment]
Ah okay, I see. `src/ios/AFNetworking/AFHTTPSessionManager.m` is third party code in `AFNetworking` library. Line 443 is for checking if the `configuration` instance (`NSURLSessionConfiguration`) conforms to `NSCoding`. It's not decoding any data.

The interesting part is happening [here in lines 411-414](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/src/ios/AFNetworking/AFHTTPSessionManager.m#L411-L414). It's decoding instances according to NSSecureCoding (`decodeObjectOfClass`), also check: https://nshipster.com/nssecurecoding/

**Comment by nipuna21018** [comment]
I understood. Thank you for taking time to look into this matter. 
I'm closing this issue as this is not an issue further.
