### ISSUE TITLE
Debugging Network Requests When Using cordova.plugin.http

### ISSUE THREAD

**Issue by ofirattia** [silkimen/cordova-plugin-advanced-http#388]
Hi,
There is any option to debug the calls that being called using cordova.plugin.http on the developer tools? like any other XHR?

Because if I am using the cert pinning for example, I want to see the network calls as well, as of now I am not able to see them.

**Comment by ofirattia** [comment]
I am closing since its duplicate and there is no option to do that.

**Comment by silkimen** [comment]
Hi @ofirattia, you are right, this is a duplicate of #167. Unfortunately, not possible in developer tools.
