### ISSUE TITLE
[E2E Test] [Android] Fail to run e2e tests on Android 7+ emulators

### ISSUE THREAD

**Issue by ath0mas** [silkimen/cordova-plugin-advanced-http#392]
**Describe the bug**
All e2e tests are failing on Android 7+ emulators because of `elementById` reported as an invalid locator ; Appium and/or Chrome seem to have change the way to find elements.

**System info**
 - affected HTTP plugin version: dev 3.1.1
 - affected platform(s) and version(s): Android 7+ (ok for 5 and 6, failing for 7 and 11)
 - affected device(s): local emulators
 - appium version: 1.19.1
 - with current e2e app template (cordova 9, cordova-android 8.1.0, cordova-browser 6.0.0, cordova-ios 5.1.0)

**Logs**
Depending on the Android version &ge; 7 of the emulator, sometimes it reports errors about `context`, but always and for every test the following error too:
```
Uncaught Error: [elementById("nextBtn")] Error response status: 61,  Selenium error: invalid argument: invalid locator
```

**Comment by silkimen** [comment]
Hi @ath0mas, I'm running my test suite with following Android versions without any problems:
* Android 6.0 (emulator on BrowserStack)
* Android 8.0 (emulator on SauceLabs)
* Android 9.0 (emulator & real device on my local machine)

See [test/e2e-tooling/caps.js](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/test/e2e-tooling/caps.js) for details. Are you sure it's not related to your appium setup?
