### ISSUE TITLE
SSL pinning Android Trust anchor for certification not found

### ISSUE THREAD

**Issue by Kashifcbt** [silkimen/cordova-plugin-advanced-http#395]
Hi there i am trying to implement ssl pinning in my ionic  application first i tried with my backend server i got the error 
"TLS connection could not be established: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found." then to check if my ssl certificate is not valid i tried calling  "google.com"
but got same error.
i have download the certificate in the required format as mention in documentation

**System info**
Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 19 other plugins)

Utility:

   cordova-res (update available: 0.15.2) : 0.6.0
   native-run (update available: 1.3.0)   : 1.1.0

System:

   Android SDK Tools : 26.1.1 (/Users/macsystem/Library/Android/sdk)
   ios-deploy        : 1.10.0
   NodeJS            : v10.13.0 (/usr/local/bin/node)
   npm               : 6.14.8
   OS                : macOS Catalina
   Xcode             : Xcode 11.4.1 Build version 11E503a

**Minimum viable code to reproduce**
If applicable, add formatted sample coding to help explain your problem.

e.g.:
```js
  cordova.plugin.http.setServerTrustMode("pinned", function () {
                console.log("SSL pining Success");
                setTimeout(() => {
                    cordova.plugin.http.sendRequest("https://www.google.com", { method: 'get' }, function (data) {
                        console.log(data);
                    }, function (data) {
                        console.log(data);
                    });
                }, 3000);
            }, function () {
                console.log("SSL pining failed");
            });
```

**Comment by Stone-TM** [comment]
I think it could be that the path to your certificate is not the same as the actual path

**Comment by silkimen** [comment]
Did you really try `https://www.google.com`? And did you pin against official `google.com` certificate (see screenshot)?

<img width="510" alt="CleanShot 2021-08-20 at 19 19 08@2x" src="https://user-images.githubusercontent.com/4717881/130270463-8d542c7d-94c6-4e76-9000-15955adbf2d1.png">

**Comment by CodeWithOz** [comment]
@silkimen quick question. Is it up to the developer to have a mechanism that handles changes in the certs of third-party services that the developer is using? For instance in this case if the cert of google is rotated to a new one, it would be up to the developer to prevent that change from affecting his/her app, is that right?
