### ISSUE TITLE
[Feature] [E2E] Update cordova and tools versions for testing

### ISSUE THREAD

**Issue by ath0mas** [silkimen/cordova-plugin-advanced-http#397]
**Is your feature request related to a problem? Please describe.**
CI uses Node.js 10 and test app is built from a template with outdated cordova, platforms and plugins.

**Describe the solution you'd like**
Update CI to **Node.js 14** as latest LTS version,
test app template to **cordova 10**,
with corresponding _modern_ cordova **platforms** (see [list](https://github.com/apache/cordova-lib/blob/10.0.0/src/platforms/platformsConfig.json)),
verifying cordova **plugins**,
updating configs,
and more...

**Comment by silkimen** [comment]
Hi @ath0mas, updated cordova platforms and also some of the dependencies today. Using node 16 on GitHub Actions and node 14 on Travis CI. See https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/test/e2e-app-template/package.json#L13-L17

**Comment by ath0mas** [comment]
Perfect! Thank you 👍
