### ISSUE TITLE
How to use this plugin with jQuery AJAX?

### ISSUE THREAD

**Issue by jfoclpf** [silkimen/cordova-plugin-advanced-http#402]
I'm trying to use like this

```js
cordova.plugin.http.setHeader('user-agent', `my APP`)
$.ajax({
  url: 'https://exemple.com/api',
  data: {
    data1: some_data,
  },
  dataType: 'json',
  type: 'GET',
  async: true,
  crossDomain: true
})
```

Though the request headers are not set. Can I combine this plugin with `$.ajax`?

**Comment by silkimen** [comment]
Well, maybe you can, but I'm not an jQuery expert. You will need to use some hook functionality to achieve this in jQuery sending requests with this plugin instead of XHR requests. You should try asking this on StackOverflow, not here.
