### ISSUE TITLE
[Bug] [iOS] ssl pinned return null

### ISSUE THREAD

**Issue by indraraj26** [silkimen/cordova-plugin-advanced-http#409]
**Describe the bug**
On Android i get 'Ok' but on iOS it returns null

**System info**
 - affected HTTP plugin version: [e.g. 3.1.0] 3.1.0
 - affected platform(s) and version(s): [e.g. iOS 12.2]
 - affected device(s): [e.g. iPhone 8]
 - cordova version: [e.g. 6.5.0] 10.0.0
 - cordova platform version(s): [e.g. android 7.0.0, browser 5.0.3] ios : 6.2.0

**Are you using ionic-native-wrapper?**
 - ionic-native-wrapper version: [e.g. 5.8.0] 5.32.1
 - did you check [ionic-native issue tracker](https://github.com/ionic-team/ionic-native/issues) for your problem? yes

**Minimum viable code to reproduce**
If applicable, add formatted sample coding to help explain your problem.
Repo:  https://github.com/indraraj26/ssl-test
e.g.:
``` 
  async ngOnInit() {
    try {
      await this._platForm.ready();
      const data = await this._http.setServerTrustMode('pinned');
      console.log(data, 'data')
      alert(JSON.stringify(data))
    } catch(e) {
      console.log(e, 'error in catchHandler')
    }
  }/
```

**Screenshots**
![image](https://user-images.githubusercontent.com/23274631/115994982-f53ebf00-a5f6-11eb-9a9e-a4f3eb4f1335.png)

**Comment by thibaultv** [comment]
Hi,

As u can see [here](https://github.com/silkimen/cordova-plugin-advanced-http/blob/d7688b485dea23a132bb8c2e018fb7299000e8cb/src/android/com/silkimen/cordovahttp/CordovaServerTrust.java#L80), this function return nothing. You just have to check if promise returns a success or an error.

Kr.
