### ISSUE TITLE
Question: does true certificate pinning work on Android?

### ISSUE THREAD

**Issue by vroegop** [silkimen/cordova-plugin-advanced-http#411]
I'm not a security expert, but I've been asked to advice my company on implementing certificate pinning for REST requests.

The question I have is that the official documentation tells me Cordova cannot support true certificate pinning on Android, but I don't see any claims or counterclaims about certificate pinning on Android in the readme.

If the official Cordova documentation is right, this plugin would probably verify the certificate fingerprint now and then on Android?

So, to conclude, my question is: is true certificate pinning enabled on Android, or if not how secure is using pinning with this library?

---

**From the docs:**

*Certificate Pinning*
Cordova does not support true certificate pinning. The main barrier to this is a lack of native APIs in Android for intercepting SSL connections to perform the check of the server's certificate. (Although it is possible to do certificate pinning on Android in Java using JSSE, the webview on Android is written in C++, and server connections are handled for you by the webview, so it is not possible to use Java and JSSE there.) Since Apache Cordova is meant to offer consistent APIs across multiple platforms, not having a capability in a major platform breaks that consistency.

There are ways to approximate certificate pinning, such as checking the server's public key (fingerprint) is the expected value when your application starts or at other various times during your application's lifetime. There are third-party plugins available for Cordova that can do that. However, this is not the same as true certificate pinning which automatically verifies the expected value on every connection to the server.

There are also plugins that can do true certificate pinning for some platforms, assuming your app is able to do all of its network requests using the plugin (i.e.: no traditional XHR/AJAX requests, etc).

**Comment by thibaultv** [comment]
Hi,

I think the last sentence refers to this plugin (the main one for native HTTP request on Cordova). You need to make every request through this plugin and not use HttpClient from Angular. I use a wrapper to encapsulate this logic at my side.

If someone has a clue regarding the meaning of "third-party plugins" into the second paragraph. It seems not equal to "plugins".

Kr.

**Comment by silkimen** [comment]
Hey guys, I don't see there is something like "true" SSL pinning. Either it's not pinned or it is. And that's actually what this plugin is doing it's SSL pinning. If a tool is not checking the certificate on every connection to the server it's not SSL pinning.

But @thibaultv did mention an important fact: you need to make every request through this plugin, not with fetch or XHR API.

> If someone has a clue regarding the meaning of "third-party plugins" into the second paragraph. It seems not equal to "plugins".

Nope, I don't have a clue what they mean, but I think they are referring to this plugin in third paragraph.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
