### ISSUE TITLE
Cannot use the plugin in a browser

### ISSUE THREAD

**Issue by Morgs007** [silkimen/cordova-plugin-advanced-http#414]
But how can you test your app using this plugin if you cannot use it in a browser!? So disappointed, only found it you cannot use it in a browser after I changed all my http requests code to use this plugin!

**Comment by silkimen** [comment]
Well, that's documented here: https://github.com/silkimen/cordova-plugin-advanced-http#browser-support

**Comment by Morgs007** [comment]
> 
> 
> Well, that's documented here: https://github.com/silkimen/cordova-plugin-advanced-http#browser-support

You cannot even initialize the plugin, it requires cordova... You cannot even do a simple post/get on a browser, the documentation you've referenced says it **cannot** do only a handful few things.

**Comment by silkimen** [comment]
Ah, now I get your problem! You are trying to run this plugin in the browser without using cordova? That's not how **cordova** plugins are designed to work. This plugin does support following **cordova platforms**:
* android
* browser
* ios 

You will need to add the `browser` platform to your cordova project. See https://www.npmjs.com/package/cordova-browser
This will create a browser bundle which can be executed in the browser, e.g.:
```
cordova platforms add browser
cordova build browser
```
