### ISSUE TITLE
peer did not return a certificate

### ISSUE THREAD

**Issue by girishkc** [silkimen/cordova-plugin-advanced-http#415]
Hi I am trying to send a a request. 
Pinning is successful, but the server throws the error
_TLS connection peer did not send a certificate_
 cURL with same certificates working fine.

Here is the code:
`this.http.setServerTrustMode('pinned')
    .then(() => {
        console.log('[SUCCESS] SSL Pinning Starts!');
    })
    .catch(() => {
        console.log('[ERROR] SSL Pinning Fails!');  
    });

    this.http.get(baseUrl + "/getinfo", {}, {})
    .then (resp => {
        return resp;
    })
    .catch (err => {
        console.log("ERR " + err);
    })`

I am trying it in Android. I have to do this in iOS also.

**Comment by silkimen** [comment]
You are NOT enabling SSL pinning in your example code. You are DISABLING all security guards. Read the readme carefully: https://github.com/silkimen/cordova-plugin-advanced-http#setservertrustmode

**Comment by girishkc** [comment]
> You are NOT enabling SSL pinning in your example code. You are DISABLING all security guards. Read the readme carefully: https://github.com/silkimen/cordova-plugin-advanced-http#setservertrustmode

Sorry. My bad. Edited the post. I was trying all combinations. but no luck yet.

**Comment by silkimen** [comment]
Okay, did you check server logs? Does the device even hit the backend? Did you try with another backend endpoint? e.g. you can check against `https://httpbin.org/anything` (you'll first need to download their certificate and pin against that one).

**Comment by silkimen** [comment]
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍
