### ISSUE TITLE
[Bug] [IOS] AFNetworking deprecated method cause app crash 

### ISSUE THREAD

**Issue by odedle-tr** [silkimen/cordova-plugin-advanced-http#418]
Hi @silkimen. 

We have a third party plugin that uses AFNetwoking. 

It expects the new API of GET method, however the AFNetworking is being overriden with your plugin wich holds an outdated version of AFNetworking. Im sure you are aware of that. 

It is important to mention that we are not using **cordova-plugin-advanced-http** directly. 
We are using **cordova-plugin-code-push** that uses the **cordova-plugin-advanced-http** as a dependency. 

When building the project the AFNetworking is overriden by the  cordova-plugin-advanced-http dependency resulting in an app crash. 

My question is, will there be an update of the AFNetworking soon?
Or, how can we fix this issue? 

Thanks. 

**System info**
 - affected HTTP plugin version:  cordova-plugin-advanced-http - >=2.2.0, cordova-plugin-code-push - 2.0.0
 - affected platform(s) and version(s): tested on IOS 14.4
 - affected device(s): all devices
 - cordova version: 9.0.0
 - cordova platform version(s): cordova-ios: 6.2.0

**Are you using ionic-native-wrapper?**
- no

**Minimum viable code to reproduce**

**We get the error in xcode resulting in an app crash when the 3rd party plugin trying to make a request:**

(lldb) *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AFHTTPSessionManager GET:parameters:headers:progress:success:failure:]: unrecognized selector sent to instance 0x2817ed950'
terminating with uncaught exception of type NSException
(lldb)

**This happens because our third party plugin expect this inteface:**

(NSURLSessionDataTask *)GET:(NSString *)URLString
parameters:(nullable id)parameters
headers:(nullable NSDictionary <NSString *, NSString *> *)headers
progress:(nullable void (^)(NSProgress * _Nonnull))downloadProgress
success:(nullable void (^)(NSURLSessionDataTask * _Nonnull, id _Nullable))success
failure:(nullable void (^)(NSURLSessionDataTask * _Nullable, NSError * _Nonnull))failure

**But the corodva-plugin-advanced-http overrides it with probably an older version (see: 'headers' and 'progress' are missing in this api):**

(NSURLSessionDataTask *)GET:(NSString *)URLString
parameters:(id)parameters
success:(void (^)(NSURLSessionDataTask *task, id responseObject))success
failure:(void (^)(NSURLSessionDataTask *task, NSError *error))failure

**Comment by meiram-tr** [comment]
This PR is fixing the issue, please merge.
https://github.com/silkimen/cordova-plugin-advanced-http/pull/422

**Comment by shaharzilb-tr** [comment]
@silkimen Can you please approve this PR?
#422

**Comment by silkimen** [comment]
Will be fixed in 3.2.1 👍
