### ISSUE TITLE
TLS connection could not be established: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

### ISSUE THREAD

**Issue by bramji06** [silkimen/cordova-plugin-advanced-http#426]
**Describe the bug**
We are using the ionic 3 app and installed this plugin and We are unable to test the app on the android simulator.

**System info**
 - affected HTTP plugin version: [3.2.0]
 - affected platform(s) and version(s): [Android 10]
 - affected device(s): [ Android Simulator]
 - cordova version: [10.0.0]
 - cordova platform version(s): [android 9.0.0]

**Minimum viable code to reproduce**

e.g.:
```js
     this.httpNative.setSSLCertMode('nocheck')
          .then(() => {
            //alert('[SUCCESS] SSL Pinning Starts!');
            console.log('[SUCCESS] SSL Pinning Starts!');
          })
          .catch((error) => {
            //alert('error ssl');
            console.log('[ERROR] SSL Pinning Fails!', error);
          });

Always goes on catch exception.


Also added certificate path in config file 
 <resource-file src="src/assets/certificates/certificate.cer" target="app/src/main/assets/www/certificates/certificate.cer" />
    
```

**Screenshots**
![Screenshot 2021-08-20 185046](https://user-images.githubusercontent.com/2579550/130239562-7b4886a2-5285-4b65-acea-033a29d7dd09.png)

**Comment by silkimen** [comment]
Please read the [documentation](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md) carefully. We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 

* README.md: https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http using the tag `cordova-plugin-advanced-http`
* Wiki: https://github.com/silkimen/cordova-plugin-advanced-http/wiki

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
