### ISSUE TITLE
How to send Authorization "Bearer: Token" in headers?

### ISSUE THREAD

**Issue by snolangps** [silkimen/cordova-plugin-advanced-http#428]
I recently added authentication to my api, and in order to reach it from my app (using cordova-plugin-advanced-http), i need to pass a Bearer token, but I don't see how that is sent?

I noticed the docs mention 
```headers: { Authorization: 'OAuth2: token' }```
but I'm not using OAuth, so question is how to send with jwt token with Bearer authentication?

Thx, Shawn

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
