### ISSUE TITLE
How can we allow only certificates signed by a trusted CA?

### ISSUE THREAD

**Issue by do-pe** [silkimen/cordova-plugin-advanced-http#431]
I already activated SSL-Pinning and it works fine. Now when connecting to a remote endpoint, how can I only allow certificates signed by a trusted CA?

Right now the plugin also accepts self-signed certificates which makes it potentially possible to intercept traffic.

**Comment by demoprojects123** [comment]
Can you paste the pinning code here for reference. as It is not working for self-signed certificate [Internal company] for https url. It is throwing SSLHANDSHAKEEXCEPTION ERROR.

**Comment by silkimen** [comment]
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍
