### ISSUE TITLE
How to include the .cer file in a iOS projetc? 

### ISSUE THREAD

**Issue by Keyurhardas** [silkimen/cordova-plugin-advanced-http#432]
Hi,
I have incorporated the .cer file in my Ionic 3 Android platform using the below tag in my config.xml
 ` <resource-file src="src/certificate/mycert.cer" target="app/src/main/assets/www/certificates/mycert.cer" />`

On android the ssl pinning is working fine. 

I have some doubts in the iOS platform. 
1. How to include the .cer file in the iOS project? 
if I include the above resource file tag in the ios platform section of the config.xml then it gets copied into 
platform/ios/APP-Name/Resources/ 

I really need help in setting this up with iOS. 

Thanks!

**Comment by silkimen** [comment]
Please read the [documentation](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md) carefully. We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 

* README.md: https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http using the tag `cordova-plugin-advanced-http`
* Wiki: https://github.com/silkimen/cordova-plugin-advanced-http/wiki
