### ISSUE TITLE
getCookieString should be exposed

### ISSUE THREAD

**Issue by cnotoham** [silkimen/cordova-plugin-advanced-http#44]
Hi,

Is there any reason why getCookies in https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/www/cookie-handler.js#L48 is not exposed in ionic?

According to the ionic documentation at https://ionicframework.com/docs/native/http/, the only methods exposed are ClearCookies and RemoveCookies

Thanks,
Cornelius

**Comment by silkimen** [comment]
Hi Cornelius,

it's not exposed in ionic because it's not even exposed in this plugin. What do you need that function for? It's meant to be used internally to create the cookie header. Can you explain your use-case?

**Comment by cnotoham** [comment]
Hi Sefa,

I have a requirement whereby I need to set Cookies into an iframe in an ionic application.

**Comment by silkimen** [comment]
Hmm ok, I still don't understand your use-case. This function is meant to create the cookie header string which is sent to the server. So if I'd expose this function you'd be able to get the stored cookies for a specific server. I'm still not sure if this is a good idea (security concerns). But how do you want to use this in an iframe?

e.g. running a GET request to http://www.google.de/
```
// first time internally call (no cookies are set, yet)
getCookieString('http://www.google.de/') --> '' (returns empty string)

// second time internally call (got a set-cookie answer from google on first request)
getCookieString('http://www.google.de/') --> '1P_JAR=2017-11-14-14; NID=117=eNWNV8UDsZIqxAvqTIZm290wdHWmeJyKwvYzEHsIUFu2CYu10ghFTSvPvS-Q2FSLu3QQw' (returns cookie string)
```

Is this you want to have?

**Comment by cnotoham** [comment]
Sorry, I should have explained it to you much better. This is my project requirements ...
I have to develop a single sign on (SSO) app.  Authentication is achieved by using this advanced-http plugin and got the Cookies from the server.  I then need to load an app within an iframe.  This app is loaded via the same authenticator and this authenticator needs the cookies otherwise it will redirect to the authenticator login page.

So for example, authenticated via https://www.xxx.org by using this plugin and then for the iframe, the src url would be:
https://www.xxx.org/someapp

I have written this app in ionic.

I hope this is a bit clearer.

Thanks so much

**Comment by silkimen** [comment]
Ok, thank you for your detailed description. The function "getCookieString" will be exposed in v1.9.0.

**Comment by cnotoham** [comment]
Thank you

**Comment by Bessonov** [comment]
Hello @silkimen,

I don't use this plugin yet, but is there any way to access HttpOnly cookie?

**Comment by silkimen** [comment]
Hi @Bessonov,
yes, you can access HttpOnly cookies just like the other cookies by calling `getCookieString(url)`.

**Comment by Bessonov** [comment]
Thank you for your response, @silkimen! But I don't think this is a good idea, because this isn't intended behavior of HttpOnly and leads to [XSS](https://www.owasp.org/index.php/HttpOnly). Therefore I can't use this plug in :(
