### ISSUE TITLE
HTTP caches have different beheviour on android and iOS

### ISSUE THREAD

**Issue by Kohagan91** [silkimen/cordova-plugin-advanced-http#441]
Hi !

I opened this issue to discuss about the data cached on device when you use android and iOS devices.

When you use this plugin on an android device, it seems no data are cached on the device. But when looking on iOS, it seems that all requests/responses are stored on the hard drive of the device in a cache.db file.

This can be a security risk. On a jailbreak device, other apps can freely access  this cache.db file and potentially get sensitive information from him.

After looking at the iOS source code, I found that is due to the session configuration which is created from the [defaultSessionConfiguration](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1411560-defaultsessionconfiguration).

https://github.com/silkimen/cordova-plugin-advanced-http/blob/5b8f20e1c4c916d1dc052d7ad9de9c8ae1b39baa/src/ios/SM_AFNetworking/SM_AFURLSessionManager.m#L513

For my own use case, I just added a line after this one to completely disable cache, but I'm pretty sure that can be good to have an option to disable cache for users that want it.

`configuration.URLCache = nil;`

Sorry for my bad english,
Regards

**Comment by silkimen** [comment]
Hi @Kohagan91, thank you for finding and reporting this! Yes, I agree that this can be a security risk. Therefore we should disable it and if someone needs the caching option, we can open a new feature request for this purpose. Would you mind creating a PR for this?
