### ISSUE TITLE
http.post seems to cache the request: I have to "localStorage.clear()" on console tab to get another value

### ISSUE THREAD

**Issue by giacomomasseron** [silkimen/cordova-plugin-advanced-http#456]
Hi,  
I have a Ionic 4 / Angular project, with a simple http.post request.

    var res = await this.http.post(myurl, {}, {
        Cache-Control: "no-cache"
        Content-Type: "application/json"
        Cookie: "SSESS....=....."
    });
    // it is a drupal request

I get this singular behaviour:
I get new value from the request only if i use `localStorage.clear()` on console tab of chromium. Otherwise I get a different value.

I do not know what it can be.
Any thought?

**Comment by silkimen** [comment]
What do you mean with "I get new value from the request"? Would you please provide more information?

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem! 👍
