### ISSUE TITLE
Memory leaks sensitive information

### ISSUE THREAD

**Issue by vv619-perf** [silkimen/cordova-plugin-advanced-http#458]
In our application, during the security testing, they were able to get the request and response details from the memory dump.
Please find the following details they were able to get from the dump, is there any option or process we can implement to remove this for happening:
CordovaHttpPlugin1351829997
CordovaHttpPlugin
post https://***.***/login 
username: ***** 
password *****  
json 
Authorization 
Bearer 
null 
Content-Type 
application/json 
Accept
text 
ionic

**Comment by vv619-perf** [comment]
Got some more details from the security team, the data is collected using "**fridump**" tool. It can get the in-memory details.

Have anyone faced similar issue or provide any suggestions

**Comment by silkimen** [comment]
I guess your pen tester team is using a rooted device, right? And then they dump data from memory? This will allow you to get sensitive information from any app.

**Comment by msathya03** [comment]
Hi even we are facing the same issue. Our pen tester is able to get the credentials from memory dump using Frida tool.  Do you have action plan to fix this memory leak issue in cordova-plugin-advanced-http plugin? 
Awaiting for your response. Thanks in advance.

**Comment by vv619-perf** [comment]
Hi @msathya03m, for our case we prevented the application to be installed in an rooted device - We stopped users from login when the application detects its installed in an rooted device.
Security team was happy with the prevention and have considered the issue resolved.

**Comment by msathya03** [comment]
Hi @vv619-perf , Thank you for the update. It will be  great if you share the formation about the root detection plugin which you are using . Currently We are using cordova-plugin-iroot but still pen test team able to collect the data using Frida tool.

**Comment by vv619-perf** [comment]
hi @msathya03 
we did the following mitigations:

- Prevented the application from running on a rooted device, using the plugin ("cordova-plugin-iroot": "^3.1.0")
- Cleared window cache
- Local storage was always cleared when the user logged out
- All the values saved in local storage were encrypted
- Unused variables in memory were cleared whenever its use was complete

**Comment by msathya03** [comment]
> hi @msathya03 we did the following mitigations:
> 
> * Prevented the application from running on a rooted device, using the plugin ("cordova-plugin-iroot": "^3.1.0")
> * Cleared window cache
> * Local storage was always cleared when the user logged out
> * All the values saved in local storage were encrypted
> * Unused variables in memory were cleared whenever their use was complete
> 
> But from my communication with the security team, they were happy when the device was not working in the rooted device and they couldn't get any more data.

Thanks so much !
