### ISSUE TITLE
 We are using the ionic 5 app and installed this plugin and We are unable to test the app on the android simulator.

### ISSUE THREAD

**Issue by quickbook** [silkimen/cordova-plugin-advanced-http#462]
**System info**

affected HTTP plugin version: [3.0.1]
affected platform(s) and version(s): [Android 10]
affected device(s): [ Android Simulator]
cordova version: [10.0.0]
cordova platform version(s): [android 9.0.0]

**Minimum viable code to reproduce**

e.g.:
 this.httpNative.setSSLCertMode('pinned')
          .then(() => {
            //alert('[SUCCESS] SSL Pinning Starts!');
            console.log('[SUCCESS] SSL Pinning Starts!');
          })
          .catch((error) => {
            //alert('error ssl');
            console.log('[ERROR] SSL Pinning Fails!', error);
          });

Always goes on catch exception.

**Also added certificate path in config file **
 resource-file src="src/assets/certificates/certificate.cer" target="app/src/main/assets/www/certificates/certificate.cer" 
Seems it is not able to read the certificates from the  _**www/certificates**_  folder. Could you please let us know fix for this issue.

![Issue](https://user-images.githubusercontent.com/9023972/158508011-f158f10c-ca84-459c-a679-81d95c52b432.jpeg)

**Comment by silkimen** [comment]
Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.
