### ISSUE TITLE
Giving error : SSLHandshakeException for https SSL Self-signed certificate .

### ISSUE THREAD

**Issue by demoprojects123** [silkimen/cordova-plugin-advanced-http#475]
**You've got questions?**

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁

* README.md: https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http using the tag `cordova-plugin-advanced-http`
* Wiki: https://github.com/silkimen/cordova-plugin-advanced-http/wiki

And don't forget: If you get help, help others. Good karma rulez!

**Comment by silkimen** [comment]
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍
