### ISSUE TITLE
Does this plug-in only work with Angular? Import projects must have Angular /core installed

### ISSUE THREAD

**Issue by dadprogrammer** [silkimen/cordova-plugin-advanced-http#476]
**You've got questions?**

We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 😁

* README.md: https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http using the tag `cordova-plugin-advanced-http`
* Wiki: https://github.com/silkimen/cordova-plugin-advanced-http/wiki

And don't forget: If you get help, help others. Good karma rulez!

**Comment by dadprogrammer** [comment]
Does this plug-in only work with Angular? Import projects must have Angular /core installed

**Comment by silkimen** [comment]
No, this plugin works with all Cordova based applications.

Please read the [documentation](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md) carefully. We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks! 

* README.md: https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http using the tag `cordova-plugin-advanced-http`
* Wiki: https://github.com/silkimen/cordova-plugin-advanced-http/wiki
