### ISSUE TITLE
Could not connect to the server when post request

### ISSUE THREAD

**Issue by letseatcayman** [silkimen/cordova-plugin-advanced-http#478]
I'm using "cordova-plugin-advanced-http": "^3.2.1", plugin for post request call.

let postCall = this.http.post('url', {
  'name': 'xyz',
  'password': '****',
  'mode': 'authprev'
}, { 'Content-Type': 'application/x-www-form-urlencoded' });
return from(postCall);

Mostly getting issue on some of the iPhone devices, also it's working on android devices. When we call that post request getting "Could not connect to the server" error. Can you please let me know what's wrong with my code.

**Comment by silkimen** [comment]
Please use [StackOverflow](https://stackoverflow.com/questions/tagged/cordova-plugin-advanced-http) for this kind of questions.
