### ISSUE TITLE
[ Failed to construct 'Blob':] [Android] "advanced-http: an error occured during post processing response:..."

### ISSUE THREAD

**Issue by kernel-debugger** [silkimen/cordova-plugin-advanced-http#481]
**Describe the bug**
I'm making parallel range requests (10+) using this plugin with responseType option set to blob, some requests complete successfully while some fail with the following message 
"advanced-http: an error occured during post processing response: Failed to construct 'Blob': The provided value is not of type 'BlobPropertyBag'."

Tried setting responseType to "arraybuffer", but it made no difference.

I get no error on browser, this is specific to android (not tested on ios)

**System info**
 - affected HTTP plugin version: [3.3.1]
 - affected platform(s) and version(s): [android 11.0.0]
 - affected device(s): [ Tested on Android 11]
 - cordova version: 11
 - cordova platform version(s): [android 11.0.0]

**Are you using ionic-native-wrapper?**
NO, I'm using Cordova.

**Minimum viable code to reproduce**
Like I said, not every request fails, but this is the basic code.

     cordova.plugin.http.sendRequest("http://example.com", {
		method:"get",
		responseType:"blob",
		headers:{
			"Range": "bytes="+1024+"-"+10024
		}}, console.log, console.log);

**Screenshots**
![Screenshot_2022-09-26_12-36-19](https://user-images.githubusercontent.com/36005801/192219444-31e35368-4771-449d-a5d2-be725933ce44.png)

**Comment by kernel-debugger** [comment]
The problem was in my success callback.

**Comment by silkimen** [comment]
Thanks for the feedback, closing this, feel free to open a new issue, if this won't solve your problem! 👍
