### ISSUE TITLE
Error: package org.apache.cordova.file does not exist

### ISSUE THREAD

**Issue by MrShakes** [silkimen/cordova-plugin-advanced-http#49]
Build is working fine for IOS however failing for Android, I get this error:

```
/Users/olaxx/Desktop/Axx/ixx/platforms/android/src/com/synconset/cordovahttp/CordovaHttpDownload.java:18: error: package org.apache.cordova.file does not exist
import org.apache.cordova.file.FileUtils;
                              ^
/Users/olaxx/Desktop/Axx/ixx/platforms/android/src/com/synconset/cordovahttp/CordovaHttpDownload.java:49: error: cannot find symbol
                JSONObject fileEntry = FileUtils.getFilePlugin().getEntryForFile(file);
                                       ^
  symbol:   variable FileUtils
  location: class CordovaHttpDownload
```
Plugin version 1.8.1

My guess is that it just needs to point to the file plugin correctly

System:

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-sim : 5.0.8 
    Node    : v6.10.2
    npm     : 3.10.10 
    OS      : macOS Sierra
    Xcode   : Xcode 8.3.3 Build version 8E3004b 
```

**Comment by MrShakes** [comment]
Upgrading Android to version 6.3.0 solves the problem, some incompatibility issues there.

**Comment by junaid5546** [comment]
**### Ionic file transfer plugin cause errors.** 

Ionic:

   Ionic CLI                     : 6.19.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.5
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3
Hi i am using ionic capacitor .
Here is info:

Capacitor:
   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : 3.4.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v16.13.2 (/usr/local/bin/node)
   npm    : 8.1.2
   OS     : macOS Monterey

**I am getting this error when i add FileTransfer plugin form cordova.**

/Users/muhammadgul/dm-mobile-app/android/capacitor-cordova-android-plugins/src/main/java/org/apache/cordova/filetransfer/FileTransfer.java:49: error: package org.apache.cordova.file does not exist

import org.apache.cordova.file.FileUtils;
                              ^
/Users/muhammadgul/dm-mobile-app/android/capacitor-cordova-android-plugins/src/main/java/org/apache/cordova/filetransfer/FileTransfer.java:851: error: cannot find symbol
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");
                        ^
  symbol: class FileUtils
/Users/muhammadgul/dm-mobile-app/android/capacitor-cordova-android-plugins/src/main/java/org/apache/cordova/filetransfer/FileTransfer.java:851: error: cannot find symbol
                        FileUtils filePlugin = (FileUtils) pm.getPlugin("File");
                                                ^
  symbol: class FileUtils

**Comment by alejob711** [comment]
> **### Ionic file transfer plugin cause errors.**
> 
> Ionic:
> 
> Ionic CLI : 6.19.1 (/usr/local/lib/node_modules/@ionic/cli) Ionic Framework : @ionic/angular 6.1.5 @angular-devkit/build-angular : 13.0.4 @angular-devkit/schematics : 13.0.4 @angular/cli : 13.0.4 @ionic/angular-toolkit : 5.0.3 Hi i am using ionic capacitor . Here is info:
> 
> Capacitor: Capacitor CLI : 3.5.1 @capacitor/android : 3.5.1 @capacitor/core : 3.5.1 @capacitor/ios : 3.4.1
> 
> Utility:
> 
> cordova-res : 0.15.4 native-run : 1.6.0
> 
> System:
> 
> NodeJS : v16.13.2 (/usr/local/bin/node) npm : 8.1.2 OS : macOS Monterey
> 
> **I am getting this error when i build and run project in Android or Ios add FileTransfer plugin form cordova.**
> 
> /Users/muhammadgul/dm-mobile-app/android/capacitor-cordova-android-plugins/src/main/java/org/apache/cordova/filetransfer/FileTransfer.java:49: error: package org.apache.cordova.file does not exist
> 
> import org.apache.cordova.file.FileUtils; ^ /Users/muhammadgul/dm-mobile-app/android/capacitor-cordova-android-plugins/src/main/java/org/apache/cordova/filetransfer/FileTransfer.java:851: error: cannot find symbol FileUtils filePlugin = (FileUtils) pm.getPlugin("File"); ^ symbol: class FileUtils /Users/muhammadgul/dm-mobile-app/android/capacitor-cordova-android-plugins/src/main/java/org/apache/cordova/filetransfer/FileTransfer.java:851: error: cannot find symbol FileUtils filePlugin = (FileUtils) pm.getPlugin("File"); ^ symbol: class FileUtils






Did you find any solution?
