### ISSUE TITLE
Error triggered on server response with status code 200

### ISSUE THREAD

**Issue by TheCelavi** [silkimen/cordova-plugin-advanced-http#53]
I am fetching data from: http://www.spreaker.com/show/2756602/episodes/feed

Simple get method. Promise resolves to error, Response status code is 200, and content of error property is XML content of above given URL.

Am I doing something wrong? Or it is a bug?

**Comment by nikmartin** [comment]
I am also getting a 200 response in the catch error object.

**Comment by silkimen** [comment]
Hi TheCelavi,

which version of this plugin are you using? Which platforms are affected? Do you use the ionic-native wrapper?

**Comment by silkimen** [comment]
This issue should be fixed with upcoming version 1.9.1. See issue #58 for further information.

@TheCelavi I'm closing this issue now. Please feel free to re-open it, if version 1.9.1 is not fixing your problem.

**Comment by TheCelavi** [comment]
@silkimen Sorry for not replying - your response/solution is very acceptable for me, thank you!
