### ISSUE TITLE
Requests are not responding on iOS with non-string values in header object

### ISSUE THREAD

**Issue by emreeay** [silkimen/cordova-plugin-advanced-http#54]
Firstly, thank you so much for this plugin. It's the only usable plugin for these kind of requirements.

I noticed a little, but a frustrating issue on iOS. If there is non string value in header object, plugin returns nothing.  I didn't stumble upon the same issue on Android however. It works well on there. 
For example:

```
cordova.plugin.http.get('https://google.com/', {
  id: 12,
  message: 'test'
}, { "somevar": "2" }, function(response) {
  console.log(response.status);
}, function(response) {
  console.error(response.error);
});
```
 works well. However, if we change "someVar"s value into integer 2, using like this:

```
cordova.plugin.http.get('https://google.com/', {
  id: 12,
  message: 'test'
}, { "somevar": 2 }, function(response) {
  console.log(response.status);
}, function(response) {
  console.error(response.error);
});
```
That's not working. I'm changing all of the header values to string but, you may want to handle this exception.

Thank you again!

**Comment by silkimen** [comment]
Hi emreeay,

thank you, you're right! It should at least throw an error instead of doing nothing.
