### ISSUE TITLE
SSL Pining is working after removing certificate.

### ISSUE THREAD

**Issue by Deepanshwad** [silkimen/cordova-plugin-advanced-http#55]
Hi, 

First of all SSL Pining is working as expected but for the first time like we add certificate and run the application, it works  but if we remove certificate and re-run the app than it again works and get the success response. Ideally it shouldn't work as i have removed the certificate file from assets folder.

**Comment by silkimen** [comment]
HI Deepanshwad,

that's interesting. Honestly, I've never tested this use-case.

- Which version of this plugin are you using?
- Which platforms are affected?
- Do you use the ionic-native wrapper?

**Comment by Deepanshwad** [comment]
Hi,
Thanks, please find my response:
Which version of this plugin are you using?- **cordova-plugin-advanced-http 1.9.0**
Which platforms are affected? **I am using on Android**
Do you use the ionic-native wrapper? **YES**

**Comment by Polgabarro** [comment]
Same here +1

**Comment by silkimen** [comment]
Hi guys, please check with latest version. Closing this, feel free to open a new issue, if this won't solve your problem!
