### ISSUE TITLE
clearCookies doesn't take effect

### ISSUE THREAD

**Issue by Immortalt** [silkimen/cordova-plugin-advanced-http#59]
I run the code
`cordova.plugin.http.clearCookies();`
However the cookie still exists.
The server still get the cookie so I failed to achieve my function.
also,the setCookie function went with errors.
How can I fully control my cookies？

**Comment by silkimen** [comment]
Hi Immortalt,

Can you please provide following information?

- plugin version
- cordova version
- cordova platform versions
- which platforms are affected
- example snippet of code

Thank you!

**Comment by Immortalt** [comment]
plugin version: 1.9.0
cordova version: 6.5.0
cordova platform versions: android 6.2.3
which platforms are affected:android
example snippet of code:
`cordova.plugin.http.clearCookies();
cordova.plugin.http.setDataSerializer('urlencoded');
cordova.plugin.http.post(url, data, head, function (response) {
      try {
        resp(response);
      } catch (e) {
        err(e);
        console.error(e);
      }
    }, function (response) {
      err(response);
    });`

**Comment by Immortalt** [comment]
I'm waiting for you online, it's urgent.

**Comment by silkimen** [comment]
I can't reproduce your problem. You can also check [my specs here](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/test/app-test-definitions.js#L335-L352) as reference. 

But I don't understand exactly what you're doing in your example snippet of code. What are `resp()` and `err()` doing? Why do you encapsulate `resp()` into a try-catch block?

> Besides, I use
```
var cookie = cordova.plugin.http.getCookieString(this.apiAccountUrl);
var sessionid = this.getCookie(cookie, "sessionid");
```
> to get the sessionid, but returned "".

Can you please show me the implementation of `this.getCookie()`? What's the value of the variable `cookie`?

**Comment by Immortalt** [comment]
`getCookie(cookie, name) {
        var arr, reg = new RegExp("(^| )" + name + "=([^;]*)(;|$)");
        if (arr = cookie.match(reg))
            return arr[2];
        else
            return "";
    }`

**Comment by Immortalt** [comment]
Finally I solved the problem.
Anyway, Thank you very much!

**Comment by gnochi** [comment]
@Immortalt I have a very similar Issue with the native Cookie handling on iOS. Would you mind sharing your solution ? Thanks in advance.
