### ISSUE TITLE
XCSRF token handling

### ISSUE THREAD

**Issue by ChanChanGR** [silkimen/cordova-plugin-advanced-http#60]
cordova-plugin-advanced-http doesn't have a header to send csrf token in post request to sap gateway..is there any solution?

**Comment by ChanChanGR** [comment]
How to fetch csrf token in cordova get request??

**Comment by silkimen** [comment]
Hi ChanChanGR,

I'm sorry, but I didn't understand your problem. Do you want to set a header during post request?

This is possible by providing a header object, e.g.:
```js
cordova.plugin.http.post('http://www.example.com/', {}, { 'X-Csrf-Token': 'your-csrf-token' });
```

Please check the [README](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/README.md) file for API documentation. You can also find many examples in the [spec file](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/test/app-test-definitions.js).

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
