### ISSUE TITLE
cordova.plugin.http.setCookie went wrong

### ISSUE THREAD

**Issue by Immortalt** [silkimen/cordova-plugin-advanced-http#62]
plugin version: 1.9.0
cordova version: 6.5.0
cordova platform versions: android 6.2.3
which platforms are affected:android
example snippet of code:

```js
cordova.plugin.http.setCookie(this.apiAccountUrl, { "sessionid": "" }, {
            http: false,
            secure: true,
            now: new Date(),
            ignoreError: false
        });
```

these code went wrong with error:
str.trim is not a function

**Comment by silkimen** [comment]
You need to provide a RFC-compliant cookie string, NOT an object as second parameter. e.g.:

```js
cordova.plugin.http.setCookie(this.apiAccountUrl, 'sessionid=', {
  http: false,
  secure: true,
  now: new Date(),
  ignoreError: false
});
```

But why do you want to set an empty cookie? You can also delete the cookies you don't need.

By the way, this is explained in the documentation:
> Add a custom cookie. Takes a URL, a **_cookie string_** and an options object. See ToughCookie documentation for allowed options.

**Comment by Immortalt** [comment]
Thank you! I'm trying your code.

**Comment by Immortalt** [comment]
I also failed to control my cookie.
It's the "Two Cookie Header" problem.

> Accept-Charset: UTF-8
> Cookie: sessionid=
> Content-Type: application/x-www-form-urlencoded; charset=UTF-8
> Connection: Keep-Alive
> Accept-Encoding: gzip
> Cookie: sessionid=9821f8c8b250caa2d23de93e47056460; userid=1021362
> Content-Length: 193

**As the request has two cookie header, although the plugin controlled the first cookie header,
the second cookie header which came form the set-cookie header cause server can't recognize the cookie.**

**Comment by Immortalt** [comment]
Finally I solved the problem.
Anyway, Thank you very much!

**Comment by Immortalt** [comment]
Finally I solved the problem.
Anyway, Thank you very much!
