### ISSUE TITLE
Ability to upload multiple files

### ISSUE THREAD

**Issue by naveddeshmukh** [silkimen/cordova-plugin-advanced-http#63]
### Feature Request
Currently, the plugin only supports one file per upload request. However, there may be a scenario where multiple files have to be sent.

**Comment by iamjoyce** [comment]
In that case, does it mean that we only have these options to send multiple files to the server?

1. Send by base64 string with `post`

2. Send files with `uploadFile` and other variables with `post`

**Comment by amb-jarek** [comment]
@silkimen this missing feature block us completely. Are you planning to add this feature in near future?

**Comment by nilswitschel** [comment]
Started working on that issue at https://github.com/SDA-SE/cordova-plugin-advanced-http 
I'll add a multiple file upload via `multipart`.

**Comment by nilswitschel** [comment]
See PR: https://github.com/silkimen/cordova-plugin-advanced-http/pull/127

**Comment by Story5** [comment]
desire the feature, is there any further news?

**Comment by silkimen** [comment]
This feature was implemented in v2.2.0.
