### ISSUE TITLE
How to send FormData in post request?

### ISSUE THREAD

**Issue by Deepanshwad** [silkimen/cordova-plugin-advanced-http#64]
Hi,

Can you please help me out that how to send FormData in post request. I have tried at my end but its not going.

Thanks

**Comment by maximilianloy** [comment]
Same issue here:

`        var formData = new FormData();
        formData.append('upload_preset', this.upload_preset);
        formData.append('file', new Blob([new Uint8Array(imageData)], { type: 'image/jpg' }));
        return this.http.post(this.config.imageUploadUrl, formData)
          .then((res) => {
`

**Comment by Deepanshwad** [comment]
Hi @silkimen ,

Can you please help on this? At-least we should know weather this plugin support or not? Then i'll move into some different direction.

Thanks

**Comment by Kanishk94** [comment]
Hi
Same issue here:
I’m trying to post a FormData type object, but it doesn’t seem to work for me. Below are some lines from my code, just see if you can suggest something in this approach:

let clientConfirmData = new FormData();
var blob = new Blob([this.signature], { type: ‘image/png’ });

clientConfirmData.append(“patientConfirmation”, blob);

this.http.post(url, clientConfirmData, headers)
.then(data =>{

                                    })
                                    .catch(error => {
                                      
                                    }));

**Comment by silkimen** [comment]
Hey guys,
unfortunately, this is not supported by this plugin. @Kanishk94 you can use `uploadFile` for transfering a file, but you won't be able to add custom fields.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!

**Comment by aecvargas** [comment]
@silkimen I'm having issues with uploadFile, could you please see this from my stackoverflow question:

In my app I have the cordova camera plugin which allows me to take a picture and I can get the URI from it.

```
const options: CameraOptions = {
  quality: 100,
  destinationType: this.camera.DestinationType.FILE_URI,
  encodingType: this.camera.EncodingType.JPEG,
  mediaType: this.camera.MediaType.PICTURE
};
this.camera.getPicture(options).then(
  imageURI => {

  },
  err => {

  }
);
```
I then use that URI to upload to my server.

```
this.http
    .uploadFile(
        'https://example.com/pages/attachments.php, {
            action: 'INSERT'
        }, {},
        'file:///storage/emulated/0/Android/data/io.ionic.starter/cache/1583144250046.jpg',
        'picture'
    )
    .then(
        fileResult => {
            console.log(fileResult);
        },
        err => {

        }
    );
```
But I am getting these errors from the console.log result:

> Undefined index: file in on line 1235
> 
> Undefined index: file in on line 1236

These are the lines in attachments.php:

```
// The tmp_name is the name of the temporary file on the server.
$tmp_name = $_FILES['file']['tmp_name'];
$name = $_FILES['file']['name'];
```
It seems like that $_FILES is empty but i'm not sure why. I assumed using http.uploadFile would send the file but i'm not sure why it isn't. Any help?
