### ISSUE TITLE
JSON with multiple layers is not properly posted

### ISSUE THREAD

**Issue by maximilianloy** [silkimen/cordova-plugin-advanced-http#65]
I am trying to post to my server a JSON object but only the "first layer" is parsed properly. Seems like it does not do "deep parsing":

```
var observation = {
    images: [
    {
        filename: "file:\\/\\/\\/storage\\/emulated\\/0\\/Android\\/data\\/eu.snowsafe.SnowSafe\\/cache\\/IMG_20180104_080422.jpg?1515508709053"
    }],
    cracking: 'false',
    provinceId: 'AT7',
    langCode: 'DE',
    avalanche:
    {
        kind: null,
        dimension: null,
        distance: null
    },
    timestamp: '2018-01-04T07:04:23.000Z'
}

this.HTTP.post(this.config.observationUploadUrl, observation, {}).then((res) => {...}
```

This is what I receive at the server side:
```
{
    images: '[{"filename":"file:\\/\\/\\/storage\\/emulated\\/0\\/Android\\/data\\/eu.snowsafe.SnowSafe\\/cache\\/IMG_20180104_080422.jpg?1515508709053"}]',
    cracking: 'false',
    provinceId: 'AT7',
    langCode: 'DE',
    avalanche: '{"kind":null,"dimension":null,"distance":null}',
    timestamp: '2018-01-04T07:04:23.000Z'
}
```

**Comment by dembal1990** [comment]
Hy
I use this  befor request and solve my same problem:
` this.http.setDataSerializer("json");`
I hope this will help you

**Comment by silkimen** [comment]
Hi maximilianloy,
I can't reproduce your problem on my side. I've also written a test case for this [(see app-test-definitions.js#L441-L448)](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/test/app-test-definitions.js#L441-L448). Did you configure serializer correctly, just like dembal1990 suggested?

**Comment by maximilianloy** [comment]
I did not call setDataSerializer("json") so that is most likely the issue. But as I also have to send form data I can not use the plugin in this module.
