### ISSUE TITLE
ssl pinning not working

### ISSUE THREAD

**Issue by ChanChanGR** [silkimen/cordova-plugin-advanced-http#67]
I am using cordova-plugin-advanced-http plugin to enable ssl pinning in my cordova project,I downloaded DER encoded binary format with .cer extension certificate from url in chrome and placed certificate inside www/certificates,

cordova.plugin.http.enableSSLPinning(true, function() {
  console.log('success!');
}, function() {
  console.log('error :(');
}
In above piece of code it always goes to success callback and get/post data from/to server but **sslpinning is not set to true**. Even if i add certificates which are not related to that server still its working fine instead of giving error?? so do i need to add or change anything ??

**Comment by nileshbandekar** [comment]
Same issue even if we don't add certificate and set as 'pinned' won't giving any error..
Kindly help
