### ISSUE TITLE
Does this plugin support setting up interceptor with ionic3 ?

### ISSUE THREAD

**Issue by Jeason123** [silkimen/cordova-plugin-advanced-http#68]
I have no idea how  the interceptor  is set  to ionic3 by the cordova-plugin-advanced-http, any professional can help me? thanks

**Comment by anooprehman** [comment]
I followed this [tutorial](https://blog.paulhalliday.io/2017/09/20/using-angular-httpinterceptor-with-the-new-httpclient/) to implement Angular HttpInterceptor with ionic 3. Hope this helps.

**Comment by silkimen** [comment]
Hi Jeason123,

this plugin doesn't support a interceptor, but you could write your own wrapper for this plugin and implement an interception pattern.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
