### ISSUE TITLE
The cookie can't be sent in the http header

### ISSUE THREAD

**Issue by QAQMiao** [silkimen/cordova-plugin-advanced-http#69]
Hi,  I want to send the cookie in the http header, and the code is
`this.http.get(url,params,{
      Cookie:'token=' + token
  })`

But the cookie in the request is empty, and there is no error in console…is there any solution?

**Comment by silkimen** [comment]
Hi QAQMiao,

you need to set Cookies by using `cordova.plugin.http.setCookie(url, cookie, options)`. It's not meant to be set via headers. Your header param will be overwritten by internal cookie handling.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
