### ISSUE TITLE
Issue when compiled with --prod flag

### ISSUE THREAD

**Issue by TheCelavi** [silkimen/cordova-plugin-advanced-http#70]
If I compile app (android, ios) without --prod flag, everything works fine.

If I do that using above mentioned flag, HTTP request errors out.

I am trying to get this feed: https://www.spreaker.com/show/2756602/episodes/feed

Any idea?

**Comment by silkimen** [comment]
Is `--prod` an ionic flag? I've never used this and I don't know it; at least not for cordova.

Which kind of error messages do you get? Can you please post an example?

Would you please create an MVP app, so I can check what's going wrong?

**Comment by TheCelavi** [comment]
Yes, it is. I turns out that issue is not in regards to your plugin, it is related to Ionic in general.

Namely, it tells to Ionic to compile javascript in production mode, which includes, but not limits, to removal of various console.log outputs etc... in order to speed up execution.

I do not think that this is right address for this issue. I am closing this, thank you for your time.

**Comment by silkimen** [comment]
Ah OK, thanks for this interesting information!

**Comment by TheCelavi** [comment]
Thank you for your hard work!

**Comment by akashdeepsharma1991** [comment]
Hii can you provide more detail in this.. i am having the same issue.. i am stuck in a project i am using the latest ionic version

**Comment by TheCelavi** [comment]
@akashdeepsharma1991 Oh, dude, so sorry, I can not remember, it was looooong time ago. If I closed it, I found a solution but beat me if I can remember what was the issue and how I did solve it. So sorry.
