### ISSUE TITLE
Android: "Content-Type" header can't be overridden

### ISSUE THREAD

**Issue by jaygauten** [silkimen/cordova-plugin-advanced-http#78]
Found in Android

Here's my code:

```
this.http.setDataSerializer("json");
this.http.setHeader("Content-Type", "application/json");

this.http.post(this.endpoint
        , {"request":"UserLogin","username":username,"password":password}
        , {})
          .then((res)=> {
            console.log(res.data);
          })
          .catch((err)=> {
            console.log(err);
          });
```

but when i checked the headers the `Content-Type` has a value of `application/json; charset=UTF-8` instead of the `application/json` only. Even if i add the headers as a POST parameter, headers are still ignored.

**Comment by silkimen** [comment]
Hi jaygauten,

did you also try to set another header? I don't see a problem here, if only the `content-type` is affected. In the end it is actually UTF-8 encoded JSON. That's what the plugin is doing when you set `json` serializer. Why are you trying to override this header?

**Comment by jaygauten** [comment]
I need the content-type to be `application/json` without the charset, beacause the server im using only accepts the ˙Content-Type` header without the charset.

**Comment by silkimen** [comment]
Okay I see, I'll fix it.
