### ISSUE TITLE
Android API <=19 doesn't support HTTP PATCH request

### ISSUE THREAD

**Issue by chax** [silkimen/cordova-plugin-advanced-http#79]
Android KitKat 4.4 (API 19) and older, doesn't support HTTP PATCH method.

https://stackoverflow.com/questions/25163131/httpurlconnection-invalid-http-method-patch/

**Comment by chax** [comment]
Maybe rewrite Android part of this plugin to use OkHttp library.
Current solution relies on Android libraries to support PATCH (which they don't for android versions <=4.4.x). Android uses OkHttp as their underlying library, but Android 4.4.x and older has too old version of OkHttp, therefore PATCH method doesn't work.

**Comment by silkimen** [comment]
Ok, thanks for this info! But rewriting the Android part seems to be a lot of work, especially a lot of testing effort. I can't do this atm. Maybe someone wants to do that and send me a PR?

**Comment by chax** [comment]
I may have quicker solution which doesn't involve complete rewrite of Android part of plugin.
We can use OkUrlFactory (part of OkHttp lib) and replace current CONNECTION_FACTORY.
I'm exploring this solution right now so maybe you can expect some PR from me soon, but i can't promise anything.

**Comment by chax** [comment]
I implemented my solution in Pull Request #82
Like i said in my previous comment, i just replaced Connection Factory with okhttp-urlconnection lib implementation of Connection Factory, and i tested both in older Android versions as well as newer Android versions. Tested both with http and https (including invalid certs using acceptAllCerts option).
Now it works for all request methods (including PATCH).

@silkimen Can you take a look at my solution and merge it if it's good, or tell me if i can change or fix anything before merge.
This is really needed for my project and i would like this to be merged ASAP.

**Comment by chax** [comment]
@silkimen Thanks for merging my PR and making new release 1.10.2, this is very much appreciated.

**Comment by silkimen** [comment]
@chax you're welcome! 😃

**Comment by chax** [comment]
You can now update your okhttp-urlconnection dependency to 3.10 which was just released few days ago and put it in your next release 1.11.0.

https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp-urlconnection

https://github.com/silkimen/cordova-plugin-advanced-http/blob/4a437f94354b1f6224f5dc6d4c2a4dc0dc4befc3/plugin.xml#L71
