### ISSUE TITLE
ionic plugin missing setCookie()

### ISSUE THREAD

**Issue by tomhartz** [silkimen/cordova-plugin-advanced-http#86]
Hello @silkimen.  I am using this in an ionic app, and I have a situation where I need to call setCookie() in my app code.

Can you make another pull request to the ionic team to get the new setCookie method exposed to ionic?  It should be similar to this recent one I found from you:
https://github.com/ionic-team/ionic-native/pull/2054

Thanks so much!!!

**Comment by silkimen** [comment]
There is already an open issue in ionic-native repo [ionic-native#2249](https://github.com/ionic-team/ionic-native/issues/2249). I'll look into the matter.

**Comment by silkimen** [comment]
I've created a PR for [ionic-native#2249](https://github.com/ionic-team/ionic-native/issues/2249). Closing this, feel free to open a new issue, if this won't solve your problem!
