### ISSUE TITLE
Reading HTTP Only cookies?

### ISSUE THREAD

**Issue by BorntraegerMarc** [silkimen/cordova-plugin-advanced-http#87]
I wanted to ask if the method `getCookieString` also returns HTTP only cookies from a response on iOS & Android? (obviously it's not possible on the browser).

**Comment by silkimen** [comment]
Hi Marc, yes, it does atm. But actually it's not a good idea to expose them into JS context. Maybe I'll remove them in a future version. Are you asking, because you're concerned about security?

**Comment by BorntraegerMarc** [comment]
Thanks for your answer @silkimen
Actually I think this is the expected behavior. We have implemented a session based authenication and on the server a HTTPOnly cookie is set. For web browsers this works great as the cookie is persisted and after closing & re-opening the browser the user is still authenticated.

I was asking, to check if we can get the same behavior on mobile devices. I'm not 100% sure if the HTTPOnly cookie is persisted on the mobile device if the app is sent to background or killed.

So to fix this, we want to store the HTTPOnly cookie in the secure storage of the device and manually append it, if a "native request" is made.

So yeah: I agree that the cookie should never be exposed into a JS context. Only to the native context :)
