### ISSUE TITLE
Self Signed certificate pinning is not possible on iOS with ionic

### ISSUE THREAD

**Issue by jeandesma** [silkimen/cordova-plugin-advanced-http#9]
Hello,

I have an issue concerning SSLPinning on iOS with ionic. My code is working well on android but I cannot make it work on iOS. Here is my code:

    @Injectable()

    @Component({
      providers: [CorrespondanceProvider]
    })

    export class ProductProvider {
    ...
      constructor(@Inject(EnvVariables) public envVariables, public http1: HTTP, private platform:Platform) {
        this.platform.ready().then(
          () => {
            this.http1.validateDomainName(false)
            .then(() => this.http1.acceptAllCerts(false)
            .then(() => this.http1.enableSSLPinning(true)
            .then(() => this.http1.setDataSerializer("json"))));
           }
        );
      }

    canLog(credentials, url){
        if (this.data){
          return Promise.resolve(this.data);
        }
        let header = { 'Content-Type' : 'application/json'};
        let body = {
                "credentials":{
                    "username": credentials.username, 
                     "password": credentials.password
                }
              };
    
        return new Promise((resolve, reject) => { 
          this.http1.post(`${this.envVariables.Endpoint}/`+url, body, header)
          .then(response => {
            this.data = JSON.parse(response.data);
              resolve(this.data);
          },
          err => reject(err)
          )
        });
      }
    }

Each time I make a request I get the following error: {"status":-1,"error":"cancelled"} which seems to correspond to a -999 error in AFNetworking.

After a little research, I discovered that acceptAllCerts(true) only put securityPolicy.allowInvalidCertificates to true, which means that it can accept also self signed certificates (even with the enableSSLPinning set to true) and nothing else, while in Android, acceptAllCert(true) is the opposite of enableSSLPinning(true). Please tell me if I am wrong, but this is a little confusing.

Therefore I also tried to set acceptAllCert to true in the code above, but I still get the same error.
(the certificate is in the right place in my project and is found correctly, if I do not put enableSSLPinning to true, everything work fine).

Could you please help?

**Comment by tomNjerry** [comment]
How did you managed to add it on android?
Cas Im getting a direct error as Plugin not installed.
My stack is :
ionic 2
Angular 2
cordova

**Comment by jeandesma** [comment]
Hello tomNjerry,
Please see this issue: https://github.com/silkimen/cordova-plugin-advanced-http/issues/8. My last comment should fix your issue.

**Comment by silkimen** [comment]
Sorry for the late response. I can confirm I'm having the same issue here, but I couldn't figure out why this is happening, yet.

**Comment by tomNjerry** [comment]
waiting for positive reply for SSL pinning

**Comment by matijse** [comment]
I've noticed that on iOS the order of the calls is important.

First call `enableSSLPinning(true)` and then `acceptAllCerts(true)`.

Details:

When you call `enableSSLPinning` [source](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/src/ios/CordovaHttpPlugin.m#L111), a `AFSecurityPolicy`object is created.

When you call `acceptAllCerts` [source](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/src/ios/CordovaHttpPlugin.m#L134), properties on that `securityPolicy` object are set.

So if you first call `acceptAllCerts`, it changes the property on `securityPolicy`, but when you then call `enableSSLPinning`, a completely new `securityPolicy` is created, with default settings for allowing all certificates.

**Comment by silkimen** [comment]
Can someone please check if this issue is still available with current version 1.10.2? It's important to use a DER encoded certificate NOT a PEM encoded one.

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!
