### ISSUE TITLE
the params type can't be number

### ISSUE THREAD

**Issue by xjy0925** [silkimen/cordova-plugin-advanced-http#91]
http.post(url,  {id: 123}, headers)
It shows error: "advanced-http: invalid params object, needs to be an object with strings"

**Comment by silkimen** [comment]
That's actually true. Parameters need to be strings NOT numbers.

```js
// You'll need to provide this:
http.post(url, { id: "123" }, headers);

// Instead of:
http.post(url, { id: 123 }, headers);
```

**Comment by silkimen** [comment]
Closing this, feel free to open a new issue, if this won't solve your problem!

**Comment by dalezak** [comment]
Hmm, seems like a pretty serious limitation of the plugin if can't support numbers as parameters?

I'm facing this same issue now, gonna take a lot of effort to cast all parameters like `limit`, `offset`, etc in all my requests 😞

**Comment by kenberkeley** [comment]
GraphQL

```graphql
query GetUserById ($id: Int!) {
  users (limit: 1, where: {
    id: $id
  }) {
    id
    name
    age
  }
}
```

Request payload:

```js
// POST /graphql
{
  query: "↵query GetUserById ($id: Int!) {↵  users (limit: 1, where: {↵    id: $id↵  }) {↵    id↵    name↵    age↵    }↵}",
  variables: { id: "1" }
}
```

Response:

```
[400] Variable "$id" got invalid value "1"; Expected type Int; Int cannot represent non-integer value: "1"
```
