### ISSUE TITLE
response.headers not deserialized for platform browser

### ISSUE THREAD

**Issue by tomhartz** [silkimen/cordova-plugin-advanced-http#92]
Hi @silkimen, appreciate the support for platform browser.  I am attempting to use it and I noticed this different behavior in browser vs. mobile platforms.  In this example, I am using `http.setDataSerializer('urlencoded');` and doing a post.

on iOS/Android:
```
> typeof(response.headers)
object

> response.headers
{"server":"Apache",
"content-type":"text/html;charset=UTF-8",
"location":" https://myserver.domain.com/more-uri/Thing-I-Care-About",
"date":"Tue, 13 Mar 2018 19:39:35 GMT",
"content-length":"389",
"cache-control":"no-store",
"connection":"close"}
```
I then have some code to parse the Thing-I-Care-About from the "location" header value:
```
var locArr = response.headers['location'].split('/');
var thing = locArr[locArr.length - 1];  // "Thing-I-Care-About"
```

Difference in browser:
```
> typeof(response.headers)
"string"

> response.headers
"location: https://myserver.domain.com/more-uri/Thing-I-Care-About
date: Tue, 13 Mar 2018 19:09:05 GMT
cache-control: no-store
server: Apache
connection: close
content-length: 389
content-type: text/html;charset=UTF-8
"
```

The problem I'm running into then is in my code, `reponse.headers['location']` is undefined, and I get this exception: "Cannot read property 'split' of undefined'.

If I have to, I can change my app code to detect when running in the browser, and parse the headers myself.  Ideally though, I want to avoid adding code everywhere to behave differently on certain platforms.  Do you think your plugin can be changed to deserialize the response headers for browser  the same as other platforms?

~Thanks

**Comment by silkimen** [comment]
Hi tomhartz, I must have missed this detail. Will fix this. Thanks for reporting!
