### ISSUE TITLE
recommendation, usage instead of cordova-http?

### ISSUE THREAD

**Issue by JhonnyJason** [silkimen/cordova-plugin-advanced-http#94]
Hallo, 
Until now I was using the cordova-http plugin and just noticed that this currently maintained/worked on plugin exists :-)

So my question is if it is recommended at the current state to use the cordova-plugin-advanced-http for production?

Thanx!

**Comment by silkimen** [comment]
Hi Lenard,

well this plugin has a lot more features and also bugfixes than the old cordova-plugin-http ([see commit list](https://github.com/silkimen/cordova-plugin-advanced-http/commits/master) and [changelog](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/CHANGELOG.md)). Many people are using it ([see download stats](https://www.npmjs.com/package/cordova-plugin-advanced-http)) and it's also part of ionic-native ([see documentation](https://ionicframework.com/docs/native/http/)).

But in the end it's up to you to decide whether you are willing to use this plugin in production. It's an OSS project under MIT license.

**Comment by JhonnyJason** [comment]
That's super awesome :-) thank you for your work therein!
I will use it then and raise issues when I encounter some ;-)

Cheers!
