### ISSUE TITLE
Android request and response are seen in burp suite

### ISSUE THREAD

**Issue by Parvezkhan-Official** [silkimen/cordova-plugin-advanced-http#95]
Hi Silkimen,
I am using this plugin for certificate pinning. i have build the app by implementeing the steps as mentioned in the Ionic page https://ionicframework.com/docs/native/http/

But my android request and response are seen in burp suite. I need to fix this as soon as possible.
I have used it like below for each request.
this.http.setHeader('Access-Control-Allow-Origin', '*');
this.http.enableSSLPinning(true);
this.http.acceptAllCerts(true);
this.http.setRequestTimeout(180);//3 minutes

What is the best way to implement if my steps are wrong

Please help me solve this so that i can try it on iOS App.

**Comment by Parvezkhan-Official** [comment]
Hi silkimen,
Thanks for the reply
Doing certificate pinning to avoid man in the middle attacks.

For information to you and others, it was problem with the certifcate , when the setup proper certificate at the server able to achived now in Android.
I have successfully now done the Certificate pinning in Android but facing issue in IOS. Giving error error : "Cancelled" & status: -1 in IOS.
Checked with this.http.enableSSLPinning(true); only first time and second time used
this.http.enableSSLPinning(true);
this.http.acceptAllCerts(true);

taken help from link https://github.com/silkimen/cordova-plugin-advanced-http/issues/9

Should i do somthing extra in IOS to acheive certificate pinning to avoid Man in the middle attacks.

Thanking you in anticipation

**Comment by silkimen** [comment]
You should be just fine using an binary (DER formatted) cert and enabling cert pinning `this.http.enableSSLPinning(true)`. Actually, you should NOT enable accepting all certs `this.http.acceptAllCerts(true)`.

If it's working for Android but not for iOS it's most likely because you're using a Base64 (PEM formatted) cert (in your App, not the server side).

**Comment by Parvezkhan-Official** [comment]
Thanks for the comments & support.
OK. It was the issue of Self signed certificate.
Will also check on IOS. Once everything is fixed and app is live then will update for others help and i will close this issue

**Comment by Parvezkhan-Official** [comment]
Hi Silkimen,
I have implemented certificate pinning with the help of this plugin. many thanks.
Please help me regarding error coming most of the time i login. Login is inconsistent. Sometimes able to login but many times giving below errors
1)There was an error with the request: java.net.ConnectException: Failed to connect to "url"
2)The request is timeout

Kindly help me i am stuck in this and project cannot be successfull if this login inconsistency persist.

Thanks & Regards

**Comment by silkimen** [comment]
Hi Parvezkhan, this is most likely a network or backend problem. Possible explanations include:
* the service has crashed or hasn't been started,
* your client is trying to connect using the wrong IP address or port, or
* server access is being blocked by a firewall that is "refusing" on the server/service's behalf

Please check the server logs for possible problems.
