### ISSUE TITLE
BUG: Double encoding

### ISSUE THREAD

**Issue by danielsogl** [silkimen/cordova-plugin-advanced-http#96]
I need to encode my URL to match some api calls. But as it turns out, the Cordova plugin also encodes the url again.

Original url: https://registry.npmjs.org/@ionic-native/device
After my encoding: https://registry.npmjs.org/@ionic-native%2Fdevice
After the double encode: https://registry.npmjs.org/@ionic-native%252Fdevice

Im not sure if its an bug or a feature? Is is possible to avoid this problem?

**Comment by Hanzofm** [comment]
Same problem here, In my case only on Android devices https://github.com/silkimen/cordova-plugin-advanced-http/issues/195

Did you solved?
