### ISSUE TITLE
Get request with params not working 1.11.1

### ISSUE THREAD

**Issue by praveenraji2i** [silkimen/cordova-plugin-advanced-http#97]
If send paramenters in get request not Working on 1.11.1 version, but its working in 1.10.1.

**Comment by Story5** [comment]
It's not work now on 1.11.1 when you pass the param whose type is not a string.

Like these 
```
{ type : 1 }
```
need to be change to
```
{ type : "1" }
```

It's feel like a bug and I am asking the author for fix it too.

**Comment by silkimen** [comment]
Please, follow up on #98.
