### ISSUE TITLE
param can't be other type except string on 1.11.1

### ISSUE THREAD

**Issue by Story5** [silkimen/cordova-plugin-advanced-http#98]
It is work on 1.9.1 when I pass the number type param.
```
this.sxhttp.get(URL_BANNER,{
      type : 1
    })
```
After update plugin to 1.11.1, it's invalid. Then I need to change my code to 
```
this.sxhttp.get(URL_BANNER,{
      type : "1"
    })
```

The param like `type : 1` is a normal json type.
Can author fix this bug for better use?

**Comment by Story5** [comment]
It's support to pass the number param to json follow to the [READ.md - get](https://github.com/silkimen/cordova-plugin-advanced-http#get)

**Comment by silkimen** [comment]
Hi guys, I see the confusion here, as I have changed the behavior without correctly updating the docs.

Before v1.11.0 some people were not understanding how to use the API properly. They tried to pass strings or nested objects as params object (second param in your example), leading to unexpected behavior.

e.g. having nested objects: `http://demo.com/?myVal=[object Object]`

I thought, it'd be a good idea to avoid misusage by throwing helpful error messages. I implemented a data type checker for both header and query param objects, validating against a whitelist.
So @Story5 while you are right, numbers are valid JSON data types, this is not about generating JSON output. It's about composing a query parameter string, consisting of strings. I thought it would be a good idea to be strict about data types. Previous versions were basically just doing a `toString()` implicitly. Now, you need to do this in your own coding.

**Comment by Story5** [comment]
@silkimen Thanks for your detailed elaboration. 
I change my param data type before pass it to the plugin function. It's solved and hope to help others.
```
for (const key in paramRef) {
      if (paramRef.hasOwnProperty(key)) {
        var element = paramRef[key];
        paramRef[key] = paramRef[key].toString();
      }
    }
```
Close the issue here.
