### ISSUE TITLE
App Store ipv6 rejected

### ISSUE THREAD

**Issue by Story5** [silkimen/cordova-plugin-advanced-http#99]
Hey guys!
Recently our app is rejected twice due to  can't connect on ipv6.
From apple's review screen shot, app  stop on ionic splash screen.
It's confirm that our web server support ipv6.
Using the plugin, is there extra code I need to set for ipv6?
I really appreciate your help  to publish our app.

**Comment by dalezak** [comment]
I also had an app rejected related to _Supporting IPv6-only Networks_ https://developer.apple.com/support/ipv6/, any suggestions on a fix for this?

**Comment by silkimen** [comment]
Hi guys, honestly I've never tested IPv6 with this plugin. I'll need to investigate this problem. But I've a tight schedule, atm. Is this problem occurring on iOS only or is Android also affected?

**Comment by dalezak** [comment]
In my case, looks like the issue might have been related to our server not supporting **IPv6**.

We've updated our server to support **IPv6** and I've replied to Apple to review the app again.

I'll let you know as soon as hear back from Apple whether the server change fixed the issue :+1:

**Comment by Story5** [comment]
In fact, our server do not support `IPv6`, caused app rejected. The plugin works well👍, and our app is ready for sale now after our server configure `IPv6` environment.
I close the issue here.

**Comment by dalezak** [comment]
Updating our server to support `IPv6`, also helped get our app approved without any code changes :+1:

**Comment by silkimen** [comment]
Ok, thanks for your feedback guys!
